### ISSUE TITLE
Crash with Appium 1.4.0Beta and 1.13.0-Android Mobile Automation

### ISSUE THREAD

**Issue by surekhapentela** [appium/appium-desktop#1093]
I have signin button to click on after launching the app, while clicking on the signin button with Appium 1.4.0beta or 1.13.0 app is crashing.

Appium 1.12.1 is fine but unable to capture controls on privacy policy page so upgraded to latest versions.

* Appium version (or git revision) that exhibits the issue: 1.14.0 Beta and 1.13.0
* Last Appium version that did not exhibit the issue (if applicable):1.12.1
* Desktop OS/version used to run Appium:Android 9
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:Samsung s8+ 
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

Please find the attached logfile
[Logcat-Appim-Crash.zip](https://github.com/appium/appium-desktop/files/3627695/Logcat-Appim-Crash.zip)

**Comment by surekhapentela** [comment]
Requesting can any one please have a look on this?

**Comment by surekhapentela** [comment]
any update on this?

**Comment by KazuCocoa** [comment]
Does this happen on the latest version, too?
(Is the crash the app under test side?)

btw, crash report in the log:

```
--------- beginning of crash\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: FATAL EXCEPTION: DiscoveryHandlerThread\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: Process: com.samsung.android.oneconnect:Core, PID: 14941\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: java.lang.SecurityException: Permission required to start wifi display scans: Neither user 10256 nor current process has android.permission.CONFIGURE_WIFI_DISPLAY.\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.hardware.display.IDisplayManager$Stub$Proxy.startWifiDisplayScan(IDisplayManager.java:849)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.hardware.display.DisplayManagerGlobal.startWifiDisplayScan(DisplayManagerGlobal.java:362)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.hardware.display.DisplayManager.semStartScanWifiDisplays(DisplayManager.java:1545)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.common.baseutil.WfdUtil.d(Unknown Source:122)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.manager.net.p2phelper.sep.SepP2pHelper.a(Unknown Source:304)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.manager.net.p2phelper.sep.SepP2pHelper.a(Unknown Source:258)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.manager.net.p2phelper.sep.SepP2pHelper.a(Unknown Source:220)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.manager.discoverymanager.SepDiscoveryManager.e(Unknown Source:446)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.samsung.android.oneconnect.manager.AbstractDiscoveryManager$DiscoveryWorkHandler.handleMessage(Unknown Source:1520)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.app.ContextImpl.enforce(ContextImpl.java:1924)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at com.android.server.display.DisplayManagerService$BinderService.startWifiDisplayScan(DisplayManagerService.java:2670)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:84)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:739)\
09-18 11:58:10.743 14941 15044 E AndroidRuntime: \
```
