### ISSUE TITLE
Infinite loader while gathering initial app source

### ISSUE THREAD

**Issue by yash3x** [appium/appium-desktop#1111]
## Appium Desktop

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Infinite loader while Gathering initial app source_

## Environment

- I am running Appium Desktop version _1.14.0 (1.14.0.20190705.4)_.
- I am on:
    - [X] Mac
- I am running macOS version _10.14.6 (18G95)_.
- I am testing on iOS version _12.4.2_

![screenshot](https://user-images.githubusercontent.com/3482664/66139383-f461c900-e61d-11e9-92d6-155b69f47a37.png)

**Comment by Neetzis** [comment]
Hi,

We have this same problem.  
Using-

Appium server --> appium@1.15.0-beta.1
Appium desktop for Mac --> .dmg (v1.14)→ https://github.com/appium/appium-desktop/releases
iOS 13
Xcode 11
Mac Mojave- 10.1.4.6

Has anyone found a workaround yet?

**Comment by Neetzis** [comment]
> Hi,
> 
> We have this same problem.
> Using-
> 
> Appium server --> appium@1.15.0-beta.1
> Appium desktop for Mac --> .dmg (v1.14)→ https://github.com/appium/appium-desktop/releases
> iOS 13
> Xcode 11
> Mac Mojave- 10.1.4.6
> 
> Has anyone found a workaround yet?



Found the workaround. Here it is, for anyone else struggling with infinite loading of inspector!

1. Start Appium server from the command line (1.15.0-beta.1)
2. Start the Appium Desktop app. Do NOT click "Start Server"
3. Launch the new session window (go up to "Appium desktop" (mac) or "File" (windows) and click new session from the menu)
4. Open the "Custom Server" tab of the new session window
5. Enter your local Appium server host and port (localhost / 4723)
6. Enter your capabilities
7. Start the session as normal. This will start a session using the Appium instance you have running on the command line, which is 1.15.0-beta.1

Original error:
On using Appium desktop 1.14 with server version 1.15.0-beta.1- accessibility inspector does not work. Loads infinitely.

Error - [HTTP] <-- GET /wd/hub/session/517796b5-170a-4258-ad88-228f502bf9b6/window/current/size 500 284 ms - 8215

&
Error-
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[MJSONWP (0713876f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[FBApplication resolve]: unrecognized selector sent to instance 0x282d10230

**Comment by KazuCocoa** [comment]
@Neetzis 
Could you share the full appium log?

**Comment by yash3x** [comment]
I'm able to inspect elements in the Appium Desktop version _1.15.0-1 (1.15.0-1.20191004.1)_

**Comment by MMannanikat** [comment]
Hello all,
I am able to reproduce this issue, also the workaround which @Neetzis has mentioned also not working for me. @KazuCocoa, I see the following error in Appium Log. it's failing on taking screenshot.

`2020-09-10 14:38:39:301 [MJSONWP (f0912a9e)] Driver proxy active, passing request on via HTTP proxy
2020-09-10 14:38:39:304 [WD Proxy] Matched '/wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/window/current/size' to command name 'getWindowSize'
2020-09-10 14:38:39:305 [WD Proxy] Proxying [GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/window/current/size] to [GET http://localhost:8200/wd/hub/session/cde0ded7-58c7-4e38-95c6-f201700b10ec/window/current/size] with body: {}
2020-09-10 14:38:39:326 [WD Proxy] Got response with status 200: {"sessionId":"cde0ded7-58c7-4e38-95c6-f201700b10ec","value":{"height":2028,"width":1080}}
2020-09-10 14:38:39:328 [WD Proxy] Replacing sessionId cde0ded7-58c7-4e38-95c6-f201700b10ec with f0912a9e-2b74-4c12-ba06-78fd9cd4a24c
2020-09-10 14:38:39:334 [HTTP] <-- GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/window/current/size 200 31 ms - 100
2020-09-10 14:38:39:334 [HTTP] 
2020-09-10 14:38:39:339 [HTTP] --> GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/context
2020-09-10 14:38:39:340 [HTTP] {}
2020-09-10 14:38:39:341 [MJSONWP (f0912a9e)] Calling AppiumDriver.getCurrentContext() with args: ["f0912a9e-2b74-4c12-ba06-78fd9cd4a24c"]
2020-09-10 14:38:39:342 [MJSONWP (f0912a9e)] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
2020-09-10 14:38:39:344 [HTTP] <-- GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/context 200 4 ms - 84
2020-09-10 14:38:39:346 [HTTP] 
2020-09-10 14:38:39:352 [HTTP] --> GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/contexts
2020-09-10 14:38:39:354 [HTTP] {}
2020-09-10 14:38:39:355 [MJSONWP (f0912a9e)] Calling AppiumDriver.getContexts() with args: ["f0912a9e-2b74-4c12-ba06-78fd9cd4a24c"]
2020-09-10 14:38:39:356 [AndroidDriver] Getting a list of available webviews
2020-09-10 14:38:39:357 [ADB] Running '/Users/mannanik/Library/Android/sdk/platform-tools/adb -P 5037 -s 8B9X16BEY shell cat /proc/net/unix'
2020-09-10 14:38:39:408 [AndroidDriver] Retrieved potential webviews; will filter out ones with no active pages
2020-09-10 14:38:39:409 [AndroidDriver] Found webviews: []
2020-09-10 14:38:39:410 [AndroidDriver] Available contexts: ["NATIVE_APP"]
2020-09-10 14:38:39:411 [MJSONWP (f0912a9e)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
2020-09-10 14:38:39:412 [HTTP] <-- GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/contexts 200 60 ms - 86
2020-09-10 14:38:39:416 [HTTP] 
2020-09-10 14:38:39:426 [HTTP] --> POST /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/context
2020-09-10 14:38:39:427 [HTTP] {"name":"NATIVE_APP"}
2020-09-10 14:38:39:429 [MJSONWP (f0912a9e)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","f0912a9e-2b74-4c12-ba06-78fd9cd4a24c"]
2020-09-10 14:38:39:430 [MJSONWP (f0912a9e)] Responding to client with driver.setContext() result: null
2020-09-10 14:38:39:432 [HTTP] <-- POST /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/context 200 6 ms - 76
2020-09-10 14:38:39:432 [HTTP] 
2020-09-10 14:38:39:439 [HTTP] --> GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/source
2020-09-10 14:38:39:440 [HTTP] {}
2020-09-10 14:38:39:443 [MJSONWP (f0912a9e)] Driver proxy active, passing request on via HTTP proxy
2020-09-10 14:38:39:447 [WD Proxy] Matched '/wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/source' to command name 'getPageSource'
2020-09-10 14:38:39:448 [WD Proxy] Proxying [GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/source] to [GET http://localhost:8200/wd/hub/session/cde0ded7-58c7-4e38-95c6-f201700b10ec/source] with body: {}
2020-09-10 14:38:40:123 [WD Proxy] Got response with status 200: {"sessionId":"cde0ded7-58c7-4e38-95c6-f201700b10ec","value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy index=\"0\" class=\"hierarchy\" rotation=\"0\" width=\"1080\" height=\"2028\">\r\n  <android.widget.FrameLayout index=\"0\" package=\"com.amazon.dee.app\" class=\"android.widget.FrameLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2028]\" displayed=\"true\">\r\n    <android.widget.LinearLayout index=\"0\" package=\"com.amazon.dee.app\" class=\"android.widget.LinearLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2028]\" displayed=\"true\">\r\n      <android.widget.FrameLayout index=\"0\" package=\"com.amazon....
2020-09-10 14:38:40:123 [WD Proxy] Replacing sessionId cde0ded7-58c7-4e38-95c6-f201700b10ec with f0912a9e-2b74-4c12-ba06-78fd9cd4a24c
2020-09-10 14:38:40:126 [HTTP] <-- GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/source 200 685 ms - 19530
2020-09-10 14:38:40:127 [HTTP] 
2020-09-10 14:38:40:137 [HTTP] --> GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/screenshot
2020-09-10 14:38:40:138 [HTTP] {}
2020-09-10 14:38:40:138 [MJSONWP (f0912a9e)] Calling AppiumDriver.getScreenshot() with args: ["f0912a9e-2b74-4c12-ba06-78fd9cd4a24c"]
2020-09-10 14:38:40:140 [WD Proxy] Matched '/screenshot' to command name 'getScreenshot'
2020-09-10 14:38:40:142 [WD Proxy] Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/cde0ded7-58c7-4e38-95c6-f201700b10ec/screenshot] with no body
2020-09-10 14:38:40:279 [WD Proxy] Got response with status 500: {"sessionId":"cde0ded7-58c7-4e38-95c6-f201700b10ec","value":{"error":"unable to capture screen","message":"Failed to capture a screenshot. Does the current view have 'secure' flag set?","stacktrace":"io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:124)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:59)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:77)\n\tat io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(CaptureScreenshot.java:34)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uia...
2020-09-10 14:38:40:281 [W3C] Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
2020-09-10 14:38:40:318 [MJSONWP (f0912a9e)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?
2020-09-10 14:38:40:318 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:124)
2020-09-10 14:38:40:319 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:59)
2020-09-10 14:38:40:319 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:77)
2020-09-10 14:38:40:320 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(CaptureScreenshot.java:34)
2020-09-10 14:38:40:321 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
2020-09-10 14:38:40:321 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
2020-09-10 14:38:40:322 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)
2020-09-10 14:38:40:322 [MJSONWP (f0912a9e)] 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
2020-09-10 14:38:40:325 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-09-10 14:38:40:326 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-09-10 14:38:40:326 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-09-10 14:38:40:327 [MJSONWP (f0912a9e)] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
2020-09-10 14:38:40:329 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-09-10 14:38:40:330 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-09-10 14:38:40:330 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-09-10 14:38:40:331 [MJSONWP (f0912a9e)] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
2020-09-10 14:38:40:331 [MJSONWP (f0912a9e)] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
2020-09-10 14:38:40:332 [MJSONWP (f0912a9e)] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
2020-09-10 14:38:40:332 [MJSONWP (f0912a9e)] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
2020-09-10 14:38:40:333 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-09-10 14:38:40:333 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-09-10 14:38:40:335 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
2020-09-10 14:38:40:335 [MJSONWP (f0912a9e)] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
2020-09-10 14:38:40:336 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
2020-09-10 14:38:40:336 [MJSONWP (f0912a9e)] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
2020-09-10 14:38:40:337 [MJSONWP (f0912a9e)] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
2020-09-10 14:38:40:337 [MJSONWP (f0912a9e)] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
2020-09-10 14:38:40:338 [MJSONWP (f0912a9e)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
2020-09-10 14:38:40:338 [MJSONWP (f0912a9e)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
2020-09-10 14:38:40:339 [MJSONWP (f0912a9e)] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
2020-09-10 14:38:40:339 [MJSONWP (f0912a9e)] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
2020-09-10 14:38:40:340 [MJSONWP (f0912a9e)] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
2020-09-10 14:38:40:341 [MJSONWP (f0912a9e)] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
2020-09-10 14:38:40:341 [MJSONWP (f0912a9e)] 	at java.lang.Thread.run(Thread.java:923)
2020-09-10 14:38:40:342 [MJSONWP (f0912a9e)] 
2020-09-10 14:38:40:345 [HTTP] <-- GET /wd/hub/session/f0912a9e-2b74-4c12-ba06-78fd9cd4a24c/screenshot 500 206 ms - 164`

**Comment by KazuCocoa** [comment]
> Failed to capture a screenshot. Does the current view have 'secure' flag set?

The error message addressed the app under test had a security flag which did not allow to get a screenshot by Android framework.
Hm, AD should show an error message then.

**Comment by MMannanikat** [comment]
@KazuCocoa Thank you for working on it. One other different I see that the view which throws error on screenshot is a webview and other working views are native views. So not sure it's really due to the 'secure' flag.

**Comment by KazuCocoa** [comment]
hm, okay, thanks.
Will take a look at webview in the 1560.

**Comment by julian506** [comment]
> > Hi,
> > We have this same problem.
> > Using-
> > Appium server --> appium@1.15.0-beta.1
> > Appium desktop for Mac --> .dmg (v1.14)→ https://github.com/appium/appium-desktop/releases
> > iOS 13
> > Xcode 11
> > Mac Mojave- 10.1.4.6
> > Has anyone found a workaround yet?
> 
> Found the workaround. Here it is, for anyone else struggling with infinite loading of inspector!
> 
> 1. Start Appium server from the command line (1.15.0-beta.1)
> 2. Start the Appium Desktop app. Do NOT click "Start Server"
> 3. Launch the new session window (go up to "Appium desktop" (mac) or "File" (windows) and click new session from the menu)
> 4. Open the "Custom Server" tab of the new session window
> 5. Enter your local Appium server host and port (localhost / 4723)
> 6. Enter your capabilities
> 7. Start the session as normal. This will start a session using the Appium instance you have running on the command line, which is 1.15.0-beta.1
> 
> Original error:
> On using Appium desktop 1.14 with server version 1.15.0-beta.1- accessibility inspector does not work. Loads infinitely.
> 
> Error - [HTTP] <-- GET /wd/hub/session/517796b5-170a-4258-ad88-228f502bf9b6/window/current/size 500 284 ms - 8215
> 
> &
> Error-
> [MJSONWP] Matched JSONWP error code 13 to UnknownError
> [MJSONWP (0713876f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[FBApplication resolve]: unrecognized selector sent to instance 0x282d10230

Worked for me, Thanks!

**Comment by vzenzo** [comment]
This is still happening and the workaround doesnt work
