### ISSUE TITLE
Appium Desktop 1.14.0 and above give signing errors

### ISSUE THREAD

**Issue by WoLpH** [appium/appium-desktop#1115]
When updating to Appium Desktop 1.14.x or 1.15.x (got the 1.15.0 update notification today which triggered me to update) my Appium completely stops working.

Downgrading to 1.13.0 immediately fixes it. Removing the appium settings and everything from the phone makes not difference. i.e.:
```
adb uninstall io.appium.settings
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test
```

## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

The issue is with the packages contained in Appium Desktop, it's not the Appium source itself that's the issue here.

## The problem

When starting the Appium Inspector I get the following error:
```Error
An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe' -jar 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\jars\\sign.jar' 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' --override' exited with code 1
```

Full (redacted) log: https://gist.github.com/WoLpH/821a6dcbe93521b3d42f833f52eaa326

## Environment

- I am running Appium Desktop version 1.14.0, 1.15.0, 1.15.0-1
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
mm, thanks.
Could you give us the output of 

```
[2019-10-05 02:08:08][ADB] Starting 'C:\Users\user\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
```

by manual execution?

The command will be like `C:\Users\user\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat sign --key C:\\Program Files\\Appium\\resources\\app\\node_modules\\...`

We assumed the cause was permission. Appium 1.15.0 has the ability to copy apks to writable space if it was not writable. https://github.com/appium/appium-uiautomator2-driver/pull/338 (Included in appium 1.15.0)  But the case is not this case.


```
[2019-10-05 02:08:08][ADB] Starting 'C:\Users\user\AppData\Local\Android\Sdk\build-tools\28.0.3\apksigner.bat' with args '["sign","--key","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[2019-10-05 02:08:09][ADB] Got an error during apksigner execution: Command 'apksigner.bat sign --key 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'' exited with code 1
[2019-10-05 02:08:09][ADB] apksigner stderr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:384)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
[2019-10-05 02:08:09][ADB] 	at java.base/java.nio.file.Files.move(Files.java:1424)
[2019-10-05 02:08:09][ADB] 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[2019-10-05 02:08:09][ADB] 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[2019-10-05 02:08:09][ADB] 
[2019-10-05 02:08:09][ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'apksigner.bat sign --key 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.pk8' --cert 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-adb\\keys\\testkey.x509.pem' 'C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk'' exited with code 1; StdErr: Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:384)
[2019-10-05 02:08:09][ADB] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
[2019-10-05 02:08:09][ADB] 	at java.base/java.nio.file.Files.move(Files.java:1424)
[2019-10-05 02:08:09][ADB] 	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[2019-10-05 02:08:09][ADB] 	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[2019-10-05 02:08:09][ADB] 
```

**Comment by WoLpH** [comment]
I think your hunch about permissions is correct. After I noticed the permission error in the logs I tried to start Appium Desktop in Administrator mode after, and that seems to have fixed it. I can now run it as a normal user as well.

I’m currently running a reasonably long test script which I would prefer not to interrupt so I’ll have to wait a few hours before I can reinstall Appium to test again.

Thank you for the quick response by the way!

**Comment by WoLpH** [comment]
And here we go, the output:

```
> apksigner.bat sign --key "C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\node_modules\appium-adb\keys\testkey.pk8" --cert "C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\node_modules\appium-adb\keys\testkey.x509.pem" "C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk"
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:384)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
        at java.base/java.nio.file.Files.move(Files.java:1424)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
```

**Comment by KazuCocoa** [comment]
thanks.
I observed the same error on my Windows 10 PC. (Even if I installed AD as the only current user.)
As a temporary solution is run appium desktop as admin permission...

Let me consider...
