### ISSUE TITLE
Facing problem with inspecting elements on real device.

### ISSUE THREAD

**Issue by RT715** [appium/appium-desktop#1132]
The problem

Hi everyone. I am currently facing that mistical problem. I am trying to inspect elements on real iOS device using appium desktop. I ve set up  required desired capabilities such as platformName, platformVersion, deviceName, udid and app path. When i start session on custom server, i get this error:
```An unknown server-side error occurred while processing the command. Original error: Could not install app: 'The "path" argument must be of type string. Received type undefined'``` 

Environment

Last Appium: 1.15.1
Desktop OS: Mac OS majavo 10.14.6

* Npm or Yarn package manager:
* Mobile platform/version under test: iOS 13.1
* Real device: iPhone 7 

Appium logs

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/user/Desktop/city-messenger.ipa","deviceName":"RT","platformName":"iOS","platformVersion":"13.1","udid":"53118c7b5847cc87c524c3da0b416cf5e83cb69b","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1571209719210 (10:08:39 GMT+0300 (MSK))
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
[Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Appium v1.15.0 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/user/Desktop/city-messenger.ipa",
[BaseDriver]   "deviceName": "RT",
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "13.1",
[BaseDriver]   "udid": "53118c7b5847cc87c524c3da0b416cf5e83cb69b",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: 957b30ea-d4f1-4ae0-a623-e81fba95e665
[XCUITest] Current user: 'user'
[XCUITest] Available devices: 53118c7b5847cc87c524c3da0b416cf5e83cb69b
[XCUITest] Creating iDevice object with udid '53118c7b5847cc87c524c3da0b416cf5e83cb69b'
[XCUITest] Determining device to run tests on: udid: '53118c7b5847cc87c524c3da0b416cf5e83cb69b', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1571209719257 (10:08:39 GMT+0300 (MSK))
[BaseDriver] Using local app '/Users/user/Desktop/city-messenger.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/5x/6mk68dxs1tjghrkstlhh0ky00000gn/T/2019916-3438-rp6sdt.fs54/Payload/city-messenger.app'
[BaseDriver] Event 'appConfigured' logged at 1571209719722 (10:08:39 GMT+0300 (MSK))
[XCUITest] Checking whether app '/var/folders/5x/6mk68dxs1tjghrkstlhh0ky00000gn/T/2019916-3438-rp6sdt.fs54/Payload/city-messenger.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/var/folders/5x/6mk68dxs1tjghrkstlhh0ky00000gn/T/2019916-3438-rp6sdt.fs54/Payload/city-messenger.app': 'appcraft.city-messenger'
[BaseDriver] Event 'resetStarted' logged at 1571209719724 (10:08:39 GMT+0300 (MSK))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1571209719725 (10:08:39 GMT+0300 (MSK))
[XCUITest] Crash reports root '/Users/user/Library/Logs/CrashReporter/MobileDevice/RT' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1571209719975 (10:08:39 GMT+0300 (MSK))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Installing '/var/folders/5x/6mk68dxs1tjghrkstlhh0ky00000gn/T/2019916-3438-rp6sdt.fs54/Payload/city-messenger.app' on device with UUID '53118c7b5847cc87c524c3da0b416cf5e83cb69b'...
[XCUITest] Error was thrown during the installation process
[XCUITest] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
[XCUITest]     at assertPath (path.js:39:11)
[XCUITest]     at Object.join (path.js:1157:7)
[XCUITest]     at Object.join [as walkDir] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/fs.js:76:29)
[XCUITest] Error: Could not install app: 'The "path" argument must be of type string. Received type undefined'
[XCUITest]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[DevCon Factory] Releasing connections for 53118c7b5847cc87c524c3da0b416cf5e83cb69b device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1571209720505 (10:08:40 GMT+0300 (MSK))
[MJSONWP] Encountered internal error running command: Error: Could not install app: 'The "path" argument must be of type string. Received type undefined'
[MJSONWP]     at IOSDeploy.install (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/ios-deploy.js:41:13)
[HTTP] <-- POST /wd/hub/session 500 1298 ms - 231
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 2 ms - 57

**Comment by ynesterssl** [comment]
@RT715 
Seems like you are not using Appium v1.15.1.
The log you attached says: _[Appium] Appium v1.15.0 creating new XCUITestDriver (v2.133.1) session_

**Comment by KazuCocoa** [comment]
Yes, please try out 1.15.1 https://github.com/appium/appium-desktop/releases/tag/v1.15.1

**Comment by RT715** [comment]
omg...i upgraded my appium. I start new inspecting session and here is what i got:
![Снимок экрана 2019-10-17 в 9 23 00](https://user-images.githubusercontent.com/56626073/66982906-f026b880-f0bf-11e9-9477-d750b67019fc.png)

`An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2019-10-17 09:26:57.586 xcodebuild[41740:582189] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Build/Products/WebDriverAgentRunner_iphoneos13.1-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fa71ddf55f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2019-10-17 09:26:57.617 xcodebuild[41740:582237] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.17_09-26-57-+0300.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-6059E2B9-B689-4EBA-B5C7-826B5063C99D/WebDriverAgentRunner-E695F20A-60B6-4B7D-BDC7-C55BC12FB0DA/Session-WebDriverAgentRunner-2019-10-17_092657-EVhUrc.log 2019-10-17 09:26:57.619 xcodebuild[41740:582186] [MT] IDETestOperationsObserverDebug: (3A14A818-6F32-4D43-ACBB-4237AEBA52B8) Beginning test session WebDriverAgentRunner-3A14A818-6F32-4D43-ACBB-4237AEBA52B8 at 2019-10-17 09:26:57.618 with Xcode 11A1027 on target 📱<DVTiOSDevice (0x7fa71e37c1b0), RT, iPhone, 13.1 (17A844), 53118c7b5847cc87c524c3da0b416cf5e83cb69b> { deviceSerialNumber: F71TPQT9HG6W identifier: 53118c7b5847cc87c524c3da0b416cf5e83cb69b deviceClass: iPhone deviceName: RT deviceIdentifier: 53118c7b5847cc87c524c3da0b416cf5e83cb69b productVersion: 13.1 buildVersion: 17A844 deviceSoftwareVersion: 13.1 (17A844) deviceArchitecture: arm64 deviceTotalCapacity: 25055916032 deviceAvailableCapacity: 15628750848 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7fa71dd6f6d0 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: (null) bonjourServiceName: dc:a9:04:c9:9b:66@fe80::dea9:4ff:fec9:9b66._apple-mobdev2._tcp.local. activeProxiedDevice: (null) } (13.1 (17A844)) 2019-10-17 09:26:57.834 xcodebuild[41740:582186] [MT] IDETestOperationsObserverDebug: (3A14A818-6F32-4D43-ACBB-4237AEBA52B8) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-akxhdiizyykdxefsthlnfyomlaiz/Logs/Test/Test-WebDriverAgentRunner-2019.10.17_09-26-57-+0300.xcresult 2019-10-17 09:26:57.871 xcodebuild[41740:582186] [MT] IDETestOperationsObserverDebug: 0.266 elapsed -- Testing started completed. 2019-10-17 09:26:57.871 xcodebuild[41740:582186] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2019-10-17 09:26:57.871 `

Following logs that say ```Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.``` it didnt help.

**Comment by RT715** [comment]
Also logs say that `WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying error: The operation couldn’t be completed. No such file or directory)))`
No clue how could it be

**Comment by RT715** [comment]
here is my desired capabilities for in case
   "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "13.1",
  "fullReset": false,
  "udid": "53118c7b5847cc87c524c3da0b416cf5e83cb69b",
  "bundleid": "appcraft.city-messenger",
  "deviceName": "RT",
  "app": "/Users/user/Desktop/city-messenger.ipa"

**Comment by RT715** [comment]
ok i fixed previous one error now m gettin another one

`An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: 'bundleId' desired capability not provided Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.`

**Comment by KazuCocoa** [comment]
Sorry, I confused your point now. 

You installed the signed WDA manually and tried to establish a new session via appium desktop 1.15.1, right?
https://github.com/appium/appium/issues/13353 the last your question is this issue, I assume.
You should use proper WDA version. Your case is probably old WDA and Appium 1.15.0 server.
