### ISSUE TITLE
Appium getPageSource return a  internal error 500

### ISSUE THREAD

**Issue by tinagongtester** [appium/appium-desktop#1156]
[W3C (bc51a573)] Calling AppiumDriver.getCurrentPackage() with args: ["bc51a573-cfeb-4a02-bad3-b9cc9e104e47"]
[ADB] Getting focused package and activity
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 4b99d530 shell dumpsys window windows'
[W3C (bc51a573)] Responding to client with driver.getCurrentPackage() result: "com.tencent.qqmusic"
[HTTP] <-- GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/appium/device/current_package 200 102 ms - 31
[HTTP] 
[HTTP] --> GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source
[HTTP] {}
[W3C (bc51a573)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source] to [GET http://localhost:8202/wd/hub/session/37dac3c5-b93c-45a7-9957-9e2ebc93d3cd/source] with body: {}
[BaseDriver] Shutting down because we waited 60 seconds for a command
[UiAutomator2] Deleting UiAutomator2 session
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 59f2fb7f-cd8e-4de8-b7c7-f835d9a60a3e from our master session list
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8201/wd/hub/session/a0979563-63d3-4a89-ba82-361b414764f2] with no body
[WD Proxy] Got response with status 200: {"sessionId":"a0979563-63d3-4a89-ba82-361b414764f2","value":null}
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 4b99d530 shell am force-stop com.tencent.qqmusic'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201 
[ADB] Running 'D:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 4b99d530 forward --remove tcp\:8201'
[Instrumentation] .
[Instrumentation] Time: 52.07
[Instrumentation] 
[Instrumentation] OK (1 test)
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[W3C (bc51a573)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
[W3C (bc51a573)]     at doJwpProxy (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:490:13)
[HTTP] <-- GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source 500 11832 ms - 783
[HTTP] 
[Instrumentation] The process has exited with code 0

**Comment by tinagongtester** [comment]
i install appium desktop  version 1.15.1

**Comment by KazuCocoa** [comment]
What about increasing `newCommandTimeout` as the message?

```
[HTTP] --> GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source
[HTTP] {}
[W3C (bc51a573)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source' to command name 'getPageSource'
[WD Proxy] Proxying [GET /wd/hub/session/bc51a573-cfeb-4a02-bad3-b9cc9e104e47/source] to [GET http://localhost:8202/wd/hub/session/37dac3c5-b93c-45a7-9957-9e2ebc93d3cd/source] with body: {}
[BaseDriver] Shutting down because we waited 60 seconds for a command
[UiAutomator2] Deleting UiAutomator2 session
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 59f2fb7f-cd8e-4de8-b7c7-f835d9a60a3e from our master session list
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8201/wd/hub/session/a0979563-63d3-4a89-ba82-361b414764f2] with no body
```

It looks like the source called after deleting the session.
If the error continues to happen, please attach the logcat

**Comment by tinagongtester** [comment]
hi，this error is cotinues to happen，logcat has attach
capablity as follows：
	    
              ` DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(CapabilityType.BROWSER_NAME, "");
		cap.setCapability("platformName", "Android");
		cap.setCapability("deviceName", "4b99d530");
															
		cap.setCapability("newCommandTimeout", "7200");
		cap.setCapability("platformVersion", "8.0"); 
		cap.setCapability("noReset", true);


		cap.setCapability("appPackage", "com.tencent.qqmusic");
		cap.setCapability("appActivity", ".activity.AppStarterActivity");

		cap.setCapability("sessionOverride", true);
		cap.setCapability("clearSystemFiles", true);

		cap.setCapability("autoAcceptAlerts", true); // 默认选择接受弹窗的条款，有些app启动的时候，会有一些权限的弹窗
		cap.setCapability("nativeWebScreenshot", true);
		cap.setCapability("androidScreenshotPath", "target/screenshots");`
[logcat.log](https://github.com/appium/appium-desktop/files/3781374/logcat.log)
[logcat.log](https://github.com/appium/appium-desktop/files/3781376/logcat.log)
[logcat.log](https://github.com/appium/appium-desktop/files/3781379/logcat.log)

**Comment by KazuCocoa** [comment]
Some source succedded,

```
10-29 09:49:33.267 I/appium  ( 6707): channel read: GET /wd/hub/session/6371d355-cabf-45cd-a8c8-80a4f35712c5/source
10-29 09:49:33.279 I/appium  ( 6707): Waiting up to 10000ms for device to be idle
10-29 09:49:33.842 D/QtiCarrierConfigHelper( 3789): WARNING, no carrier configs on phone Id: 0
10-29 09:49:33.843 D/HeadsetStateMachine( 3493): Disconnected process message: 10, size: 0
10-29 09:49:33.843 D/HeadsetStateMachine( 3493): Enter processIntentBatteryChanged()
10-29 09:49:33.843 D/HeadsetStateMachine( 3493): Exit processIntentBatteryChanged()
10-29 09:49:33.843 D/HeadsetStateMachine( 3493): Exit Disconnected processMessage() 
10-29 09:49:34.415 I/chatty  ( 6784): uid=11971(com.tencent.qqmusic) expire 3 lines
10-29 09:49:34.443 I/zygote64( 6707): Do full code cache collection, code=125KB, data=71KB
10-29 09:49:34.444 I/zygote64( 6707): After code cache collection, code=98KB, data=52KB
10-29 09:49:34.682 I/appium  ( 6707): AppiumResponse: {"sessionId":"6371d355-cabf-45cd-a8c8-80a4f35712c5","value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy index=\"0\" class=\"hierarchy\" rotation=\"0\" width=\"1080\" height=\"1920\">\r\n  <android.widget.FrameLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.FrameLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n    <android.widget.LinearLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.LinearLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n      <android.widget.FrameLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"android:id\/content\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n        <android.widget.FrameLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/mainactivityviewlayout\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n          <android.view.ViewGroup index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/main_music_fragment_detail\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n            <android.widget.RelativeLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.RelativeLayout\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/main_fragment\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\">\r\n              <android.widget.ImageView index=\"3\" package=\"com.tencent.qqmusic\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/main_view_bg\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1920]\" displayed=\"true\" \/>\r\n              <android.support.v4.view.ViewPager index=\"4\" package=\"com.tencent.qqmusic\" class=\"android.support.v4.view.ViewPager\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/main_desk_fragment_pager\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"true\" selected=\"false\" bounds=\"[0,0][1080,1755]\" displayed=\"true\">\r\n                <android.widget.FrameLayout index=\"0\" package=\"com.tencent.qqmusic\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.tencent.qqmusic:id\/loading_layout\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,1755]\" displayed=\"true\">\r\n                  <android.widget.Fram
10-29 09:49:34.871 I/appium  ( 6707): channel read invoked!
10-29 09:49:34.872 I/appium  ( 6707): channel read: POST /wd/hub/session/6371d355-cabf-45cd-a8c8-80a4f35712c5/element
10-29 09:49:34.875 I/appium  ( 6707): Find element command using 'id' with selector 'com.tencent.qqmusic:id/content_image'.
```

but I found the below message.

```
10-29 09:53:22.724 E/AccessibilityManagerService( 2777): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-29 09:53:22.724 E/AccessibilityManagerService( 2777): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-29 09:53:22.738 D/AndroidRuntime( 8609): Calling main entry com.android.commands.am.Am
10-29 09:53:22.743 I/ActivityManager( 2777): Force stopping io.appium.uiautomator2.server appid=11969 user=0: start instr
10-29 09:53:22.743 I/ActivityManager( 2777): Killing 6707:io.appium.uiautomator2.server/u0a1969 (adj 0): stop io.appium.uiautomator2.server
10-29 09:53:22.785 D/ActivityManager( 2777): Process io.appium.uiautomator2.server has 0 services
10-29 09:53:22.785 W/ActivityManager( 2777): Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
10-29 09:53:22.786 I/ActivityManager( 2777): Force stopping io.appium.uiautomator2.server appid=11969 user=0: finished inst
10-29 09:53:22.786 W/Binder  ( 2777): Outgoing transactions from this process must be FLAG_ONEWAY
10-29 09:53:22.786 W/Binder  ( 2777): java.lang.Throwable
10-29 09:53:22.786 W/Binder  ( 2777): 	at android.os.BinderProxy.transact(Binder.java:753)
10-29 09:53:22.786 W/Binder  ( 2777): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:160)
10-29 09:53:22.786 W/Binder  ( 2777): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
10-29 09:53:22.789 D/AndroidRuntime( 6692): Shutting down VM
10-29 09:53:22.790 W/Binder  ( 6692): Binder call failed.
10-29 09:53:22.790 W/Binder  ( 6692): java.lang.SecurityException: Calling from not trusted UID!
10-29 09:53:22.790 W/Binder  ( 6692): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:413)
10-29 09:53:22.790 W/Binder  ( 6692): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:317)
10-29 09:53:22.790 W/Binder  ( 6692): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:209)
10-29 09:53:22.790 W/Binder  ( 6692): 	at android.os.Binder.execTransact(Binder.java:692)
10-29 09:53:22.806 I/ActivityManager( 2777): Start proc 8620:io.appium.uiautomator2.server/u0a1969 for added application io.appium.uiautomator2.server
10-29 09:53:22.809 I/zygote64( 8620): Late-enabling -Xcheck:jni
10-29 09:53:22.827 E/JavaBinder( 2777): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 768)
10-29 09:53:22.828 E/AccessibilityManagerService( 2777): Error during sending EventType: TYPE_WINDOW_CONTENT_CHANGED; EventTime: 10413101; PackageName: com.tencent.qqmusic; MovementGranularity: 0; Action: 0 [ ClassName: android.widget.ImageView; Text: []; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; IsEnabled: true; IsPassword: false; IsChecked: false; IsFullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0 to android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@b39527b
10-29 09:53:22.828 E/AccessibilityManagerService( 2777): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
10-29 09:53:22.828 E/AccessibilityManagerService( 2777): 
```


Did this happen only on particular views?
