### ISSUE TITLE
No Chromedriver found that can automate Chrome '69.0.3497'

### ISSUE THREAD

**Issue by krthknan** [appium/appium-desktop#1196]
Even I'm trying to automate an app, but it is throwing chroemdriver error. Please refer the below error and help me

D:\mobile\test\config>protractor androidMobile.config.js
[19:08:00] I/launcher - Running 1 instances of WebDriver
[19:08:00] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[19:08:12] E/launcher - An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '69.0.3497'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.
md for more details. You could also try to enable automated chromedrivers download server feature
[19:08:12] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '69.0.3497'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/w
eb/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature
    at Object.checkLegacyResponse (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\Users\kannadurai\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[19:08:12] E/launcher - Process exited with error code 199

**Comment by KazuCocoa** [comment]
Which version of the desktop app did you use?

You can download the proper Chromedriver version and set it as `chromedriverExecutable` to run with it.

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md
https://appium.io/docs/en/writing-running-appium/caps/

**Comment by AvishekDhar** [comment]
You can let Appium to automatically download the chromedriver version:

"appium --allow-insecure chromedriver_autodownload" run this in the CMD where you were running appium server. Once if we run above command then appium get the compatible browser version matching the emulator/device and now from next time just start appium server normally and run the code.

The above command tested in Appium v1.21.0

https://www.youtube.com/watch?v=bOFXhjfdg08

**Comment by sakibguy** [comment]
i faced the same issue after node/desktop appium installed

working **appium --allow-insecure chromedriver_autodownload**

thanks a lot  @AvishekDhar
