### ISSUE TITLE
Appium :: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session

### ISSUE THREAD

**Issue by kiranhungama1** [appium/appium-desktop#1202]
1. Updated to MacOS catalina
2. Updated appium desktop 1.15.1
3. Xcode 11.2.1
4. java client - 7.3.0
5. Testng 7.0.0

Below is the exception on the appium server

[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session [Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided [BaseDriver] Creating session with W3C capabilities: { [BaseDriver] "alwaysMatch": { [BaseDriver] "platformName": "ios", [BaseDriver] "appium:automationName": "XCUITest", [BaseDriver] "appium:bundleId": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZ", [BaseDriver] "appium:deviceName": "iPhone7_Hml", [BaseDriver] "appium:newCommandTimeout": 160, [BaseDriver] "appium:noReset": true, [BaseDriver] "appium:platformVersion": "13.2", [BaseDriver] "appium:udid": "89c4364185f2f1dba22992faaae1179e32a4eb41", [BaseDriver] "appium:xcodeOrgId": "XXXXXXXXXXXXXXXXXXXX", [BaseDriver] "appium:xcodeSigningId": "iPhone Developer" [BaseDriver] }, [BaseDriver] "firstMatch": [ [BaseDriver] {} [BaseDriver] ] [BaseDriver] } [BaseDriver] Session created with session id: ee9f8be2-da63-44d3-9f8a-0d433ea9f2f8 [XCUITest] Current user: 'Yayati' [XCUITest] Available devices: 89c4364185f2f1dba22992faaae1179e32a4eb41, ccfe00fee87aa9140b71a98eedc18c88a214121d, 3bdf2f4113dfccd88c17e26b56dc2e03b53f2812, 9f993665a8a2abf6b22fec56e576487a4b40a818 [XCUITest] Creating iDevice object with udid '89c4364185f2f1dba22992faaae1179e32a4eb41' [XCUITest] Determining device to run tests on: udid: '89c4364185f2f1dba22992faaae1179e32a4eb41', real device: true [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [BaseDriver] Event 'appConfigured' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [BaseDriver] Event 'resetStarted' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [XCUITest] Reset: fullReset not set. Leaving as is [BaseDriver] Event 'resetComplete' logged at 1575638568501 (18:52:48 GMT+0530 (IST)) [XCUITest] Continuing without capturing device logs: Connection was refused to port 53356 [XCUITest] Setting up real device [XCUITest] Error: Connection was refused to port 53359 [XCUITest] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13) [DevCon Factory] Releasing connections for 89c4364185f2f1dba22992faaae1179e32a4eb41 device on any port number [DevCon Factory] No cached connections have been found [BaseDriver] Event 'newSessionStarted' logged at 1575638608946 (18:53:28 GMT+0530 (IST)) [W3C] Encountered internal error running command: Error: Connection was refused to port 53359 [W3C] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13) [HTTP] <-- POST /wd/hub/session 500 40502 ms - 702

NOTE : Before the update it was working properly.

Below are the logs that I Get on eclipse console ::

FAILED CONFIGURATION: @BeforeTest beforeTest
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:92)
	at utils.Capability.capability_phone(Capability.java:53)
	at testcases.search.beforeTest(search.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 39 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'M16IMACHDMGG7J.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.1', java.version: '12.0.1'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Connection was refused to port 53359
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 44 more
Capability which I am using are as follows :

 public static IOSDriver capability_phone() throws MalformedURLException {
 final String URL_STRING = "http://0.0.0.0:4723/wd/hub";
 url = new URL(URL_STRING);
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("deviceName","iPhone7_Hml");
cap.setCapability("udid","89c4364185f2f1dba22992faaae1179e32a4eb41");
cap.setCapability("platformVersion","13.2");
cap.setCapability("platformName","IOS");
cap.setCapability("automationName", "XCUITest");
cap.setCapability("bundleId","com.hungama.myplay");
cap.setCapability("noReset",true);
cap.setCapability("xcodeSigningId", "iPhone Developer");
 cap.setCapability("xcodeOrgId", "XXXXXXXXXXXXXXXXXXXX");
 cap.setCapability("newCommandTimeout", 160);
 we = new IOSDriver(url, cap);
 we.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
System.out.println(" ~~~ !!! Setting the capabilities !!! ~~~ ");
 return we;
    	}
[XCUITest] Continuing without capturing device logs: Connection was refused to port 57483
[XCUITest] Setting up real device
[XCUITest] Error: Connection was refused to port 57486
[XCUITest] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[DevCon Factory] Releasing connections for f29645da08dedad0760f2efa2e451949ea4124d2 device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1576053574827 (14:09:34 GMT+0530 (IST))
[W3C] Encountered internal error running command: Error: Connection was refused to port 57486
[W3C] at Usbmux.connect (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-ios-device/lib/usbmux/index.js:183:13)
[HTTP] <-- POST /wd/hub/session 500 80492 ms - 702

**Comment by KazuCocoa** [comment]
>  Releasing connections for 89c4364185f2f1dba22992faaae1179e32a4eb41 device on any port number


Was your port 8000 available?
The number was the default port number which WDA (on the device) communicated with Appium server.
`wdaLocalPort` capability can configure it.

How about changing the default to another port number which is available on your environment?

**Comment by kiranhungama1** [comment]
I have tried that. I have set 8100 as the WDA port in capability.
I usually run the test suite...It has 150 plus testcases... After successful execution of some testcases(10 to 15), it throws this error...

**Comment by KazuCocoa** [comment]
It perhaps happens xcodebuild keep the connection even if appium tried to close the connection, for example.

As a workaround, you can change the port number every test running.
e.g. Use port number 8100 -> next is 8101 -> the next is 8100 again

**Comment by kiranhungama1** [comment]
Not working...still the same issue...

**Comment by kiranhungama1** [comment]
[AppiumLogsError.txt](https://github.com/appium/appium-desktop/files/4015468/AppiumLogsError.txt)

Latest logs from Run....It works fine & "Usbmux.connect" error comes up...after some excecutions...

I have another Mac running the same code but Mac OS(mojave & appium desktop version 1.13.0).
The code & testcases works perfect on the second mac.

**Comment by KazuCocoa** [comment]
What about 1.16.0? It is appium 1.16.0 base

**Comment by kiranhungama1** [comment]
Tried 1.16.0 still same issue...
I think some dependencies should be updated in AD 1.16.0 like appium-ios-device, appium-xcuitest-driver, WebDriverAgent etc.

**Comment by KazuCocoa** [comment]
> The code & testcases works perfect on the second mac.
