### ISSUE TITLE
 Cannot use apksigner tool for signature verification. Original error: Command 'apksigner.bat verify --print-certs  C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not signed with debug cert: Exception in thread "main" java.util.zip.ZipException: zip file is empty

### ISSUE THREAD

**Issue by gpankajgupta929** [appium/appium-desktop#1210]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by gpankajgupta929** [comment]
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4025624/appium-server-logs.txt)

**Comment by gpankajgupta929** [comment]
[info] [35m[Appium][39m Welcome to Appium v1.13.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m4 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"adbExecTimeout":"25000","app":"C:/Users/Administrator/Downloads/GoodwillLiveBuild.apk","autoGrantPermissions":"true","automationName":"UiAutomator2","deviceName":"redmi","fullReset":"false","noReset":"false","noSign":"true","platformName":"Android","platformVersion":"7.1.2","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"adbExecTimeout":"25000","app":"C:/Users/Administrator/Downloads/GoodwillLiveBuild.apk","autoGrantPermissions":"true","automationName":"UiAutomator2","deviceName":"redmi","fullReset":"false","noReset":"false","noSign":"true","platformName":"Android","platformVersion":"7.1.2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1578305177391 (15:36:17 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Appium v1.13.0 creating new AndroidUiautomator2Driver (v1.33.1) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   adbExecTimeout: 25000
[info] [35m[Appium][39m   app: C:/Users/Administrator/Downloads/GoodwillLiveBuild.apk
[info] [35m[Appium][39m   autoGrantPermissions: true
[info] [35m[Appium][39m   automationName: UiAutomator2
[info] [35m[Appium][39m   deviceName: redmi
[info] [35m[Appium][39m   fullReset: false
[info] [35m[Appium][39m   noReset: false
[info] [35m[Appium][39m   noSign: true
[info] [35m[Appium][39m   platformName: Android
[info] [35m[Appium][39m   platformVersion: 7.1.2
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"adbExecTimeout":"25000","...
[warn] [35m[BaseDriver][39m Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m Capability 'noSign' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m Capability 'autoGrantPermissions' changed from string to boolean. This may cause unexpected behavior
[warn] [35m[BaseDriver][39m Capability 'adbExecTimeout' changed from string ('25000') to integer (25000). This may cause unexpected behavior
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[info] [35m[BaseDriver][39m Session created with session id: 61b4ae48-d4ed-4503-8ad0-f4808ab2f43f
[info] [35m[BaseDriver][39m Using local app 'C:/Users/Administrator/Downloads/GoodwillLiveBuild.apk'
[debug] [35m[UiAutomator2][39m Checking whether app is actually present[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe'
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Looking for a device with Android '7.1.2'
[debug] [35m[ADB][39m Setting device id to 803226a7d740
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 7.1.2
[info] [35m[AndroidDriver][39m Using device: 803226a7d740
[info] [35m[ADB][39m Using 'adb.exe' from 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe'
[debug] [35m[ADB][39m Setting device id to 803226a7d740
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 25
[debug] [35m[ADB][39m Device API level: 25
[debug] [35m[AndroidDriver][39m Parsing package and activity from app manifest
[info] [35m[ADB][39m Using 'apkanalyzer.bat' from 'C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\apkanalyzer.bat'
[debug] [35m[ADB][39m Starting 'C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\apkanalyzer.bat' with args ["-h","manifest","print","C:/Users/Administrator/Downloads/GoodwillLiveBuild.apk"]
[info] [35m[ADB][39m Using the alternative activity name detection method because of: Command ''C:\\Program Files (x86)\\Android\\android-sdk\\build-tools\\28.0.3\\apkanalyzer.bat' -h manifest print C\:/Users/Administrator/Downloads/GoodwillLiveBuild.apk' exited with code 1
[info] [35m[ADB][39m Using 'aapt.exe' from 'C:\Program Files (x86)\Android\android-sdk\platform-tools\aapt.exe'
[info] [35m[ADB][39m Extracting package and launch activity from manifest
[info] [35m[ADB][39m Package name: 'com.rs.goodwill_new'
[info] [35m[ADB][39m Main activity name: 'com.rs.goodwill_new.splash.Splash'
[debug] [35m[AndroidDriver][39m Parsed package and activity are: com.rs.goodwill_new/com.rs.goodwill_new.splash.Splash
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 wait-for-device'
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell echo ping'[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m The version code of the installed 'io.appium.settings' is greater than the application version code (18 > 17)
[debug] [35m[ADB][39m There is no need to install/upgrade 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Getting IDs of all 'io.appium.settings' processes
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell 'pgrep --help; echo $?''[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell pgrep \^appium\\.settings\$'
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell appops set io.appium.settings android\:mock_location allow'
[debug] [35m[Logcat][39m Starting logcat capture[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell dumpsys package io.appium.uiautomator2.server'
[debug] [35m[ADB][39m 'io.appium.uiautomator2.server' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.uiautomator2.server'
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m The installed 'io.appium.uiautomator2.server' package is older than 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.5.1.apk' (2 < 31 or '1.12.0' < '3.5.1')'
[debug] [35m[UiAutomator2][39m io.appium.uiautomator2.server installation state: olderVersionInstalled
[debug] [35m[ADB][39m Checking app cert for C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.5.1.apk
[info] [35m[ADB][39m Using 'apksigner.bat' from 'C:\Program Files (x86)\Android\android-sdk\emulator\apksigner.bat'
[debug] [35m[ADB][39m Starting 'C:\Program Files (x86)\Android\android-sdk\emulator\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.5.1.apk"]'[warn] [35m[ADB][39m Got an error during apksigner execution: Command 'apksigner.bat verify --print-certs C\:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.5.1.apk' exited with code 1
[warn] [35m[ADB][39m apksigner stderr: Error: Unable to access jarfile C:\Program Files (x86)\Android\android-sdk\emulator\..\framework\apksigner.jar
[warn] [35m[ADB][39m 
[warn] [35m[ADB][39m Cannot use apksigner tool for signature verification. Original error: Command 'apksigner.bat verify --print-certs C\:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.5.1.apk' exited with code 1
[debug] [35m[ADB][39m Defaulting to verify.jar[debug] [35m[ADB][39m 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.5.1.apk' is already signed.
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server.test
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell dumpsys package io.appium.uiautomator2.server.test'[debug] [35m[ADB][39m 'io.appium.uiautomator2.server.test' is installed
[debug] [35m[ADB][39m Checking app cert for C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [35m[ADB][39m Starting 'C:\Program Files (x86)\Android\android-sdk\emulator\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'[warn] [35m[ADB][39m Got an error during apksigner execution: Command 'apksigner.bat verify --print-certs C\:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' exited with code 1
[warn] [35m[ADB][39m apksigner stderr: Error: Unable to access jarfile C:\Program Files (x86)\Android\android-sdk\emulator\..\framework\apksigner.jar
[warn] [35m[ADB][39m 
[warn] [35m[ADB][39m Cannot use apksigner tool for signature verification. Original error: Command 'apksigner.bat verify --print-certs C\:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' exited with code 1
[debug] [35m[ADB][39m Defaulting to verify.jar[debug] [35m[ADB][39m 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not signed with debug cert: Exception in thread "main" java.util.zip.ZipException: zip file is empty
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1284)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
[debug] [35m[ADB][39m 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
[debug] [35m[ADB][39m 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
[debug] [35m[ADB][39m 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
[debug] [35m[ADB][39m 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:270)
[debug] [35m[ADB][39m 	at v.Verify.verify(Verify.java:28)
[debug] [35m[ADB][39m 	at v.Verify.main(Verify.java:72)
[debug] [35m[ADB][39m 
[info] [35m[ADB][39m Using 'zipalign.exe' from 'C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\zipalign.exe'
[debug] [35m[ADB][39m 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is not zip-aligned. Aligning
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[WD Proxy][39m Matched '/' to command name 'deleteSession'
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 shell am force-stop com.rs.goodwill_new'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s 803226a7d740 forward --remove tcp\:8200'
[warn] [35m[UiAutomator2][39m Unable to remove port forward 'Error executing adbExec. Original error: 'Command ''C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s 803226a7d740 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb.exe: error: listener 'tcp:8200' not found'; Code: '1''
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1578305194618 (15:36:34 GMT+0530 (India Standard Time))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: zipAlignApk failed. Original error: Command ''C:\\Program Files (x86)\\Android\\android-sdk\\build-tools\\28.0.3\\zipalign.exe' -f 4 C\:\\Users\\Administrator\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk C\:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\202006-15884-1xmh3sd.fhxbj\\appium.tmp' exited with code 1. Stdout: ''; Stderr: 'Unable to open 'C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' as zip archive
[debug] [35m[MJSONWP][39m '
[debug] [35m[MJSONWP][39m     at ADB.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:251:11)
[debug] [35m[MJSONWP][39m     at Generator.next (<anonymous>)
[debug] [35m[MJSONWP][39m     at asyncGeneratorStep (C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[debug] [35m[MJSONWP][39m     at _next (C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
[debug] [35m[MJSONWP][39m     at run (C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:75:22)
[debug] [35m[MJSONWP][39m     at C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:92:30
[debug] [35m[MJSONWP][39m     at flush (C:\Users\Administrator\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\_microtask.js:18:9)
[debug] [35m[MJSONWP][39m     at process._tickCallback (internal/process/next_tick.js:61:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m17231 ms - 878[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m3 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by gpankajgupta929** [comment]
Tapped on wrong button mistakely...Hence! reopening

After a long struggle into this issue finally comeup with a Solution for this.
Just added a apksigner.jar to the Folder - android-sdk > build-tools > "your latest build-tools version folder" & also updated to Appium version 1.51.1.


And now after successfully implementation of UiAutomator2, again got stuck at kind of Error's called 1.Could not proxy command to remote server.
2.socket hang up.
3.Got an unexpected response with status undefined: {"code":"ECONNRESET"}.
