### ISSUE TITLE
Not able to use xcode version 11.3 in appium version 1.72

### ISSUE THREAD

**Issue by Sangitasubudhi** [appium/appium-desktop#1220]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium 1.72
xcode10.3 /11.3
MACos catalina 10.15
node version 13.5

i used this above versions while running the code, configuration error is coming from eclipse and it skips
in terminal if use the xcode 10.3 and xcode11.3 

**Error**
When using the xcode version 11.3.1

```
Xcode version '1.3.1'. Support for Xcode 1.3.1 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at getAndCheckXcodeVersion$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:61:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```
**Error**
When using the xcode version 10.3

```
Xcode version '0.3'. Support for Xcode 0.3 is not supported. Please upgrade to version 7.3 or higher
    at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:69:13)
    at getAndCheckXcodeVersion$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:61:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac

**Comment by mykola-mokhnach** [comment]
This is not possible without upgrading the server

**Comment by Sangitasubudhi** [comment]
which version i have to use to support xcode 10.3

**Comment by KazuCocoa** [comment]
Over 1.15 > which appium version..

**Comment by Sangitasubudhi** [comment]
I used 1.72 appium comand prompt and tried in desktop 1.15 still not working

**Comment by KazuCocoa** [comment]
Did you mean use Appium 1.7.2 via Appium Desktop 1.15?
Appium 1.15+ is necessary to run tests on Xcode 11. So, you should use Appium 1.15 via Appium Desktop. If you still have the same Xcode version error, please uninstall appium nodejs modules from your environment once. Then, please attach the full log, too.
