### ISSUE TITLE
Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by Nish0106** [appium/appium-desktop#1334]
## The problem

I am facing the below stated  issue while trying to launch & execute tests in Appium server v1.15

Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

Laptop OS   -  Windows 10
Test Device  -  OPPO F3
Android Version - V6
Appium version - 1.15
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4460308/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
The instrumentation process crashed.

```
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/window/current/size [39m[32m200[39m [90m629 ms - 100[39m
[info] [35m[HTTP][39m [90m[39m[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.

[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0[debug] [35m[Instrumentation][39m The process has exited with code 0[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (eb075eb0)][39m Calling AppiumDriver.deleteSession() with args: ["eb075eb0-2ba0-43ea-9798-4936a060fdc3"]
[debug] [35m[BaseDriver][39m Event 'quitSessionRequested' logged at 1586493747661 (10:12:27 GMT+0530 (India Standard Time))
[info] [35m[Appium][39m Removing session eb075eb0-2ba0-43ea-9798-4936a060fdc3 from our master session list
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
```

Could you share the logcat to dig the reason more?


----

btw, the log had below message. Potentially, the secure flag's error was related to.
```
[debug] [35m[MJSONWP (eb075eb0)][39m Encountered internal error running command: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:124)
```

**Comment by Nish0106** [comment]
Hi KazuCocoa,

Thanks for your reply

Please find the logcat file attached for more verification

**Comment by KazuCocoa** [comment]
If the cause is around below, I assume taking a screenshot on a secure flag brings UIAutomaton's illegalsateexception (out of Appium). It leads UIA2 server's error.

If so, maybe you can do is coordinating the secure flag on your target view or avoid calling taking screenshots

```
04-08 16:23:22.414 30762 30776 E AndroidRuntime: java.lang.IllegalStateException: UiAutomation not connected!
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:976)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at android.app.UiAutomation.disconnect(UiAutomation.java:237)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at android.app.Instrumentation.finish(Instrumentation.java:204)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:358)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:408)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:397)
04-08 16:23:22.414 30762 30776 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1893)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-13
04-08 16:28:07.886  3921  4053 E AndroidRuntime: java.lang.RuntimeException: Error running shell command
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at android.app.UiAutomationConnection$1.run(UiAutomationConnection.java:302)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: Caused by: java.io.IOException: write failed: EPIPE (Broken pipe)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at libcore.io.IoBridge.write(IoBridge.java:533)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at java.io.FileOutputStream.write(FileOutputStream.java:186)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at android.app.UiAutomationConnection$1.run(UiAutomationConnection.java:299)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at libcore.io.Posix.writeBytes(Native Method)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at libcore.io.Posix.write(Posix.java:271)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	at libcore.io.IoBridge.write(IoBridge.java:528)
04-08 16:28:07.886  3921  4053 E AndroidRuntime: 	... 2 more
04-08 16:28:07.890  3921  4053 E AndroidRuntime: Error reporting crash
```

**Comment by Nish0106** [comment]
Hi,

Thank you for the response

But we not capturing any screenshots as you said

We are copying only XML source from the uiautomator tool. Is that you mean
to say?


Thanks & Regards,
Nishar Ahamed

**Comment by KazuCocoa** [comment]
That was because I could see below log in your attached one.
```
[debug] �[35m[WD Proxy]�[39m Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/8da2b22a-7116-4461-9d9d-040d70fdf893/screenshot] with no body
```

around the command.

```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m149389 ms - 1236[39m
[info] [35m[HTTP][39m [90m[39m[debug] [35m[MJSONWP (eb075eb0)][39m Responding to client with driver.setContext() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/context [39m[32m200[39m [90m8 ms - 76[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/screenshot[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[MJSONWP (eb075eb0)][39m Calling AppiumDriver.getScreenshot() with args: ["eb075eb0-2ba0-43ea-9798-4936a060fdc3"]
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8200/wd/hub/session/8da2b22a-7116-4461-9d9d-040d70fdf893/screenshot] with no body
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[info] [35m[MJSONWP (eb075eb0)][39m Driver proxy active, passing request on via HTTP proxy
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/window/current/size[39m
[info] [35m[HTTP][39m [90m{}[39m
[info] [35m[MJSONWP (eb075eb0)][39m Driver proxy active, passing request on via HTTP proxy[debug] [35m[WD Proxy][39m Got response with status 500: {"sessionId":"8da2b22a-7116-4461-9d9d-040d70fdf893","value":{"error":"unable to capture screen","message":"Failed to capture a screenshot. Does the current view have 'secure' flag set?","stacktrace":"io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:124)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:59)\n\tat io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:77)\n\tat io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(CaptureScreenshot.java:34)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uia...
[debug] [35m[W3C][39m Matched W3C error code 'unable to capture screen' to UnableToCaptureScreen
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/source' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/source] to [GET http://localhost:8200/wd/hub/session/8da2b22a-7116-4461-9d9d-040d70fdf893/source] with body: {}
[debug] [35m[MJSONWP (eb075eb0)][39m Encountered internal error running command: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:124)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:59)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:77)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(CaptureScreenshot.java:34)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [35m[MJSONWP (eb075eb0)][39m 	at java.lang.Thread.run(Thread.java:818)
[debug] [35m[MJSONWP (eb075eb0)][39m 
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/eb075eb0-2ba0-43ea-9798-4936a060fdc3/screenshot [39m[31m500[39m [90m350 ms - 164[39m
```

**Comment by Nish0106** [comment]
Hi,

The following are the process performed using appium

1. Launching application in UIAutomator
2. Capturing XML source from the tool for each screens

This XML file will be used for testing the application

So What should I do to avoid this issue ?

Please suggests

Thank you,
Nishar Ahamed

**Comment by KazuCocoa** [comment]
A way is to disable https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE You should communicate with developers to control the flag for your testing.

Or you can get the page source via command directly without AppiumDesktop.
Then, you only can get the XML source.

**Comment by Nish0106** [comment]
Hi,

Thank you very much for your immediate response

I will follow your instructions and revert you with the feedback

Thanks & Regards,
Nishar Ahamed
