### ISSUE TITLE
Stderr: 'Security exception: adb clearing user data is forbidden

### ISSUE THREAD

**Issue by wangjingzun** [appium/appium-desktop#1340]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

adb.exe  ..... shell pm clear com.android.settings' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden

## Environment

- I am running Appium Desktop version _v1.15.1_.
- I am on (pick one):
   Windows
  oppo
  andriod 10
 
An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\AndriodSdk\\platform-tools\\adb.exe -P 5037 -s XXXXXX shell pm clear com.android.settings' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden. java.lang.SecurityException: adb clearing user data is forbidden. at com.android.server.pm.ColorClearDataProtectManager.interceptClearUserDataIfNeeded(ColorClearDataProtectManager.java:88) at com.android.server.pm.OppoBasePackageManagerService$OppoPackageManagerInternalImpl.interceptClearUserDataIfNeeded(OppoBasePackageManagerService.java:733) at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:4500) at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1837) at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:212) at android.os.ShellCommand.exec(ShellCommand.java:104) at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23866) at android.os.Binder.shellCommand(Binder.java:881) at android.os.Binder.onTransact(Binder.java:765) at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5352) at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4783) at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java:78) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)'; Code: '255'

**Comment by wangjingzun** [comment]
use v1.17  same error

**Comment by wangjingzun** [comment]
通过这个参数解决了  "noReset": "True"

**Comment by KazuCocoa** [comment]
Thanks.
The root cause is the device does not allow cleanup adb command. Then, appium fails because of failing cleanup.

noReset True skip to cleanup, so it works.

**Comment by saiarun18** [comment]
I tried to launch Chrome browser in mobile (Realme 1) through appium. but i keep on getting the  error.

Error executing adbExec. Original error: 'Command '//adb.exe -P 5037 -s <device id > shell pm clear com.android.browser' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden

I tried with Appium 1.15 and 1.17 versions. but still same error always getting.
Below is my code.

    DesiredCapabilities dac=new DesiredCapabilities().android();
    dac.setCapability("udid","<device id>");
    dac.setCapability("deviceName","<device id>");
    dac.setCapability("platformName","Android");
    dac.setCapability("platformVersion","9");
    dac.setCapability("newCommandTimeout","8000");
    dac.setCapability("noRetest",true);
    dac.setCapability("automationName","appium");
    dac.setCapability("browserName","browser");

    URL url = new URL("http://127.0.0.1:4723/wd/hub");
    driver1 =new AndroidDriver<MobileElement>(url, dac);
    driver.get("http://www.yahoo.com");

**Comment by KazuCocoa** [comment]
If you meant `noRetest`, it is typo. `noReset` is correct.

**Comment by saiarun18** [comment]
i tried "noReset" also, but same issue 
 Error executing adbExec. Original error: 'Command '//adb.exe -P 5037 -s shell pm clear com.android.browser' exited with code 255'; Stderr: 'Security exception: adb clearing user data is forbidden.

actually the same set of code is working for me in another device (redmi note 8)
but its not working in (oppo A32).

i found some difference between both devices that 
in Oppo A32 (generally all Oppo devices)

under Developer options 
Install via USB
(Allow installing App via USB)

USB debugging(Security settings)
Allow granting permissions and simulating input via USB debugging. , these options are not available in OPPO devices. 

how to over come this issue

**Comment by saiarun18** [comment]
@KazuCocoa , in previous comments, you provided one solution like 

"noReset True skip to cleanup, so it works."  

can you guide how to use that cleanup in desired capabilities

**Comment by KazuCocoa** [comment]
Please attach the full Appium log as GIST.
My comment follows https://appium.io/docs/en/writing-running-appium/other/reset-strategies/index.html

**Comment by saiarun18** [comment]
PFB logs,

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4873)
	at android.os.Binder.execTransact(Binder.java:731)

  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18363 x86)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ARUN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4873)
	at android.os.Binder.execTransact(Binder.java:731)

  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18363 x86)
    at getResponseForW3CError (C:\Users\Arun\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Arun\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ARUN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at appium.My_1st_Appium.launchchromebrowser(My_1st_Appium.java:88)
	at appium.My_1st_Appium.main(My_1st_Appium.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 13 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4873)
	at android.os.Binder.execTransact(Binder.java:731)

  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18363 x86)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ARUN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.

java.lang.SecurityException: adb clearing user data is forbidden.
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4873)
	at android.os.Binder.execTransact(Binder.java:731)

  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18363 x86)
    at getResponseForW3CError (C:\Users\Arun\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\Arun\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:392:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 18 more

**Comment by KazuCocoa** [comment]
Thanks, but it seems not the full Appium server log we need. It looks error messages your client got.

**Comment by saiarun18** [comment]
ok @KazuCocoa  , any solution to resolve this issue

**Comment by KazuCocoa** [comment]
We cannot say anything without full Appium server log.

The error was the manufacture's customisation. Appium provides skipping such commands. as a workaround.

**Comment by saiarun18** [comment]
[appium.log](https://github.com/appium/appium-desktop/files/4797817/appium.log)

Please refer the attached log

**Comment by KazuCocoa** [comment]
It seems chrome driver tried to clean the target local data. (it was not Appium itself) 

```
2020-06-18 09:53:53:319 [WD Proxy] Matched '/session' to command name 'createSession'
2020-06-18 09:53:53:320 [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","w3c":false,"androidDeviceSerial":"BIMNKJBME6EYSC7D"},"loggingPrefs":{"browser":"ALL"}}}
2020-06-18 09:53:53:703 [WD Proxy] Got response with status 200: {"sessionId":"7fff4c2b934d4e075113718f964bed8f","status":13,"value":{"message":"unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.\n\njava.lang.SecurityException: adb clearing user data is forbidden.\n\tat com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)\n\tat com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)\n\tat android.os.ShellCommand.exec(ShellCommand.java:103)\n\tat com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)\n\tat android.os.Binder.shellCommand(Binder.java:634)\n\tat android.os.Binder.onTransact(Binder.java:532)\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)\n\tat com.android.server.pm.PackageManagerService.onTransact(Packag...
2020-06-18 09:53:53:704 [WD Proxy] Determined the downstream protocol as 'MJSONWP'
2020-06-18 09:53:53:706 [MJSONWP] Matched JSONWP error code 13 to UnknownError
2020-06-18 09:53:53:707 [Chromedriver] Failed to start Chromedriver session: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to clear data for com.android.chrome on device BIMNKJBME6EYSC7D: Security exception: adb clearing user data is forbidden.
2020-06-18 09:53:53:708 [Chromedriver] 
2020-06-18 09:53:53:709 [Chromedriver] java.lang.SecurityException: adb clearing user data is forbidden.
2020-06-18 09:53:53:710 [Chromedriver] 	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:7741)
2020-06-18 09:53:53:714 [Chromedriver] 	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:1616)
2020-06-18 09:53:53:716 [Chromedriver] 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:199)
2020-06-18 09:53:53:717 [Chromedriver] 	at android.os.ShellCommand.exec(ShellCommand.java:103)
2020-06-18 09:53:53:718 [Chromedriver] 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25311)
2020-06-18 09:53:53:718 [Chromedriver] 	at android.os.Binder.shellCommand(Binder.java:634)
2020-06-18 09:53:53:719 [Chromedriver] 	at android.os.Binder.onTransact(Binder.java:532)
2020-06-18 09:53:53:721 [Chromedriver] 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3254)
2020-06-18 09:53:53:722 [Chromedriver] 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4873)
2020-06-18 09:53:53:726 [Chromedriver] 	at android.os.Binder.execTransact(Binder.java:731)
2020-06-18 09:53:53:727 [Chromedriver] 
2020-06-18 09:53:53:728 [Chromedriver]   (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18363 x86)
2020-06-18 09:53:53:932 [WD Proxy] Matched '/session' to command name 'createSession'
2020-06-18 09:53:53:936 [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","w3c":false,"androidDeviceSerial":"BIMNKJBME6EYSC7D"},"loggingPrefs":{"browser":"ALL"}}}
```

You should find the way to skip clearing data, I assume.
https://chromedriver.chromium.org/capabilities

I haven't tried, but potentially `androidUseRunningApp`  https://chromedriver.chromium.org/getting-started/getting-started---android may help.

You can pass options via `chromeOptions` https://appium.io/docs/en/writing-running-appium/caps/ by Appium

**Comment by abdl-azis** [comment]
Hey bro, I got the same problem using the oppo reno 3 device.
 
 Is there a solution? @saiarun18

**Comment by manish837** [comment]
Hey bro, I also got the same problem using the oppo reno 3 pro device.

Is there a solution? @saiarun18

**Comment by Ajay012** [comment]
Hi, I am facing the same issue on Realme device
@KazuCocoa 
@wangjingzun @saiarun18

**Comment by KazuCocoa** [comment]
`noReset: true` should help in Appium.
If your case was by chromedriver like https://github.com/appium/appium-desktop/issues/1340#issuecomment-645924496 since , Appium only can pass `chromeOptions` to the driver. Probably chromedriver called `adb pm clean` in the initial session.  I don't know how to skip it, but probably you can find the way in https://chromedriver.chromium.org/capabilities . 

I didn't have any devices reported here, so I have no exact idea how to solve it.
Potentially you should set these devices up to relax some security stuff in their developer options etc. (It depends on the manufacture)

**Comment by snevesbarros** [comment]
Just adding the answer here as I faced the same issue (but on an OPPO device), but was able to resolve it by using a new flag that was added to chromedriver.

The issue is that noReset works for native apps, but chromedriver itself also makes the call to clear the user app data before it launches chrome. To prevent this a new argument "[androidKeepAppDataDir](https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/capabilities.cc;l=588?q=keep_app_data_dir&ss=chromium%2Fchromium%2Fsrc)" was added around 4 months ago.

        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        appCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "UiAutomator2");
        appCapabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        appCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("androidKeepAppDataDir", true);
        appCapabilities.setCapability(ChromeOptions.CAPABILITY, options);
The above works for me on an OPPO device (which originally showed the same error as mentioned above) and prevents chromedriver from calling the adb clear command.

Hope this helps.
