### ISSUE TITLE
 Original error: JAVA_HOME is not set currently. Please set JAVA_HOME.

### ISSUE THREAD

**Issue by Ad1991** [appium/appium-desktop#1405]
Appium
This is my .bash_profile:

export M2_HOME=/usr/local/apache-maven/apache-maven-3.6.0
export M2=$M2_HOME/bin
export PATH=$M2:$PATH
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home
export JDK_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home
export PATH=$PATH:$JAVA_HOME/bin
export PUBLIC_PATH_PREFIX=/p
export PATH=${PATH}:/usr/local/mysql/bin
export ANDROID_HOME=/Users/<username>/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME:$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export NODE_PATH=usr/local/bin/node
export PATH=${PATH}:/usr/local/lib/node_modules/npm/bin

## The problem:
When ever i try to run the program, Im getting this error " Original error: JAVA_HOME is not set currently. Please set JAVA_HOME."

Im running it on MAC.
Can someone please help me on it

**Comment by KazuCocoa** [comment]
Duplicate of https://github.com/appium/appium-desktop/issues/1402 ?

**Comment by Ad1991** [comment]
> Duplicate of #1402 ?

Nope

**Comment by KazuCocoa** [comment]
Could you attach the full log as GIST?

Btw, do you mean appium cli stuff?
This repository is Appium Desktop specific thing. Then, will transfer this issue to appium/appium

**Comment by Ad1991** [comment]
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: JAVA_HOME is not set currently. Please set JAVA_HOME.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXXX', ', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_251'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: JAVA_HOME is not set currently. Please set JAVA_HOME.
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:392:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)

**Comment by Ad1991** [comment]
Its not appium Desktop thing

**Comment by KazuCocoa** [comment]
Thanks for the log, but we need the full server side log.
The attached one was the client side.
