### ISSUE TITLE
 Original error: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by lakshmank04199** [appium/appium-desktop#1427]
## The problem

flow breaks in the middle of a run with error- "Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up"
this occurs only on physical devices 

## Environment

- I am running Appium Desktop version _<1.15.1>_.
- I am on (pick one):
    - [x] Linux

please find appium logs below
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4779741/appium-server-logs.txt)

**Comment by KazuCocoa** [comment]
Could you share the logcat?
I could below message in the log. UIA2 server in the device crashed.

```
io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerCon...
[debug] [35m[W3C][39m Matched W3C error code 'no such element' to NoSuchElementError
[debug] [35m[BaseDriver][39m Waited for 4937 ms so far[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0[debug] [35m[Instrumentation][39m The process has exited with code 0
[debug] [35m[WD Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://localhost:8210/wd/hub/session/3114b1b6-5566-44a1-b41f-f5e4e5548914/element] with body: {"strategy":"xpath","selector":"//android.widget.Image[@text='chevron forward outline']","context":"","multiple":false}
```

**Comment by lakshmank04199** [comment]
thanks for the response
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/4781414/appium-server-logs.txt)
[logcat.txt](https://github.com/appium/appium-desktop/files/4781432/logcat.txt)

**Comment by KazuCocoa** [comment]
Definitely a crash happened in the instrumentation process, but could not find the cause in the logcat...
Probably it needs to debug with breakpoint more...

```
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://localhost:8204/wd/hub/session/1f9c62b4-c764-4b99-85a1-a412145a2339/element] with body: {"strategy":"xpath","selector":"//android.widget.Button[contains(@text,'Login using password')]","context":"","multiple":false}[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"1f9c62b4-c764-4b99-85a1-a412145a2339","value":{"ELEMENT":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4","element-6066-11e4-a52e-4f735466cecf":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4"}}
[debug] [35m[W3C (d25a0227)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4","ELEMENT":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d25a0227-3755-46f8-9fbf-6cf1a2d6e819/element [39m[32m200[39m [90m2703 ms - 137[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d25a0227-3755-46f8-9fbf-6cf1a2d6e819/element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click[39m
[info] [35m[HTTP][39m [90m{"id":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4"}[39m
[debug] [35m[W3C (d25a0227)][39m Calling AppiumDriver.click() with args: ["d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4","d25a0227-3755-46f8-9fbf-6cf1a2d6e819"]
[debug] [35m[WD Proxy][39m Matched '/element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click' to command name 'click'
[debug] [35m[WD Proxy][39m Proxying [POST /element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click] to [POST http://localhost:8204/wd/hub/session/1f9c62b4-c764-4b99-85a1-a412145a2339/element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click] with body: {"element":"d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4"}
[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0
[info] [35m[WD Proxy][39m Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [35m[W3C (d25a0227)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[debug] [35m[W3C (d25a0227)][39m     at JWProxy.command (/tmp/.mount_AppiumiJ3XxC/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d25a0227-3755-46f8-9fbf-6cf1a2d6e819/element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click [39m[31m500[39m [90m228 ms - 554[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/d25a0227-3755-46f8-9fbf-6cf1a2d6e819/screenshot[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (d25a0227)][39m Calling AppiumDriver.getScreenshot() with args: ["d25a0227-3755-46f8-9fbf-6cf1a2d6e819"]
[debug] [35m[WD Proxy][39m Matched '/screenshot' to command name 'getScreenshot'
[debug] [35m[WD Proxy][39m Proxying [GET /screenshot] to [GET http://localhost:8204/wd/hub/session/1f9c62b4-c764-4b99-85a1-a412145a2339/screenshot] with no body[info] [35m[WD Proxy][39m Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[debug] [35m[W3C (d25a0227)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up
[debug] [35m[W3C (d25a0227)][39m     at JWProxy.command (/tmp/.mount_AppiumiJ3XxC/resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:261:13)
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/d25a0227-3755-46f8-9fbf-6cf1a2d6e819/screenshot [39m[31m500[39m [90m21 ms - 554[39m
[info] [35m[HTTP][39m [90m[39m
```

logcat
```
2020-06-15 21:17:34.988 7344-7532/io.appium.uiautomator2.server I/appium: channel read: POST /wd/hub/session/1f9c62b4-c764-4b99-85a1-a412145a2339/element/d2fdbfaa-3ef3-4015-ab92-4d83cefa0da4/click
2020-06-15 21:17:34.992 7344-7532/io.appium.uiautomator2.server I/appium: Click element command
2020-06-15 21:17:56.201 7874-7874/? I/zygote64: Late-enabling -Xcheck:jni
2020-06-15 21:17:56.291 7874-7874/io.appium.uiautomator2.server I/zygote64: The ClassLoaderContext is a special shared library.
2020-06-15 21:17:56.295 7874-7874/io.appium.uiautomator2.server I/zygote64: The ClassLoaderContext is a special shared library.
2020-06-15 21:17:56.298 7874-7874/io.appium.uiautomator2.server W/zygote64: ClassLoaderContext classpath element mismatch for position 0. expected=/system/framework/android.test.mock.jar, found=/system/framework/android.test.runner.jar (PCL[/system/framework/android.test.mock.jar*1065265343:/system/framework/android.test.runner.jar*1742119008] | PCL[/system/framework/android.test.runner.jar*1742119008:/system/framework/android.test.mock.jar*1065265343])
2020-06-15 21:17:56.302 7874-7874/io.appium.uiautomator2.server W/zygote64: ClassLoaderContext classpath size mismatch for position 0. expected=0, found=4 (PCL[] | PCL[/system/framework/android.test.runner.jar*1742119008:/system/framework/android.test.mock.jar*1065265343:/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk*2134910765:/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk!classes2.dex*2874176862])
2020-06-15 21:17:56.304 7874-7874/io.appium.uiautomator2.server W/zygote64: Found duplicate classes, falling back to extracting from APK : /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk
2020-06-15 21:17:56.304 7874-7874/io.appium.uiautomator2.server W/zygote64: NOTE: This wastes RAM and hurts startup performance.
2020-06-15 21:17:56.304 7874-7874/io.appium.uiautomator2.server W/zygote64: Found duplicated class when checking oat files: 'Ljunit/runner/BaseTestRunner;' in /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk and /system/framework/android.test.runner.jar
2020-06-15 21:17:56.559 7874-7874/io.appium.uiautomator2.server W/System: ClassLoader referenced unknown path: 
2020-06-15 21:17:56.610 7874-7874/io.appium.uiautomator2.server I/MonitoringInstr: Instrumentation started!
2020-06-15 21:17:56.616 7874-7874/io.appium.uiautomator2.server I/MonitoringInstr: Setting context classloader to 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk", zip file "/data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/lib/arm64, /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/lib/arm64, /system/lib64, /vendor/lib64]]]', Original: 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk", zip file "/data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/lib/arm64, /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/lib/arm64, /system/lib64, /vendor/lib64]]]'
2020-06-15 21:17:56.623 7874-7874/io.appium.uiautomator2.server I/MonitoringInstr: No JSBridge.
2020-06-15 21:17:56.627 7874-7889/io.appium.uiautomator2.server I/MonitoringInstr: Setting context classloader to 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk", zip file "/data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/lib/arm64, /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/lib/arm64, /system/lib64, /vendor/lib64]]]', Original: 'dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/base.apk", zip file "/data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/base.apk"],nativeLibraryDirectories=[/data/app/io.appium.uiautomator2.server.test-zb0_HAKqGiCWP8FopqJk7g==/lib/arm64, /data/app/io.appium.uiautomator2.server-FzGSPXYdTEtv0qGoiDtslg==/lib/arm64, /system/lib64, /vendor/lib64]]]'
```
