### ISSUE TITLE
An unexpected error occurred with message: Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by arunrona** [appium/appium-desktop#1449]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [* ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [* ] Mac
    - [ ] Windows
    - [ ] Linux
While trying to launch my app getting below error

An unexpected error occurred with message: Cannot read property 'length' of undefined.
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
TypeError: Cannot read property 'length' of undefined
    at recursive (file:///Applications/Appium.app/Contents/Resources/app/app/renderer/components/Inspector/Source.js:71:28)
    at c.render (file:///Applications/Appium.app/Contents/Resources/app/app/renderer/components/Inspector/Source.js:90:21)
    at finishClassComponent (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:17160:31)
    at updateClassComponent (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:17110:24)
    at beginWork (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:18620:16)
    at HTMLUnknownElement.callCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
    at performUnitOfWork (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
    at workLoopSync (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
    at performSyncWorkOnRoot (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
    at /Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11089:24
    at unstable_runWithPriority (/Applications/Appium.app/Contents/Resources/app/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11084:7)

**Comment by arunrona** [comment]
I had pulled latest version still same issue appears and i see fix already commited for #1450 

 Commits on Jul 08, 2020 @KazuCocoa 
KazuCocoa fix: no children in source (#1450)

Below is latest version detail 
App Version: 1.17.1-1
Electron: 7.2.4
Node.js: 12.8.1

Still same error 

Unhandled Exception
An unexpected error occurred with message: Cannot read property 'length' of undefined.
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
TypeError: Cannot read property 'length' of undefined
    at recursive (file:///Applications/Appium.app/Contents/Resources/app/app/renderer/components/Inspector/Source.js:71:28)
    at c.render (file:///Applications/Appium.app/Contents/Resources/app/app/renderer/components/Inspector/Source.js:90:21)
    at finishClassComponent (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:17160:31)
    at updateClassComponent (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:17110:24)
    at beginWork (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:18620:16)
    at HTMLUnknownElement.callCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
    at performUnitOfWork (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
    at workLoopSync (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
    at performSyncWorkOnRoot (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:21756:9)
    at /Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11089:24
    at unstable_runWithPriority (/Applications/Appium.app/Contents/Resources/app/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:11084:7)

**Comment by KazuCocoa** [comment]
How did you try it out?
The line `Source.js:71:28` is a blank line on current master.
https://github.com/appium/appium-desktop/blob/master/app/renderer/components/Inspector/Source.js#L71

The change is not in 1.17.1-1.
You can try it out https://github.com/appium/appium-desktop/releases/tag/v1.18.0-beta.1 if you want.

**Comment by arunrona** [comment]
I tried out 
By starting inspector session with my app in MAC version it throws the above error 
@KazuCocoa Thanks let me try it out 
Actually earlier i tried this link https://github.com/appium/appium-desktop/releases/tag/v1.17.1-1 

let me try the link you provided thanks

**Comment by arunrona** [comment]
@KazuCocoa Getting this below error after app launch

Call to 'source' failed
[context("NATIVE_APP")] Error response status: 9, UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: Could not find selector (post_context:data:) for path '/session/CX2wrCEk/context'.

**Comment by KazuCocoa** [comment]
It means the target driver does not support `/session/CX2wrCEk/context`.
Probably other changes for mobile web in 1.18.0 beta may affect.
Adding `/context` endpoint to the driver is a proper way.

**Comment by KazuCocoa** [comment]
Please create an issue about it. Perhaps it seems it does not iOS or Android...?

**Comment by arunrona** [comment]
it is a MAC application

**Comment by arunrona** [comment]
@KazuCocoa Thanks you let me wait for this commit #1462 build and i will try it.
