### ISSUE TITLE
An unexpected error occurred with message: Cannot read property 'length' of undefined. [1.18.0-beta.1]

### ISSUE THREAD

**Issue by wulfihm** [appium/appium-desktop#1483]
## Appium or Appium Desktop?
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue
Since it is an issue with the inspector I expect it to be a desktop client issue.

## The problem

I tried using the inspector on the google login. When I try to inspect the "Weiter"(Next) button it throws an exception.

<img src="https://user-images.githubusercontent.com/9419801/88180638-f557fb80-cc2d-11ea-86ac-7154ec5fd05f.png" width="300">

```
Unhandled Exception
An unexpected error occurred with message: Cannot read property 'length' of undefined.
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
TypeError: Cannot read property 'length' of undefined
    at E.render (file:///C:/Program%20Files/Appium/resources/app/dist/renderer.e31bb0bc.js:166:4452)
    at finishClassComponent (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:17160:31)
    at updateClassComponent (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:17110:24)
    at beginWork (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:18620:16)
    at HTMLUnknownElement.callCallback (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:237:16)
    at invokeGuardedCallback (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:292:31)
    at beginWork$1 (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:23203:7)
    at performUnitOfWork (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:22157:12)
    at workLoopSync (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:22130:22)
    at performSyncWorkOnRoot (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:21756:9)
    at C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:11089:24
    at unstable_runWithPriority (C:\Program Files\Appium\resources\app\node_modules\scheduler\cjs\scheduler.development.js:653:12)
    at runWithPriority$1 (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:11084:7)
    at flushSyncCallbackQueue (C:\Program Files\Appium\resources\app\node_modules\react-dom\cjs\react-dom.development.js:11072:3)
```

## Environment

- I am running Appium Desktop version _1.18.0-beta.1_.
Error does not occur with 1.17.1-1
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Thanks.
The current pre-released version has the fix.
Please check it

**Comment by wulfihm** [comment]
@KazuCocoa Works! :)
