### ISSUE TITLE
Memory Leak when trying to shut down the appium server

### ISSUE THREAD

**Issue by jmehtaebates** [appium/appium-desktop#15]
When I try 'Ctrl + C' to shut down the appium server I get the below error

```
[Appium] Received SIGINT - shutting down
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Server.addListener (events.js:239:17)
    at Server.once (events.js:265:8)
    at Server.close (net.js:1490:12)
    at ../../../lib/express/server.js:26:7
    at new Promise (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:201:7)
    at callee$1$0$ (../../../lib/express/server.js:24:18)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```

I see there are few more users facing similar issue @ https://discuss.appium.io/t/appium-1-6-0-beta3-memory-leak/12787

Any pointers how to fix this?

**Comment by jmehtaebates** [comment]
Created new ticket: https://github.com/appium/appium/issues/7644

similar to https://github.com/appium/appium/issues/7328
