### ISSUE TITLE
node ..\Appium\resources\app\node_modules\appium\build\lib\main.js --address 127.0.0.1 --port 4723 无法启动1.18.3版本

### ISSUE THREAD

**Issue by hagyao520** [appium/appium-desktop#1588]
C:\Users\King-liu\AppData\Local\Programs\Appium\resources\app\node_modules\appium\build\lib\main.js:37
async function preflightChecks(parser, args, throwInsteadOfExit = false) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by KazuCocoa** [comment]
Are you talking about Appium CLI? (not appium desktop?)
I think your node version is old. Please try with newer versions.
