### ISSUE TITLE
Request failed due to An unknown server-side error - AWS Device Farm

### ISSUE THREAD

**Issue by DeividWillyan** [appium/appium-desktop#1629]
I'm running the appium with a nodejs script on the aws device farm in an apk generated with Flutter, on my local machine everything works properly, but on the aws of this error ...

```
DEVICEFARM] Setting up your device. This usually takes 2-3 minutes.
[DEVICEFARM] ########### Start executing testspec ###########
 
 
[DEVICEFARM] ########### Entering phase install ###########
 
[DeviceFarm] echo "Navigate to test package directory"
Navigate to test package directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH
[DeviceFarm] npm install *.tgz
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN saveError ENOENT: no such file or directory, open '/tmp/scratchZRZh49.scratch/test-packageinHSGw/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/scratchZRZh49.scratch/test-packageinHSGw/package.json'
npm WARN test-packageinHSGw No description
npm WARN test-packageinHSGw No repository field.
npm WARN test-packageinHSGw No README data
npm WARN test-packageinHSGw No license field.

+ appium@1.0.0
added 126 packages from 153 contributors and audited 126 packages in 16.5s
found 0 vulnerabilities

[DeviceFarm] export APPIUM_VERSION=1.19.0
[DeviceFarm] avm $APPIUM_VERSION

  [36m   install[0m : [90mv1.19.0[0m
  [36m     mkdir[0m : [90m/usr/local/avm/versions/1.19.0[0m
  [36m   install[0m : [90m1.19.0[0m

> appium-windows-driver@1.13.0 install /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-windows-driver
> node install-npm.js

Not installing WinAppDriver since did not detect a Windows system

> core-js@2.6.11 postinstall /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> appium-chromedriver@4.26.1 postinstall /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

[23:40:45] [Chromedriver Install] Installing Chromedriver version '86.0.4240.22' for platform 'linux' and architecture '64'
[23:40:45] [Chromedriver Install] Opening temp file to write 'chromedriver_linux64' to...
[23:40:45] [Chromedriver Install] Opened temp file '/tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64.zip'
[23:40:45] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip to '/tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64.zip'
dbug Support https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip (5.20 MB) has been downloaded to '/tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64.zip' in 0.254s
[23:40:45] [Chromedriver Install] Extracting /tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64.zip to /tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64
[23:40:46] [Chromedriver Install] Creating /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux...
[23:40:46] [Chromedriver Install] Copying unzipped binary, reading from /tmp/20201025-3108-1tedw2s.zd9h/chromedriver_linux64/chromedriver...
[23:40:46] [Chromedriver Install] Writing to /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64...
[23:40:46] [Chromedriver Install] /usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64 successfully put in place
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/avm/versions/1.19.0/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/avm/versions/1.19.0/package.json'
npm WARN 1.19.0 No description
npm WARN 1.19.0 No repository field.
npm WARN 1.19.0 No README data
npm WARN 1.19.0 No license field.

+ appium@1.19.0
added 763 packages from 600 contributors and audited 763 packages in 17.111s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/usr/bin/avm: line 286: appium: command not found
  [36m installed[0m : [90m[0m

[DeviceFarm] ln -s /usr/local/avm/versions/$APPIUM_VERSION/node_modules/.bin/appium  /usr/local/avm/versions/$APPIUM_VERSION/node_modules/appium/bin/appium.js
 
[DEVICEFARM] ########### Entering phase pre_test ###########
 
[DeviceFarm] echo "Start appium server"
Start appium server
[DeviceFarm] appium --log-timestamp --default-capabilities "{\"deviceName\": \"$DEVICEFARM_DEVICE_NAME\", \"platformName\":\"$DEVICEFARM_DEVICE_PLATFORM_NAME\", \"app\":\"$DEVICEFARM_APP_PATH\", \"udid\":\"$DEVICEFARM_DEVICE_UDID\", \"platformVersion\":\"$DEVICEFARM_DEVICE_OS_VERSION\", \"chromedriverExecutable\":\"$DEVICEFARM_CHROMEDRIVER_EXECUTABLE\"}" >> $DEVICEFARM_LOG_DIR/appiumlog.txt 2>&1 &
[DeviceFarm] start_appium_timeout=0; while [ true ]; do
    if [ $start_appium_timeout -gt 60 ];
    then
        echo "appium server never started in 60 seconds. Exiting";
        exit 1;
    fi;
    grep -i "Appium REST http interface listener started on 0.0.0.0:4723" $DEVICEFARM_LOG_DIR/appiumlog.txt >> /dev/null 2>&1;
    if [ $? -eq 0 ];
    then
        echo "Appium REST http interface listener started on 0.0.0.0:4723";
        break;
    else
        echo "Waiting for appium server to start. Sleeping for 1 second";
        sleep 1;
        start_appium_timeout=$((start_appium_timeout+1));
    fi;
done;
Waiting for appium server to start. Sleeping for 1 second
Appium REST http interface listener started on 0.0.0.0:4723
 
[DEVICEFARM] ########### Entering phase test ###########
 
[DeviceFarm] echo "Navigate to test source code"
Navigate to test source code
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH/node_modules/*
[DeviceFarm] echo "Start Appium Node test"
Start Appium Node test
[DeviceFarm] node ../appium/index.js $DEVICEFARM_DEVICE_PLATFORM_NAME $DEVICEFARM_DEVICE_NAME $DEVICEFARM_DEVICE_OS_VERSION $DEVICEFARM_APP_PATH
{ platformName: 'Android',
  deviceName: '88RX029VF',
  platformVersion: '10',
  app:
   '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk' }
Initial app testing
2020-11-25T23:40:50.266Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-11-25T23:40:50.270Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2020-11-25T23:40:50.270Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        deviceName: '88RX029VF',
        platformVersion: '10',
        app:
         '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
        automationName: 'Flutter' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     deviceName: '88RX029VF',
     platformVersion: '10',
     app:
      '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
     automationName: 'Flutter' } }
2020-11-25T23:40:57.279Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: Could not find 'apksigner.jar' in ["/opt/dev/android-sdk-linux/platform-tools/apksigner.jar","/opt/dev/android-sdk-linux/emulator/apksigner.jar","/opt/dev/android-sdk-linux/cmdline-tools/latest/bin/apksigner.jar","/opt/dev/android-sdk-linux/tools/apksigner.jar","/opt/dev/android-sdk-linux/tools/bin/apksigner.jar","/opt/dev/android-sdk-linux/apksigner.jar","/opt/dev/android-sdk-linux/build-tools/21.1.1/apksigner.jar","/opt/dev/android-sdk-linux/build-tools/21.1.1/lib/apksigner.jar"]. Do you have Android Build Tools installed at '/opt/dev/android-sdk-linux'?
2020-11-25T23:40:57.279Z INFO webdriver: Retrying 1/3
2020-11-25T23:40:57.279Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2020-11-25T23:40:57.279Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        deviceName: '88RX029VF',
        platformVersion: '10',
        app:
         '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
        automationName: 'Flutter' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     deviceName: '88RX029VF',
     platformVersion: '10',
     app:
      '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
     automationName: 'Flutter' } }
2020-11-25T23:40:57.282Z WARN webdriver: Request failed due to socket hang up
2020-11-25T23:40:57.282Z INFO webdriver: Retrying 2/3
2020-11-25T23:40:57.282Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2020-11-25T23:40:57.282Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        deviceName: '88RX029VF',
        platformVersion: '10',
        app:
         '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
        automationName: 'Flutter' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     deviceName: '88RX029VF',
     platformVersion: '10',
     app:
      '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
     automationName: 'Flutter' } }
2020-11-25T23:41:00.941Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of '/usr/local/avm/versions/1.19.0/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v4.15.0.apk'. Original error: Could not find 'apksigner.jar' in ["/opt/dev/android-sdk-linux/platform-tools/apksigner.jar","/opt/dev/android-sdk-linux/emulator/apksigner.jar","/opt/dev/android-sdk-linux/cmdline-tools/latest/bin/apksigner.jar","/opt/dev/android-sdk-linux/tools/apksigner.jar","/opt/dev/android-sdk-linux/tools/bin/apksigner.jar","/opt/dev/android-sdk-linux/apksigner.jar","/opt/dev/android-sdk-linux/build-tools/21.1.1/apksigner.jar","/opt/dev/android-sdk-linux/build-tools/21.1.1/lib/apksigner.jar"]. Do you have Android Build Tools installed at '/opt/dev/android-sdk-linux'?
2020-11-25T23:41:00.942Z INFO webdriver: Retrying 3/3
2020-11-25T23:41:00.942Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
2020-11-25T23:41:00.942Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        deviceName: '88RX029VF',
        platformVersion: '10',
        app:
         '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
        automationName: 'Flutter' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     deviceName: '88RX029VF',
     platformVersion: '10',
     app:
      '/tmp/scratchZRZh49.scratch/share-6T2Dg0.scratch/app-eKD0eI.apk',
     automationName: 'Flutter' } }
2020-11-25T23:41:00.944Z ERROR webdriver: Request failed due to Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:433:23)
    at Socket.emit (events.js:194:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1107:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
2020-11-25T23:41:00.944Z ERROR webdriver: Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:433:23)
    at Socket.emit (events.js:194:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1107:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:3160) UnhandledPromiseRejectionWarning: Error: Failed to create session.
socket hang up
    at startWebDriverSession (/tmp/scratchZRZh49.scratch/test-packageinHSGw/node_modules/webdriver/build/utils.js:45:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:3160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
[DEVICEFARM] ########### Entering phase post_test ###########
 
 
[DEVICEFARM] ########### Finish executing testspec ###########
 
[DEVICEFARM] ########### Setting upload permissions ###########
 
 
[DEVICEFARM] Tearing down your device. Your tests report will come shortly.

```

**Comment by KazuCocoa** [comment]
It would be good to ask AWS Device Farm support. I don't know if they support Flutter stuff.
And https://github.com/truongsinh/appium-flutter-driver is a proper place to get answer about Flutter automationName.
