### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by gaopu202** [appium/appium-desktop#163]
## The problem

initialized app failed. Always ask to install app again if have installed. as appium desktop not support noReset so uninstall app then initialize,  but this issue again. 

## Environment

- I am running Appium Desktop version _<1.0.0>_.
- I am on (pick one):
    - [ ] Windows
           android 7.0
## log:
```
[ADB] 1 device(s) connected
[ADB] Running 'D:\software\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","CJL5T1630500xxxx","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D\:\\software\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s CJL5T1630500xxxx install C\:\\Users\\xxxx\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install C:\Users\xxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.unlock signatures do not match the previously installed version; ignoring!]'; Code: '1'
    at ADB.execFunc$ (C:\Users\xxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:200:13)
    at tryCatch (C:\Users\xxxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\xxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\xxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\xxxx\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 2611 ms - 831 
```

**Comment by dpgraham** [comment]
This is similar to this S.O. question: http://stackoverflow.com/questions/31489567/manually-installing-an-updated-apk-fails-with-signatures-do-not-match-the-previ

Can you try running `adb install "io.appium.unlock"` from your command line and then try again?

**Comment by jlipps** [comment]
Appium Desktop _does_ support `noReset`: set the "noReset" capability to `true`.

**Comment by Amittallewar** [comment]
Facing the issue while executing on android 7.0 
**Log:**
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'E\:\\Android_Sdk\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s ZH33B2DN54 install C\:\\Users\\admin\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk' exited with code 1'; Stderr: 'adb: failed to install C:\Users\admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.unlock signatures do not match the previously installed version; ignoring!]'; Code: '1'
    at ADB.execFunc$ (C:\Users\admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:317:13)
    at tryCatch (C:\Users\admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\admin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
