### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Command 'find C\:\\Users\\****\\AppData\\Local\\Temp\\201742-5920-27ux2n.1i8gvkuik9 -type d -name \*.apk' exited with code 2

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium-desktop#164]
## Appium or Appium Desktop?
This is happening with Appium and Appium-Desktop

## The problem
When I run the script below error is appearing without proceeding.
```
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"E:\\Apps\\MotivDeveloper.ipa","browserName":"","platformName":"Android","version":"6.0.1","deviceName":"Shure India (Galaxy Tab S)","platform":"ANDROID"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"E:\\Apps\\MotivDeveloper.ipa","browserName":"","platformName":"Android","version":"6.0.1","deviceName":"Shure India (Galaxy Tab S)","platform":"ANDROID"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1493721345511 (16:05:45 GMT+0530 (India Standard Time))
[Appium] Creating new AndroidDriver (v1.17.1) session
[Appium] Capabilities:
[Appium]   app: 'E:\\Apps\\MotivDeveloper.ipa'
[Appium]   browserName: ''
[Appium]   platformName: 'Android'
[Appium]   version: '6.0.1'
[Appium]   deviceName: 'Shure India (Galaxy Tab S)'
[Appium]   platform: 'ANDROID'
[AndroidDriver] AndroidDriver version: 1.17.1
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform.
[BaseDriver] Session created with session id: 3e2ba41a-7978-4b8c-9e14-525210bda766
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_45
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Appium\adt-bundle-windows-x86-20140702\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 3204061f25611199
[ADB] Checking whether adb is present
[ADB] Using adb.exe from D:\Appium\adt-bundle-windows-x86-20140702\sdk\platform-tools\adb.exe
[ADB] Setting device id to 3204061f25611199
[BaseDriver] Using local app 'E:\Apps\MotivDeveloper.ipa'
[BaseDriver] Copying local zip to tmp dir
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running 'D:\Appium\adt-bundle-windows-x86-20140702\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","3204061f25611199","shell","am","force-stop","io.appium.unlock"]
[AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[MJSONWP] Encountered internal error running command: Error: Command 'find C\:\\Users\\SysAdmin\\AppData\\Local\\Temp\\201742-5920-27ux2n.1i8gvkuik9 -type d -name \*.apk' exited with code 2
    at ChildProcess. (C:\Users\SysAdmin\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\teen_process\lib\teen_process.js:70:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 2073 ms - 279 
```
## Environment
- I am running Appium Desktop version _1.0.0_ and Appium _1.6.4_
- I am on (pick one):
    - [ ] Mac
    - [* ] Windows - 32 bit 
    - [ ] Linux

**Comment by imurchie** [comment]
Why are you sending an `ipa` file to an Android test?

**Comment by shivakrishnach31** [comment]
@imurchie Sorry That was my fault. I passed apk path and now it is working.
