### ISSUE TITLE
Android Session is not connecting in 1.20.2 via Java programmatically using capabilities which used to work in older appium versions

### ISSUE THREAD

**Issue by yadavsvmx** [appium/appium-desktop#1707]
## Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Android Session is not connecting via Java programmatically using capabilities which used to work in older appium versions

I am able to launch the android app in inspector session without any issues, only when i try to run it via Java it is throwing the session terminated exception.

I tried uninstalling the Appium Settings also it did not help.

## Environment

- I am running Appium Desktop version _<1.20.2>_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

## Logs

org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: A new session could not be created. Details: io.appium.uiautomator2.common.exceptions.NoSuchDriverException: A session is either terminated or not started
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'C02ZG011NQMC', ip: 'fe80:0:0:0:14b4:5a33:4a33:6a8a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_211'
Driver info: driver.version: AndroidDriver
remote stacktrace: io.appium.uiautomator2.common.exceptions.SessionNotCreatedException: io.appium.uiautomator2.common.exceptions.NoSuchDriverException: A session is either terminated or not started
	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:57)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:261)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:255)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:764)
Caused by: io.appium.uiautomator2.common.exceptions.NoSuchDriverException: A session is either terminated or not started
	at io.appium.uiautomator2.model.AppiumUIA2Driver.getSessionOrThrow(AppiumUIA2Driver.java:55)
	at io.appium.uiautomator2.model.settings.EnableMultiWindows.getValue(EnableMultiWindows.java:32)
	at io.appium.uiautomator2.model.settings.EnableMultiWindows.getValue(EnableMultiWindows.java:21)
	at io.appium.uiautomator2.model.Session.<init>(Session.java:49)
	at io.appium.uiautomator2.model.AppiumUIA2Driver.initializeSession(AppiumUIA2Driver.java:42)
	at io.appium.uiautomator2.handler.NewSession.safeHandle(NewSession.java:50)

**Comment by KazuCocoa** [comment]
Please attach the full Appium log

**Comment by yadavsvmx** [comment]
[1.20.2 android issue appium-server-logs.txt](https://github.com/appium/appium-desktop/files/6047357/1.20.2.android.issue.appium-server-logs.txt)

Attaching the full appium logs

**Comment by KazuCocoa** [comment]
thanks, but could you share the logcat as well?
Your attached log probably indicated something happened in uia2 server side.

Btw, settings should be https://appium.io/docs/en/writing-running-appium/caps/#update-settings if you wanted to set them as capabilities

**Comment by yadavsvmx** [comment]
Can u guide me how to get the LogCat ?

Thanks,
Yadav Thyagaraj
Staff Quality Assurance Engineer

[A picture containing object, clock, traffic, drawing  Description automatically generated]

**Comment by KazuCocoa** [comment]
The easiest way is https://developer.android.com/studio/debug/am-logcat

**Comment by yadavsvmx** [comment]
[1.20.2 logCat android issue.txt](https://github.com/appium/appium-desktop/files/6047868/1.20.2.logCat.android.issue.txt)

Please find the LogCat logs

**Comment by KazuCocoa** [comment]
Once you correct `enableMultiWindows` as `"settings[enableMultiWindows]": true`, it should work.
https://appium.io/docs/en/writing-running-appium/caps/#update-settings
(If `enableMultiWindows` worked as capabilities without `settings`, then it was accidental..)

Or you could use the latest beta. The crash should not happen.

**Comment by yadavsvmx** [comment]
We have enabled it, 					

capabilities.setCapability("enableMultiWindows", true);

But still the issue seems to occur even in the beta version.

**Comment by KazuCocoa** [comment]
Did you correct the capability?

---

My env did not happen the error in beta, but potentially some condition affected. (But enableMultiWindows did not work then since incorrect capability. This was expected.)

**Comment by yadavsvmx** [comment]
I tried with the beta version https://github.com/appium/appium-desktop/releases/tag/v1.20.2-1
Still i encountered the exact same issue.

capabilities.setCapability("enableMultiWindows", true); was always there when we used to run previous versions

**Comment by KazuCocoa** [comment]
1.20.2-1 is not beta. Beta I addressed is https://www.npmjs.com/package/appium/v/1.21.0-beta.0

Did you tried out `"settings[enableMultiWindows]": true` syntax as I addressed?
We expect the syntax for settings items in capabilities as https://appium.io/docs/en/writing-running-appium/caps/#update-settings
No desired capabilities named `enableMultiWindows`, so I addressed it worked accidentally (this case was a bug) if your environment worked with it. https://github.com/search?q=org%3Aappium+enableMultiWindows&type=code

If the same issue happens with  `"settings[enableMultiWindows]": true`, it will be appreciated to attach the appium log here.

**Comment by yadavsvmx** [comment]
But i am using appium desktop version, and there is no 1.21.0-beta version for me to test on in the releases page

https://github.com/appium/appium-desktop/releases

can u point me to the desktop version of the beta build so that i can try it

**Comment by KazuCocoa** [comment]
We only provide to attach to a local appium as https://github.com/appium/appium-desktop#connect-to-local-appium-server for beta.

Did you try out `capabilities.setCapability("settings[enableMultiWindows]", true);` before using beta? It is correct syntax for `enableMultiWindows` as i addressed a couple of times.

**Comment by yadavsvmx** [comment]
Its working now !
Yes I used the enableMultiWindows capability as true in the exact same way as suggested buy you.

Syntax:
	capabilities.setCapability("settings[enableMultiWindows]", true);

Appium desktop Version :
1.20.2-1

@KazuCocoa Thanks for the quick help.

However , it is having difficulty to maintain the session consistently , i will try a restart of the system and see if it helps else I will post the logs here.

**Comment by yadavsvmx** [comment]
Yes it is having difficulty to maintain the session  

Here are the logs:

[after adding multiwindow setting appium-server-logs.txt](https://github.com/appium/appium-desktop/files/6059258/after.adding.multiwindow.setting.appium-server-logs.txt)


org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'GET /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

**Comment by KazuCocoa** [comment]
Okay.

Please create a new issue for a different one.
