### ISSUE TITLE
java.lang.reflect.InvocationTargetException org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature

### ISSUE THREAD

**Issue by sameeer95** [appium/appium-desktop#1710]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by sameeer95** [comment]
Can someone please help me with this issue. 
I am using JDK v15
Android SDK v28 (tried with all version from 25 to 30 still issue exists)
Appium Desktop Client 1.20.2
Android device v11

**Comment by KazuCocoa** [comment]
Please attach the full appium log as GitHub GIST

**Comment by sameeer95** [comment]
@KazuCocoa I have attached full logs hope this helps.

java.lang.reflect.InvocationTargetException
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Device DRGID18112203989 was not in the list of connected devices
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Device DRGID18112203989 was not in the list of connected devices
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at appium.Calc_Test.openCalc(Calc_Test.java:53)
	at appium.Calc_Test.main(Calc_Test.java:22)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Device DRGID18112203989 was not in the list of connected devices
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Device DRGID18112203989 was not in the list of connected devices
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 19 more

**Comment by sameeer95** [comment]
@KazuCocoa I have attached full logs. Hope this helps.

java.lang.reflect.InvocationTargetException
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\omram\AppData\Local\Temp\202121-6228-st4k8z.w5ovf\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\platform-tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\emulator\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\cmdline-tools\\latest\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\apksigner.jar"]. Do you have Android Build Tools installed at 'H:\Documents\New\Automation\Appium\commandlinetools'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\omram\AppData\Local\Temp\202121-6228-st4k8z.w5ovf\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\platform-tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\emulator\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\cmdline-tools\\latest\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\apksigner.jar"]. Do you have Android Build Tools installed at 'H:\Documents\New\Automation\Appium\commandlinetools'?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:94)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:95)
	at appium.Calc_Test.openCalc(Calc_Test.java:53)
	at appium.Calc_Test.main(Calc_Test.java:22)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\omram\AppData\Local\Temp\202121-6228-st4k8z.w5ovf\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\platform-tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\emulator\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\cmdline-tools\\latest\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\apksigner.jar"]. Do you have Android Build Tools installed at 'H:\Documents\New\Automation\Appium\commandlinetools'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP', ip: '192.168.1.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\omram\AppData\Local\Temp\202121-6228-st4k8z.w5ovf\appium-uiautomator2-server-v4.17.4.apk'. Original error: Could not find 'apksigner.jar' in ["H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\platform-tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\emulator\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\cmdline-tools\\latest\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\tools\\bin\\apksigner.jar","H:\\Documents\\New\\Automation\\Appium\\commandlinetools\\apksigner.jar"]. Do you have Android Build Tools installed at 'H:\Documents\New\Automation\Appium\commandlinetools'?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 19 more

**Comment by KazuCocoa** [comment]
> Could not find 'apksigner.jar' in ["H:\Documents\New\Automation\Appium\commandlinetools\platform-tools\apksigner.jar","H:\Documents\New\Automation\Appium\commandlinetools\emulator\apksigner.jar","H:\Documents\New\Automation\Appium\commandlinetools\cmdline-tools\latest\bin\apksigner.jar","H:\Documents\New\Automation\Appium\commandlinetools\tools\apksigner.jar","H:\Documents\New\Automation\Appium\commandlinetools\tools\bin\apksigner.jar","H:\Documents\New\Automation\Appium\commandlinetools\apksigner.jar"]. Do you have Android Build Tools installed at 'H:\Documents\New\Automation\Appium\commandlinetools'?

What version of Android SDK version did you install?
Afaik, the apksinger is in the Android SDK 24+.

http://appium.io/docs/en/drivers/android-uiautomator2/index.html
> The minimum required Android SDK Build Tools version is 24

Or if your environment had `apksigner.jar` in someplace, where is it? Potentially Windows environment has different path to the jar file.

**Comment by sameeer95** [comment]
@KazuCocoa  Yes I have SDK 28.

I see apksigner.jar in C: path under build tools

**Comment by KazuCocoa** [comment]
I guess you should set ANDROID_HOME in _Edit Configuration_ properly in `C:`. Your environment had no proper ANDROID_HOME or something Windows env specific Windows environment stuff...

**Comment by sameeer95** [comment]
I tried to set ANDROID_HOME to C: path having apksigner.jar but still same error comes. Attaching screenshot of folder with apksigner.jar (logs are same as previous one)

![apksigner1](https://user-images.githubusercontent.com/58164124/109494898-83457000-7ab4-11eb-89bb-d95a8847fe72.png)

**Comment by KazuCocoa** [comment]
Thanks.
hm, could you try https://github.com/appium/java-client/blob/master/docs/environment.md out?
