### ISSUE TITLE
Cannot launch app - xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134

### ISSUE THREAD

**Issue by appiumams** [appium/appium-desktop#174]
## Appium or Appium Desktop?

Appium Desktop issue

## The problem

When I try to launch my app with the following capabilities, I get the following error : -

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134

Could you please help me resolve this problem?

Thanks in advance.

Capabilities :- 
{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone 7",
  "app": "....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app"
}

## Environment

- I am running Appium Desktop version _Version 1.0.0 (1.0.0)_.
- I am on (pick one):
    - [x] Mac :- Version 1.0.0 (1.0.0)
    - [ ] Windows
    - [ ] Linux

Xcode version :- Version 8.3.2 (8E2002)

Please find the full logs below

[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app","automationName":"XCUITest","deviceName":"iPhone 7","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app","automationName":"XCUITest","deviceName":"iPhone 7","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1494258551802 (16:49:11 GMT+0100 (BST))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone 7'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: b6239b6a-fa78-48cb-8ce2-61866a5d1201
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1494258551892 (16:49:11 GMT+0100 (BST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid 'CC9F2632-359F-419F-AE7B-68060F4A3FF1'
[XCUITest] Determining device to run tests on: udid: 'CC9F2632-359F-419F-AE7B-68060F4A3FF1', real device: false
[BaseDriver] Using local app '....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app'
[BaseDriver] Event 'appConfigured' logged at 1494258552217 (16:49:12 GMT+0100 (BST))
[XCUITest] Checking whether app '....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app': 'org.reactjs.native.example.ABCDxxxx'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1494258552220 (16:49:12 GMT+0100 (BST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1494258552420 (16:49:12 GMT+0100 (BST))
[iOSLog] Starting iOS 10.3 simulator log capture
[iOSLog] System log path: /Users/ABCDuser/Library/Logs/CoreSimulator/CC9F2632-359F-419F-AE7B-68060F4A3FF1/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1494258552556 (16:49:12 GMT+0100 (BST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Reset requested. Removing app with id 'org.reactjs.native.example.ABCDapp' from the device
[XCUITest] Simulator with udid 'CC9F2632-359F-419F-AE7B-68060F4A3FF1' already booted
[BaseDriver] Event 'simStarted' logged at 1494258552812 (16:49:12 GMT+0100 (BST))
[XCUITest] Installing ....../Build/Products/Debug-iphonesimulator/ABCDxxxx.app on Simulator with UUID 'CC9F2632-359F-419F-AE7B-68060F4A3FF1'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1494258558265 (16:49:18 GMT+0100 (BST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1494258558268 (16:49:18 GMT+0100 (BST))
[XCUITest] Using WDA path: '/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Symbol not found: __TWPC13ReactiveSwift14QueueSchedulerS_13DateSchedulerS_
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
[XCUITest]  in /usr/local/bin/carthage
[XCUITest] Scripts/bootstrap.sh: line 45: 15738 Abort trap: 6           carthage bootstrap $USE_SSH
[BaseDriver] Event 'wdaStartFailed' logged at 1494258558334 (16:49:18 GMT+0100 (BST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1494258568482 (16:49:28 GMT+0100 (BST))
[XCUITest] Using WDA path: '/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] dyld: Symbol not found: __TWPC13ReactiveSwift14QueueSchedulerS_13DateSchedulerS_
[XCUITest]   Referenced from: /usr/local/bin/carthage
[XCUITest]   Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
[XCUITest]  in /usr/local/bin/carthage
[XCUITest] Scripts/bootstrap.sh: line 45: 15749 Abort trap: 6           carthage bootstrap $USE_SSH
[BaseDriver] Event 'wdaStartFailed' logged at 1494258568517 (16:49:28 GMT+0100 (BST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 134
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/2d/3g2g4c1j1132s9mc31yp02zc0000gn/T/AppTranslocation/86BAA90F-88A3-4286-9C62-E9786167839C/d/Appium 3.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 26927 ms - 254 
[HTTP] --> DELETE /wd/hub/session {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57

**Comment by DeepikaThiru** [comment]
Me too getting the same problem. Can anyone please resolve this?

This is the log that I got.
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app","xcodeConfigfile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","deviceName":"iPad Air 2"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app","xcodeConfigfile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3","automationName":"XCUITest","platformName":"iOS","deviceName":"iPad Air 2"},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1494324893659 (15:44:53 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app'
[Appium]   xcodeConfigfile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '9.3'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPad Air 2'
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: xcodeConfigfile, realDeviceLogger.
[BaseDriver] Session created with session id: 0d5dbf6a-af4c-40f0-a3a9-dc6ee49611ba
[XCUITest] Xcode version set to '8.3.2' 
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1494324893720 (15:44:53 GMT+0530 (IST))
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid '2743A64B-701D-4538-9D35-1523AEB8D292'
[XCUITest] Determining device to run tests on: udid: '2743A64B-701D-4538-9D35-1523AEB8D292', real device: false
[BaseDriver] Using local app '/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app'
[BaseDriver] Event 'appConfigured' logged at 1494324893898 (15:44:53 GMT+0530 (IST))
[XCUITest] Checking whether app '/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app': 'com.mcclatchy.kcstar'
[BaseDriver] Event 'resetStarted' logged at 1494324893900 (15:44:53 GMT+0530 (IST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1494324894069 (15:44:54 GMT+0530 (IST))
[iOSLog] Starting iOS 9.3 simulator log capture
[iOSLog] System log path: /Users/vijaygvb/Library/Logs/CoreSimulator/2743A64B-701D-4538-9D35-1523AEB8D292/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1494324894182 (15:44:54 GMT+0530 (IST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Reset requested. Removing app with id 'com.mcclatchy.kcstar' from the device
[XCUITest] Simulator with udid '2743A64B-701D-4538-9D35-1523AEB8D292' already booted
[BaseDriver] Event 'simStarted' logged at 1494324894377 (15:44:54 GMT+0530 (IST))
[XCUITest] Installing /Users/vijaygvb/Library/Developer/Xcode/DerivedData/phoenix-reader-dzoeikczurceevdyabsarasjioww/Build/Products/Debug-iphonesimulator/phoenix-reader.app on Simulator with UUID '2743A64B-701D-4538-9D35-1523AEB8D292'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1494324897711 (15:44:57 GMT+0530 (IST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1494324897714 (15:44:57 GMT+0530 (IST))
[XCUITest] Using WDA path: '/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] Failed to write to /private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fbca3d58000 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}
[BaseDriver] Event 'wdaStartFailed' logged at 1494324899038 (15:44:59 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1494324909161 (15:45:09 GMT+0530 (IST))
[XCUITest] Using WDA path: '/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] Failed to write to /private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7feb75578830 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}
[BaseDriver] Event 'wdaStartFailed' logged at 1494324910426 (15:45:10 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:374:15)
    at tryCatch (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/1k/zgc4j2td1gjggq142d0075qh0000gn/T/AppTranslocation/3ABF00B4-C6A7-4F5A-996B-F99F8696AA3D/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 26893 ms - 252 
Appium server stopped successfully

**Comment by imurchie** [comment]
This is _not_ the same issue, @DeepikaThiru. In your case you are running the app from within the dmg. Move the program to your hard drive, and run again.

**Comment by dpgraham** [comment]
@appiumams Have you tested using the CLI to verify that this is a Desktop problem?

**Comment by DeepikaThiru** [comment]
thanks @imurchie . when i move the app to my hard drive its working fine.

**Comment by appiumams** [comment]
@dpgraham I tested using the CLI and i am getting the same error. 
Although Appium Inspector (not the appium desktop inspector) started working fine.

So I am using the Appium Inspector now instead of Appium desktop one.

thanks for your response.

**Comment by dpgraham** [comment]
Can you try running WebDriverAgent from XCode?

If it doesn't run through XCode it won't run on Appium Desktop.
