### ISSUE TITLE
Error while fetching sessions in case of self-signed certificates

### ISSUE THREAD

**Issue by huzaifaiftikhar** [appium/appium-desktop#1771]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
If we use self-signed certificates then while getting the list of running sessions (even after enabling the _"Allow Unauthorized Certificates"_ setting) we get an exception. We fixed part of the problem in https://github.com/appium/appium-desktop/pull/469 but it's still present for the case where we fetch the list of running sessions from the cloud provider.

**Screenshot**
![image](https://user-images.githubusercontent.com/10832531/115547232-aece2500-a2c3-11eb-92b7-d51e151c0b5b.png)

**Stacktrace**
```
RequestError: Error: self signed certificate in certificate chain
  at new RequestError (C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\request-promise-core\\lib\\errors.js:14:15)
    at Request.plumbing.callback (C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:87:29)
  at Request.RP$callback [as _callback] (C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\request-promise-core\\lib\\plumbing.js:46:31)
  at self.callback (C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\request\\request.js:185:22)
  at Request.emit (events.js:203:13)
  at Request.onRequestError (C:\\Users\\xyz\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\request\\request.js:881:8)
  at ClientRequest.emit (events.js:203:13)
  at TLSSocket.socketErrorListener (_http_client.js:399:9)
  at TLSSocket.emit (events.js:203:13)
  at emitErrorNT (internal/streams/destroy.js:91:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
  at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Solution**
1. We should honor the _"Allow Unauthorized Certificates"_ setting while making API calls from the `request-promise` module as well similar to what we do for the `admc/wd` library [here](https://github.com/appium/appium-desktop/blob/9a1a7f973ffc244ca557c124a0ca63fe731299e8/app/main/appium.js#L186).
2. We can try implementing it similar to the suggestions mentioned in https://github.com/request/request-promise/issues/225

## Environment

- I am running Appium Desktop version 1.20.2-4.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Please try out latest https://github.com/appium/appium-inspector ...
