### ISSUE TITLE
测试UC浏览器打开URL，出现异常退出，提示An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by hexiaolong-coco** [appium/appium-desktop#1773]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):

    - [x] Windows

![image](https://user-images.githubusercontent.com/57431480/115809828-662b7e80-a41f-11eb-893c-dec6b95460b6.png)
![image](https://user-images.githubusercontent.com/57431480/115809842-6d528c80-a41f-11eb-93ba-e59bf8757d41.png)

异常报错信息如下：
Error
Traceback (most recent call last):
  File "D:\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\Python37\lib\unittest\case.py", line 624, in run
    self.setUp()
  File "D:\JetBrains\PycharmProjects\AutoTest_Creator_V1.0\Android_Web_all\src\static\test3d_Screenshot_Compare.py", line 70, in setUp
    self.driver.get(text.url)
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error attempting to start URI. Original error: Error: Error executing adbExec. Original error: 'Command 'D:\\android_sdk\\platform-tools\\adb.exe -P 5037 -s BIF6J7EQ99VGPBDQ shell am start -W -a android.intent.action.VIEW -d http\://192.168.52.67\:8080/web-mobile/ com.UCMobile' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

**Comment by KazuCocoa** [comment]
Please attach the full appium log and translate the title in English
