### ISSUE TITLE
Appium desktop not displaying relevant logs

### ISSUE THREAD

**Issue by deepikam24** [appium/appium-desktop#1848]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

[GENERIC (d6628de8)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[GENERIC (d6628de8)]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[GENERIC (d6628de8)]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[GENERIC (d6628de8)]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5

Logs are being displayed like the above format, how do I revert back to logs being displayed wrt api calls and view the elements being tested on 

## Environment

- I am running Appium Desktop version _<1.20.2>_.
- I am on (pick one):
    - [ ] Mac

**Comment by jlipps** [comment]
do sessions themselves work? what is the entire log during the course of a session?

**Comment by deepikam24** [comment]
When running automation previously I used to see the post api etc and the Id xpath of the elements used in api in the log. Now I see logs like pasted above. Is there a setting to enable or disable
