### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method (ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl

### ISSUE THREAD

**Issue by Stephane-Tostivin** [appium/appium-desktop#1916]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When I try starting a session in Appium Desktop, the process crashes while executing startEspressoServer, with the message below:

[Espresso] Espresso server is online. The initialization process took 2836ms
[Espresso] Starting the session
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8300/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\StephaneTostivin\\IdeaProjects\\MFT\\src\\test\\resources\\PM3Application-qa.apk","automationName":"Espresso","deviceName":"Pixel XL API 30 (Android 11.0)","ensureWebviewsHavePages":true,"espressoBuildConfig":"{ \"additionalAppDependencies\": [ \"com.google.android.material:material:1.0.0\", \"androidx.lifecycle:lifecycle-extensions:2.1.0\" ] }","platformName":"Android","platformVersion":"11.0","showGradleLog":true,"newCommandTimeout":0,"connectHardwareKeyboard":true},"app":"C:\\Users\\StephaneTostivin\\IdeaProjects\\MFT\\src\\test\\resources\\PM3Application-qa.apk","automationName":"Espresso","deviceName":"emulator-5554","ensureWebviewsHavePages":true,"espressoBuildConfig":"{ \"additionalAppDependencies\": [ \"com.google.android.material:material:1.0.0\",...
[Espresso] [Instrumentation] Process crashed while executing startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[Espresso] java.lang.NoSuchMethodError: No direct method (ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/~~tP2L5Z66hCstgze-NNtVpQ==/io.appium.espressoserver.test-QcJuRnGUFkse4BYebd7hug==/base.apk)
[Espresso] 	at com.praxedo.mobile.pm3.services.impl.DefaultActivationService$checkDatabaseVersion$databaseVersion$1.(Unknown Source:10)
[Espresso] 	at com.praxedo.mobile.pm3.services.impl.DefaultActivationService.checkDatabaseVersion(DefaultActivationService.kt:112)
[Espresso] 	at com.praxedo.mobile.pm3.interactors.StartupInteractor.startup(StartupInteractor.kt:37)
[Espresso] 	at com.praxedo.mobile.pm3.app.screens.main.viewmodel.StartupViewModel$1.invokeSuspend(StartupViewModel.kt:23)
[Espresso] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[Espresso] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[Espresso] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[Espresso] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[Espresso] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[Espresso] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[WD Proxy] socket hang up
[Espresso] Deleting espresso session

I have no issue when running a test from IntelliJ with same capabilities.

## Environment

- I am running Appium Desktop version _1.21.0.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-espresso-driver/issues/686

Probably you should coordinate espresso dependencies:

https://github.com/appium/appium-espresso-driver#troubleshooting
https://github.com/appium/appium-espresso-driver#espresso-build-config
