### ISSUE TITLE
Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.

### ISSUE THREAD

**Issue by alshari86** [appium/appium-desktop#195]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I cannot start new session on iOS real device, It always show error "Could not initialize ios-deploy and make sure it is installed", I've installed ios-deploy already and it keeps showing this error, I tried uninstall Appium and reinstall the latest version of client app, it works fine on simulator
{
at Object.wrappedLogger.errorAndThrow (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13)
    at getRealDeviceObj$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/real-device-management.js:82:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
}
## Environment

- I am running Appium Desktop version _<1.0.2-beta.2>_.
- I am on (pick one):
    - Mac: 10.12.4 (16E195)
- I am on Xcode 8.3.2

**Comment by dpgraham** [comment]
You need to install ios-deploy

```
brew install ios-deploy
```

Try running appium-doctor (https://github.com/appium/appium-doctor) to see what dependencies you need to install

**Comment by alshari86** [comment]
@dpgraham thanks for your response
I fixed that problem by (brew install ios-deploy)
I am curious of one problem that I used "npm install -g ios-deploy" before and also installed ios-deploy but appium always has that error (fail to initialize ios-deploy), this problem is fixed until I use "brew install ios-deploy", what is the difference of them? why using "npm install -g ios-deploy" doesn't work?

I have another problem now after fixed ios-deploy, it shows error like this "Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65"
I know this is something related to webdriveragent failed to run because of provision profile. Can you tell me some more information, I installed the appium client app by zip file not the git clone, so Do I need to clone appium-xcuitest-driver and register device with webdriver agent project?

**Comment by imurchie** [comment]
See the directions here: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by dpgraham** [comment]
The ios-deploy that is installed through `npm install -g ios-deploy` is different from the ios-deploy that is installed through `brew install ios-deploy`.

**Comment by alshari86** [comment]
@dpgraham yep..just wanna what the difference is, if always need brew install ios-deploy, why the message in appium said "npm install -g ios-deploy"?

**Comment by jlipps** [comment]
@alshari86 where did you see it tell you to do that?

**Comment by alshari86** [comment]
When I launch Appium client app and start new session manually on real device, it shows error message from Appium "error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system."

**Comment by jlipps** [comment]
Actually i think it works to install it via NPM too (it's how I did it). But I bet the issue is that your global node modules bin directory is not available on your PATH, so Appium couldn't detect that it was installed.

**Comment by dpgraham** [comment]
Actually yeah, I think have `ios-deploy` confused with `ios-webkit-debug-proxy`

**Comment by rgupta7888** [comment]
Hi folks,
I am trying best to run appium server programmatically but getting below 
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.I installed it through npm install -g ios-deploy and set the path in eclipse but still getting the same error. 
I tried evensudo npm install -g ios-deploy --unsafe-perm --allow-root to install ios-deploy but no luck. 
Please help me . reinstalling appium did not work for me as well.

**Comment by dpgraham** [comment]
Can you provide the full logs?

**Comment by rgupta7888** [comment]
@dpgraham @imurchie 
Please find the logs :

[Appium] Welcome to Appium v1.6.5 (REV 88793ba798cd2dbe3ce44972be912f8f5d892c5e)
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 23850
[Appium]   log: /Users/cex/Downloads/iOS/iOSAutomationHybridFramework/src/com/cexwebuy/logs/Application.log
[Appium] Appium REST http interface listener started on 127.0.0.1:23850
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.5","revision":"88793ba798cd2dbe3ce44972be912f8f5d892c5e"}}
[HTTP] <-- GET /wd/hub/status 200 25 ms - 121 
Jun 09, 2017 1:35:24 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}},"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},{},{"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496952324835 (01:35:24 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   clearSystemFiles: 'true'
[Appium]   bundleId: 'com.cex.cexdevinternal'
[Appium]   automationName: 'XCUITest'
[Appium]   ipa: 'CeX Beta'
[Appium]   udid: '437593bb0b56b28071b0b8287b2c6844f680178c'
[Appium]   platformName: 'iOS'
[Appium]   version: '10.3.2'
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Capability 'clearSystemFiles' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: ipa, version, platform.
[BaseDriver] Session created with session id: 73290986-db79-4617-90a4-34ecbf325755
[debug] [XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496952325113 (01:35:25 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 437593bb0b56b28071b0b8287b2c6844f680178c, 437593bb0b56b28071b0b8287b2c6844f680178c
[debug] [XCUITest] Creating iDevice object with udid '437593bb0b56b28071b0b8287b2c6844f680178c'
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] No WebDriverAgent derived data available, so unable to cl[MJSONWP] Encountered internal error running command: Error: Could not initialize ios-deploy make sure it is installed (npm insear system files
tall -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1095 ms - 248 
Jun 09, 2017 1:35:25 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},{},null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496952325982 (01:35:25 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   clearSystemFiles: 'true'
[Appium]   bundleId: 'com.cex.cexdevinternal'
[Appium]   automationName: 'XCUITest'
[Appium]   ipa: 'CeX Beta'
[Appium]   udid: '437593bb0b56b28071b0b8287b2c6844f680178c'
[Appium]   platformName: 'iOS'
[Appium]   version: '10.3.2'
[Appium]   deviceName: 'iPhone 6'
[Appium]   platform: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Capability 'clearSystemFiles' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: ipa, version, platform.
[BaseDriver] Session created with session id: bb041b05-7154-439c-b4f1-063a5be940ca
[debug] [XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1496952326059 (01:35:26 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 437593bb0b56b28071b0b8287b2c6844f680178c, 437593bb0b56b28071b0b8287b2c6844f680178c
[debug] [XCUITest] Creating iDevice object with udid '437593bb0b56b28071b0b8287b2c6844f680178c'
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[MJSONWP] Encountered internal error running command: Error: Could not initialize ios-deploy make sure it is installed (npm install -g ios-deploy) and works on your system.
    at Object.wrappedLogger.errorAndThrow (../../lib/logging.js:63:13)
    at getRealDeviceObj$ (../../lib/real-device-management.js:82:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 273 ms - 248 
Jun 09, 2017 1:35:26 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [null,null,{"desiredCapabilities":{"clearSystemFiles":"true","bundleId":"com.cex.cexdevinternal","automationName":"XCUITest","ipa":"CeX Beta","udid":"437593bb0b56b28071b0b8287b2c6844f680178c","platformName":"iOS","version":"10.3.2","deviceName":"iPhone 6","platform":"iOS"},"requiredCapabilities":{}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1496952326263 (01:35:26 GMT+0530 (IST))
[MJSONWP] Encountered internal error running command: Error: You must include a platformName capability
    at AppiumDriver.getDriverForCaps (../../lib/appium.js:44:13)
    at AppiumDriver.createSession$ (../../lib/appium.js:157:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (../../lib/appium.js:183:31)
    at ../../../lib/basedriver/driver.js:207:24
    at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by jlipps** [comment]
is ios-deploy in your path from .bashrc?

**Comment by alshari86** [comment]
@rgupta7888 
Please try "brew install iso-deploy" to see if it works then

**Comment by rgupta7888** [comment]
@jlipps 
Yep "/usr/local/bin/ios-deploy " set it as a PATH in eclipse as env variable and bashrc but no luck 
@alshari86 : tried but no luck.

**Comment by jlipps** [comment]
if you open a mac terminal and type "ios-deploy", does it work?

**Comment by rgupta7888** [comment]
@jlipps 

Please see the logs after hitting ios-deploy on terminal:

"ios-deploy"
2017-06-09 23:33:04.194 ios-deploy[738:22614] Usage: ios-deploy [OPTION]...
  -d, --debug                  launch the app in lldb after installation
  -i, --id <device_id>         the id of the device to connect to
  -c, --detect                 only detect if the device is connected
  -b, --bundle <bundle.app>    the path to the app bundle to be installed
  -a, --args <args>            command line arguments to pass to the app when launching it
  -t, --timeout <timeout>      number of seconds to wait for a device to be connected
  -u, --unbuffered             don't buffer stdout
  -n, --nostart                do not start the app when debugging
  -I, --noninteractive         start in non interactive mode (quit when app crashes or exits)
  -L, --justlaunch             just launch the app and exit lldb
  -v, --verbose                enable verbose output
  -m, --noinstall              directly start debugging without app install (-d not required)
  -p, --port <number>          port used for device, default: dynamic
  -r, --uninstall              uninstall the app before install (do not use with -m; app cache and data are cleared) 
  -9, --uninstall_only         uninstall the app ONLY. Use only with -1 <bundle_id> 
  -1, --bundle_id <bundle id>  specify bundle id for list and upload
  -l, --list                   list files
  -o, --upload <file>          upload file
  -w, --download               download app tree
  -2, --to <target pathname>   use together with up/download file/tree. specify target
  -D, --mkdir <dir>            make directory on device
  -R, --rm <path>              remove file or directory on device (directories must be empty)
  -V, --version                print the executable version 
  -e, --exists                 check if the app with given bundle_id is installed or not 
  -B, --list_bundle_id         list bundle_id 
  -W, --no-wifi                ignore wifi devices
2017-06-09 23:33:04.198 ios-deploy[738:22614] [ !! ] One of -[b|c|o|l|w|D|R|e|9] is required to proceed!

**Comment by jlipps** [comment]
and what are the contents of the file `~/.bashrc`?

**Comment by rgupta7888** [comment]
@jlipps 

Please see the contents :

#!/bin/bash
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/cex/.sdkman"
[[ -s "/Users/cex/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/cex/.sdkman/bin/sdkman-init.sh"

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

# Setting PATH for Python 2.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export TESSDATA_PREFIX=“/Users/cex/tesseract-ocr”
export PATH=$PATH:/opt/local/bin#ADDED BY 010 EDITOR
export PATH="$PATH:/Applications/010 Editor.app/Contents/CmdLine"
export iosDeploy=“/usr/local/bin/ios-deploy”

**Comment by jlipps** [comment]
@rgupta7888 that last iosDeploy line won't do anything. it just puts that path into a local variable. do this instead at the end

```
export PATH="/usr/local/bin:$PATH"
```
