### ISSUE TITLE
Appium inspector can't start session

### ISSUE THREAD

**Issue by OpenKapija** [appium/appium-desktop#1989]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I can't start session in Appium inspector, I have depleted my time and will in search for the solution :( I believe it has something to do with apksigner but I don't know how to fix it...

Error message:

> Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\Ivan Filipović\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk'. Original error: Exception in thread "main" java.io.FileNotFoundException: C:\Users\Ivan Filipovic\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk (The system cannot find the path specified) at java.base/java.io.RandomAccessFile.open0(Native Method) at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344) at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:143) at com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:542) at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)

Log is attached 
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/8252502/appium-server-logs.txt)
## Environment

- I am running Appium Desktop version 1.22.2.
- I am on (pick one):
    - [x] Windows
    - [ ] Mac

**Comment by OpenKapija** [comment]
Reinstalled Inspector and now it is working.
