### ISSUE TITLE
Appium Server GUI 1.22.3 failed to start on macOS 12.3.1

### ISSUE THREAD

**Issue by DGandalf** [appium/appium-desktop#2024]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After having copied the App into the application directory.
The Appium Server GUI App crashes on every start

## Environment
macOS 12.3.1 (21E258)

- I am running Appium Desktop version 1.22.3.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

The crash-log locks as follows:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Could not get code signature for running application
at s (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/gui-common/util.js:44:15)
at Object.parcelRequire.oCSp../config (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/app/main/auto-updater/index.js:24:38)
at f (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:468)
at p (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:544)
at Object.parcelRequire.cWcu.../shared/settings (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/app/main/appium.js:10:1)
at f (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:468)
at p (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:544)
at Object.parcelRequire.epB2../configs/i18next.config (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/app/main.js:3:1)
at f (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:468)
at parcelRequire.Aj3S (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:771)
at Object.<anonymous> (/Applications/Appium Server GUI_22_3.app/Contents/Resources/app/dist/main.js:1:1023)
at Module._compile (internal/modules/cjs/loader.js:880:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
at Module.load (internal/modules/cjs/loader.js:735:32)
at Module._load (internal/modules/cjs/loader.js:648:12)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Object.<anonymous> (electron/js2c/browser_init.js:5806:12)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5813:30)
at __webpack_require__ (electron/js2c/browser_init.js:20:30)
at electron/js2c/browser_init.js:84:18
at electron/js2c/browser_init.js:87:10
at NativeModule.compile (internal/bootstrap/loaders.js:302:5)
at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:8)
at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
at Module._load (internal/modules/cjs/loader.js:630:15)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717

Nota Bene: I just changed the App name to install the different Versions of App Server GUI in the Application directory. ;-)
The crash also occurs with the original application name.

**Comment by amandaflagg** [comment]
I'm experiencing this same issue, running Monterrey v12.3 on a Macbook Pro.

**Comment by jamespizzurro** [comment]
Likewise! I'm also on macOS 12.3.1 (21E258). Reverting to Appium Server GUI 1.22.2 worked for me for now.

**Comment by jlipps** [comment]
same issue as https://github.com/appium/appium-inspector/issues/343. still waiting on the openjs foundation to get us an updated code signing certificate. until then you either need to sign it yourself (see the linked issue) or use an older version. 

cc @brianwarner

**Comment by amandaflagg** [comment]
> same issue as [appium/appium-inspector#343](https://github.com/appium/appium-inspector/issues/343). still waiting on the openjs foundation to get us an updated code signing certificate. until then you either need to sign it yourself (see the linked issue) or use an older version.
> 
> cc @brianwarner

thanks @jlipps, i was able to get it working by doing the manual signing referenced in that issue.

is it possible to get that documented on the appium server 1.22.3 release notes? i saw that it is in the mac os installation instructions, but for users who are just updating to a new version (like myself), that would be missed.

**Comment by DGandalf** [comment]
> Likewise! I'm also on macOS 12.3.1 (21E258). Reverting to Appium Server GUI 1.22.2 worked for me for now.

Yepp that's correct. But when you run scripts under iOS 15.4.1 on a real device then the getScreenshot command is broken.

And as stated in issue #2001  and #2002  @KazuCocoa wrote there : "Appium 1.22.3 supports it."

**Comment by KazuCocoa** [comment]
Did https://github.com/appium/appium-desktop/issues/2024#issuecomment-1098407474 not help your case?

https://github.com/appium/appium-inspector/issues/343#issuecomment-1070586278
Codesign in https://github.com/appium/appium-desktop#installing-on-macos

**Comment by DGandalf** [comment]
> Did [#2024 (comment)](https://github.com/appium/appium-desktop/issues/2024#issuecomment-1098407474) not help your case?
> 
> [appium/appium-inspector#343 (comment)](https://github.com/appium/appium-inspector/issues/343#issuecomment-1070586278) Codesign in https://github.com/appium/appium-desktop#installing-on-macos

Hi Kazu,

Please try to call codesign --deep --sign - /Applications/Appium\ Server\ GUI.app in case you gets a crash in the app starts.

Fixed the issue! Thanks a lot to point his out!
Please add this hint on a prominent place because the normal user only checks if there is a new version and installs it. As year long user you never scroll down and look there because normaly the installation process works in a perfect way.

Kind regards!!

**Comment by KazuCocoa** [comment]
Added a link in https://github.com/appium/appium-desktop/releases/tag/v1.22.3 a couple of hours ago

**Comment by DGandalf** [comment]
Perfect!

Thank you very much and a happy easter weekend !!!

Von: Kazuaki Matsuo ***@***.******@***.***>>
Datum Donnerstag, 14. Apr. 2022, 09:21
An: appium/appium-desktop ***@***.******@***.***>>
Cc: Paulmichl, Dominik ***@***.******@***.***>>, Author ***@***.******@***.***>>
Betreff: Re: [appium/appium-desktop] Appium Server GUI 1.22.3 failed to start on macOS 12.3.1 (Issue #2024)

EXTERNAL SENDER: Do not click any links or open any attachments unless you trust the sender and know the content is safe.
EXPÉDITEUR EXTERNE: Ne cliquez sur aucun lien et n’ouvrez aucune pièce jointe à moins qu’ils ne proviennent d’un expéditeur fiable, ou que vous ayez l'assurance que le contenu provient d'une source sûre.


Added a link in https://github.com/appium/appium-desktop/releases/tag/v1.22.3<https://urldefense.com/v3/__https://github.com/appium/appium-desktop/releases/tag/v1.22.3__;!!AaIhyw!8Mx_bUCgLwIz1MtRm81pYk8vNXLO8TlyXWKVNG0QxTK2B9jesAGykIxyi-sQlkDTCkY9$> a couple of hours ago

**Comment by AshwinNandhakumar** [comment]
> Added a link in https://github.com/appium/appium-desktop/releases/tag/v1.22.3 a couple of hours ago

Getting this below error. 
Uncaught Exception:
Error: Could not get code signature for running application
at s (/Applications/Appium Server GUI.app/Contents/Resources/app/gui-common/util.js:44:15)
at Object.parcelRequire.oCSp../config (/Applications/Appium Server GUI.app/Contents/Resources/app/app/main/auto-updater/index.js:24:38)
at f (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:468)
at p (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:544)
at Object.parcelRequire.cWcu.../shared/settings (/Applications/Appium Server GUI.app/Contents/Resources/app/app/main/appium.js:10:1)
at f (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:468)
at p (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:544)
at Object.parcelRequire.epB2../configs/i18next.config (/Applications/Appium Server GUI.app/Contents/Resources/app/app/main.js:3:1)
at f (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:468)
at parcelRequire.Aj3S (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:771)
at Object.<anonymous> (/Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js:1:1023)
at Module._compile (internal/modules/cjs/loader.js:880:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
at Module.load (internal/modules/cjs/loader.js:735:32)
at Module._load (internal/modules/cjs/loader.js:648:12)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Object.<anonymous> (electron/js2c/browser_init.js:5806:12)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5813:30)
at __webpack_require__ (electron/js2c/browser_init.js:20:30)
at electron/js2c/browser_init.js:84:18
at electron/js2c/browser_init.js:87:10
at NativeModule.compile (internal/bootstrap/loaders.js:302:5)
at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:8)
at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
at Module._load (internal/modules/cjs/loader.js:630:15)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)

**Comment by Mahmoud-Nabuwi** [comment]
I have the same issue.. any help

**Comment by kolenj** [comment]
help, I have the same issue...too

**Comment by KazuCocoa** [comment]
Did you attempt all of https://github.com/appium/appium-desktop#installing-on-macos ?
