### ISSUE TITLE
An unexpected error occurred with message: Need to implement 'codeFor_status()': undefined.

### ISSUE THREAD

**Issue by qa-inho-song** [appium/appium-desktop#2146]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [v ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Unhandled Exception
An unexpected error occurred with message: Need to implement 'codeFor_status()': undefined.
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
Error: Need to implement 'codeFor_status()': undefined
    at o.getCodeString (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:20:903)
    at m.code (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:142:1275)
    at m.render (file:///Applications/Appium%20Inspector.app/Contents/Resources/app.asar/dist/renderer.e31bb0bc.js:142:2696)
    at finishClassComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
    at updateClassComponent (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
    at beginWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
    at HTMLUnknownElement.callCallback (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
    at performUnitOfWork (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
    at workLoopSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
    at renderRootSync (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
    at performSyncWorkOnRoot (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
    at /Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11327:26
    at unstable_runWithPriority (/Applications/Appium Inspector.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468:12)
## Environment

- I am running Appium Desktop version _<2022.11.1 appium inspector>_.
- I am on (pick one):
    - [v ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
Use https://github.com/appium/appium-inspector instead
