### ISSUE TITLE
original error: unknown device or simulator udid ...   i am just trying to start session first .. but the session is not starting....what maybe the problem

### ISSUE THREAD

**Issue by sarozNep** [appium/appium-desktop#258]
@jlipps 
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:e
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40 
[HTTP] --> DELETE /wd/hub/session {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 2 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/xx/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app","deviceName":"iphone 6s","noReset":true,"platformName":"iOS","platformVersion":"10.2","udid":"FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/xx/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app","deviceName":"iphone 6s","noReset":true,"platformName":"iOS","platformVersion":"10.2","udid":"FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1501256955247 (16:49:15 GMT+0100 (WEST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/XX/Desktop/ios-uicatalog-master/Build/Products/Debug-iphonesimulator/UICatalog.app'
[Appium]   deviceName: 'iphone 6s'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   udid: 'FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: fb5f9c45-1b5a-40b4-a993-70911a07f034
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1501256955314 (16:49:15 GMT+0100 (WEST))
[XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 'FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59'
    at XCUITestDriver.determineDevice$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unknown device or simulator UDID: 'FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59'
    at XCUITestDriver.determineDevice$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: 'FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59'
    at XCUITestDriver.determineDevice$ (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:604:17)
    at tryCatch (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gm/49c1hvk93b91915wrh1lr95m0000gp/T/AppTranslocation/E3CEE5CC-E927-4FC2-B0BE-1AC91D59D1D8/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 274 ms - 208

**Comment by jlipps** [comment]
The error message is clear:

> [XCUITest] Error: Unknown device or simulator UDID: 'FBA5F1DB-19F2-4ED5-AA2F-AD24CFF9B59' at XCUITestDriver.determineDevice$ 

If you don't need to specify a simulator udid, then remove the udid capability.

**Comment by sarozNep** [comment]
@jlipps  if i remove UDID the error is sdk '10.2' was not in the list of simctl sdks ...and so i put 10.3 for the available device it doesnt work

**Comment by jlipps** [comment]
This is not an appium desktop issue. It's either an appium issue or an issue with your environment. I recommend going to the forums (discuss.appium.io) to ask for help, and submitting an issue to the appium repository with repro information if you can't find help on the forums.

**Comment by sarozNep** [comment]
Thank you so much ...the problem is solved and i am using it now :) ..i will post the issue if i get it..

Regards 

Saroj Duwadi

**Comment by pankajpat2014** [comment]
@sarozNep how you resolved the issue ? I am facing similar issue. Please help
