### ISSUE TITLE
unable to launch iOS App in real device Error thrown on running java code from windows machine to launch iOS in mac machine "A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank, (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by findmanish** [appium/appium-desktop#293]
## The problem
unable to launch app as
Error thrown on running java code from windows machine to launch iOS in mac machine "A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank, (WARNING: The server did not provide any stacktrace information)

## Environment

    - [ ] Mac
    - [ ] Windows

**Comment by jlipps** [comment]
please link to a gist of your appium log

**Comment by findmanish** [comment]
@jlipps Please find the logs

The server is running

[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 192.168.187.76
[Appium] Appium REST http interface listener started on 192.168.187.76:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","browserName":"IOS","newCommandTimeout":300}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","browserName":"IOS","newCommandTimeout":300},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1505465945733 (16:59:05 GMT+0800 (HKT))
[Appium] Creating new IosDriver (v1.24.1) session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   browserName: 'IOS'
[Appium]   newCommandTimeout: 300
[iOS] IosDriver version: 1.24.1
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,
    at IosDriver.validateDesiredCaps (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:155:25)
    at IosDriver.validateDesiredCaps (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:52:16)
    at IosDriver.callee$0$0$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:23:8)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as createSession] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
    at IosDriver.createSession$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:52:16)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.createSession (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/build/lib/driver.js:202:34)
    at AppiumDriver.createSession$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:183:43)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/appium.js:307:34)
    at /private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:207:24
    at tryCatcher (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
 { SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s):  deviceName can't be blank,
    at IosDriver.validateDesiredCaps (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:155:25)
    at IosDriver.validateDesiredCaps (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:52:16)
    at IosDriver.callee$0$0$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:23:8)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as createSession] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/build/lib/basedriver/commands/session.js:35:30)
    at IosDriver.createSession$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/lib/driver.js:52:16)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.createSession (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-driver/build/lib/driver.js:202:34)
    at AppiumDriver.createSession$ (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:183:43)
    at tryCatch (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at Promise.F (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at AppiumDriver.createSession (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/appium.js:307:34)
    at /private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:207:24
    at tryCatcher (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/private/var/folders/k0/pn8b2yyd3vzc23ckxycn0htc0000gn/T/AppTranslocation/BD352D7C-FEE0-46A8-A481-B34EFB784589/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 199 ms - 199

**Comment by findmanish** [comment]
@jlipps on debugging in eclipse it returns with correct device name

**Comment by jlipps** [comment]
@findmanish the error is clear in the logs: you did not start a session with a `deviceName` capability. add an appropriate `deviceName` capability. See the appium capability docs for more instruction. Also, `browserName: iOS` is not valid. Don't send in a browserName capability.

**Comment by svetikshark** [comment]
having same problem as latest grid hub running selenium 3.6.0 or 3.5.3 -doesn't matter - throws error when trying to send capabilities from c# code with capabilities.SetCapability("deviceName","iPhone 6")

the error on hub is 
java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [deviceName]

**Comment by svetikshark** [comment]
managed to run appium without specifying device name in capabilities with command
node /usr/local/bin/appium -p 4733 --log-timestamp --nodeconfig /Users/qa/Downloads/appium_node_4723.json --log /Users/qa/Downloads/log/appium_node_4723.log --default-capabilities '{"deviceName":"iPhone 6",  "automationName": "XCUITest"}'

and capabilities are set as follows

DesiredCapabilities capabilities = new DesiredCapabilities(new Dictionary<string, object>
            {
                {"browserName", "safari"},
                {"platformName", "iOS"},
                {"version", "10.3"},
           });
            return capabilities;

The issue now that I can't start ipad at the same instance of appuim
