### ISSUE TITLE
On Opening macaca inspector for iOS App, web page shows internal server error

### ISSUE THREAD

**Issue by findmanish** [appium/appium-desktop#296]
## Appium 

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## iPhone
##Mac

    - [ ] Mac
   Error Log

undefined
>> iOS device started: c10dbb4c75c4b05f97b41d486bcfdc28be3f81da
>> inspector start at: http://192.168.187.76:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1020:11)
      at exports._exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1020:11)
      at exports._exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1020:11)
      at exports._exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

 

^[
clear
macaca doctor
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1020:11)
      at exports._exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by jlipps** [comment]
Appium Desktop has nothing to do with Macaca. Please ask that project for help.
