### ISSUE TITLE
Xcode 9 Not Supported Error, Creating Sim Builds on Xcode 8.3.3

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium-desktop#302]
## Appium or Appium Desktop?
Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
Creating iPad sim build to test on AppiumDesktop 
Using Xcode 8.3.3 to build version of ipad app for testing, but when I put the file in appium desktop capability sets and start session I get the error the Xcode 9 is not supported. Where could error be coming from if I don't even have xcode 9?

## Environment

- I am running Appium Desktop version _Version 1.2.0-beta.3 (1.2.0-beta.3)_.
- I am on (pick one):
    - [ x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment]
please send in the full set of logs from the console window

**Comment by alexttransisland** [comment]
```
[XCUITest] Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
For me

**Comment by havenqi** [comment]
I think I had the same issue, I can attach what I got for quick reference. 
Appium Desktop: 1.2.1 (the latest from github), Xcode is version 9.

![image](https://user-images.githubusercontent.com/11476671/30794295-eeb8ceaa-a1f9-11e7-8bea-9f236e5d1c95.png)

Then I initiated a session by clicking "Start Inspector Session" on the GUI

`[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 12 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/QArt/AB/App/iOS/HisunPay_sit.ipa","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/QArt/AB/App/iOS/HisunPay_sit.ipa","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1506319263157 (14:01:03 GMT+0800 (CST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/QArt/AB/App/iOS/HisunPay_sit.ipa'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 0d428be8-f6cd-4678-bc8c-4259486270ca
[XCUITest] Xcode version set to '9.0' (tools v9.0.0.0.1.1504363082)
[XCUITest] iOS SDK Version set to '11.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1506319263510 (14:01:03 GMT+0800 (CST))
[XCUITest] Changing deviceName from 'iPhone Simulator' to 'iPhone 6'
[XCUITest] Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/QArt/Tools/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 2058 ms - 175 `

**Comment by alexttransisland** [comment]
XCode updates _automatically_, but Appium doesn't support it yet. Not sure it's an issue, but more like new feature to me. I did the following:
1) Uninstall current version of XCode
2) Open https://developer.apple.com/download/more/?name=Xcode
3) Download `xpi` for `8.3.3`
4) Install `xpi`
5) Move XCode to `Applications`
6) Restart your OS machine
7) Run Appium Server. Run XCode. Enjoy!
8) _Don't upgrade XCode to newer version_
9) _Wait for Appium to release support for XCode 9.0 and then update XCode to 9.0_.

**Comment by saikrishna321** [comment]
xcode-9 support you need appium 1.7.0

**Comment by mojojojo94** [comment]
```
[Appium] Welcome to Appium v1.6.5
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/ysxw055/Downloads/Grainger-iPad_3.2.zip","automationName":"XCUITest","connectHardwareKeyboard":true,"deviceName":"iPad Pro","platformName":"iOS","platformVersion":"9.3","sendKeyStrategy":"setValue","showIOSLog":true,"newCommandTimeout":0}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ysxw055/Downloads/Grainger-iPad_3.2.zip","automationName":"XCUITest","connectHardwareKeyboard":true,"deviceName":"iPad Pro","platformName":"iOS","platformVersion":"9.3","sendKeyStrategy":"setValue","showIOSLog":true,"newCommandTimeout":0},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1506444402117 (11:46:42 GMT-0500 (CDT))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/ysxw055/Downloads/Grainger-iPad_3.2.zip'
[Appium]   automationName: 'XCUITest'
[Appium]   connectHardwareKeyboard: true
[Appium]   deviceName: 'iPad Pro'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   sendKeyStrategy: 'setValue'
[Appium]   showIOSLog: true
[Appium]   newCommandTimeout: 0
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 1d8ad2cb-8fe9-4843-be1c-fc40efddfb53
[XCUITest] Xcode version set to '9.0' (tools v9.0.0.0.1.1504363082)
[XCUITest] iOS SDK Version set to '11.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1506444402216 (11:46:42 GMT-0500 (CDT))
[XCUITest] Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[MJSONWP] Encountered internal error running command: Error: Xcode version 9.0 is not yet supported
    at handleUnsupportedXcode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:16:11)
    at getSimulator$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-simulator/lib/simulator.js:28:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 385 ms - 175 
Appium server stopped successfully
```

**Comment by imurchie** [comment]
Appium 1.6.5 was released _before_ Xcode 9. It does not know anything about it. You need to upgrade to Appium 1.7.0.

**Comment by lodicolo** [comment]
I have two installations of appium, one global and one local to the project, and both of them are 1.7.1. I have the latest appium-desktop installed (1.2.2) and as you can see appium-desktop still wants me to start v1.6.5:
![schermata 2017-09-28 alle 11 09 20 am](https://user-images.githubusercontent.com/1476550/30974379-87f34f24-a43d-11e7-908b-c7791b13fda3.png)

and near as I can tell it is still starting v1.6.5, I assume from its own copy of Appium:
![schermata 2017-09-28 alle 11 12 30 am](https://user-images.githubusercontent.com/1476550/30974556-eedb54c0-a43d-11e7-8348-ebe8a0da7103.png)

I end up getting the same errors as @mojojojo94 and @havenqi.
<img width="441" alt="schermata 2017-09-28 alle 11 13 45 am" src="https://user-images.githubusercontent.com/1476550/30974643-2167543e-a43e-11e7-82d2-b480e59971d2.png">

**Comment by dejavu969** [comment]
@lodicolo 
looks like the appium GUI (1.2.2) doesn't support Xcode 9. There is 1.2.3 in works. hopefully that works for Xcode9.
https://github.com/appium/appium-desktop/releases/tag/v1.2.3

**Comment by mojojojo94** [comment]
@dejavu969 I npm uninstall -g appium and npm install -g appium in command line to update to appium v1.7.1, appium version shows up as 1.7.1 in command line when I run appium --version but Appium Desktop still shows v1.6.5. Should I replace my current appium desktop version with appium desktop 1.2.2 for now? Anyone else here can answer this question?

**Comment by dejavu969** [comment]
@mojojojo94 As per my understanding the appium desktop(1.2.2) is not yet ready for Xcode 9. I tried and i can still see Appium v1.6.5. Irrespective of the version your desired capabilities should point to the Xcode version and Iphone device version. v1.2.3 must have the fix and i still need to verify that once its comes out.

**Comment by jlipps** [comment]
Appium is bundled with Appium Desktop and there hasn't been a release of Appium Desktop since Appium 1.7.1 was released. @dpgraham will be doing that soon. However this is not a blocker for anyone. If you have Appium 1.7.1 on the command line, you can simply run it, then attach to it as a custom server in the new session window. The inspector can be run against any Appium server, not only the one bundled with Appium Desktop.

**Comment by jlipps** [comment]
To answer the original question: @mojojojo94 it looks like your xcode was indeed upgraded, even if you didn't do it intentionally. You can go to your Apple developer account and download an old version if you want to stick with 8.
