### ISSUE TITLE
Unable to Launch app on real device Error:Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

### ISSUE THREAD

**Issue by findmanish** [appium/appium-desktop#338]
Getting this error when running on real Device
WebdriverAgent is build successfully with correct provisioning profile.
Neither WebDriverApp is being installed when WebDriverAgent gets succeeded on real device. 

Logs 
https://gist.github.com/findmanish/bfb903f5fc9ffbb6faebec1142893ae3

**Comment by dpgraham** [comment]
Can you set the capability `showXcodeLog = true` and repost the gist.

**Comment by chanugithub** [comment]
@findmanish did you resolve this issue, i am getting same exact error
{code}
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[debug] [XCUITest] 'pgrep -nif xcodebuild.*8aac5844172ab9be5989a408b784bddb3e735ae8' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:395:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[HTTP] <-- POST /wd/hub/session 500 23568 ms - 470 

===============================================
Envrmnt Suite
Total tests run: 13, Failures: 0, Skips: 13
Configuration Failures: 1, Skips: 0
===============================================
{code}

**Comment by findmanish** [comment]
@chanugithub  No.Not yet...Still facing

**Comment by chanugithub** [comment]
@findmanish okay please Let me know if you resolve it, thanks

**Comment by chanugithub** [comment]
@findmanish Finally i was able to find the solution, it was actually Apple certificates in key chain access which now i set to 'system default' and previously it was in 'Always trust' mode, are you able to resolve it, let me know there is another workaround too

**Comment by okankurtulus** [comment]
Hi, I'm experiencing the exact same error. I've checked all my certificates and confirmed all were already `system default`. So there should be some other reason. Please let me know if you have any idea?

**Comment by poonam26sg** [comment]
Hi,

Even I am facing same error though I have checked all certificates and all of them are **system default** . Please let me know if there is any alternative solution for this issue.

**Comment by okankurtulus** [comment]
Hi, here is how I've solved the issue:
1. Go to Applications/Appium from Finder
2. RightClick Appium and select `Show Package Contents`
3. Then navigate to `Contents\Resources\app\node_modules\appium\node_modules/appium-xcuitest-driver/WebDriverAgent`
4. There you will see `WebDriverAgent.xcodeproj` file
5. Open it and fix signing issues. Fix the signing so that this app should be able to installed on real device
6. Then close all and retry Appium. It should work now

In my case the error "code 65" is raised for `WebDriverAgent` not my bundle, but I lost so much time because I all thought the signing issue is with my bundle

**Comment by smrutiv** [comment]
It took me forever to figure this out! Thanks to @okankurtulus it was these steps above helped me run. in my case the error code 65 was raised for WebDriverAgent not my bundle. We need a different error code to let others know.

**Comment by smrutiv** [comment]
HI @girishh143 

Did you try above steps from @okankurtulus ? If not please try to go to that folder  (webdriverAgent) and then run the xcode first and then go to terminal and run the command from where the WebdriverAgent is located. 

If it is still not working then make sure you are not copying the command and paste it to terminal. It does not recognize the single quote when copied and pasted. 

For eg: the above command you have given has double quotes after test ("xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=XXXXd938649f9640a0460d10c93ae95bcddee857' test") Please remove those quotes it should be just -$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=XXXXd938649f9640a0460d10c93ae95bcddee857' test. After you remove the double quotes make sure the single quotes are typed not copied. 

Hope you will get it run. Good luck.

**Comment by girishh143** [comment]
@smrutiv :  I have done the singing in xcode, also created the certificate, also added it in key-chain but still i am getting the  same error.
Note: I am using the Hybrid app is there any special setting for it ?
