### ISSUE TITLE
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null,Unhandled rejection Error: UiAUtomator shut down unexpectedly

### ISSUE THREAD

**Issue by chenzheng102** [appium/appium-desktop#358]
appium1.7.1
Execute the script, throw out the exception:
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
Unhandled rejection Error: UiAUtomator shut down unexpectedly
    at AndroidBootstrap.callee$2$0$ (../../lib/bootstrap.js:161:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:185:17)
    at Promise (<anonymous>)
    at F (/usr/local/lib/node_modules/appium/node_modules/_core-js@1.2.7@core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/_babel-runtime@5.8.24@babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator.callee$2$0 (../../lib/bootstrap.js:158:62)
    at emitOne (events.js:115:13)
    at UiAutomator.emit (events.js:210:7)
    at UiAutomator.changeState (../../lib/uiautomator.js:85:10)
    at SubProcess.<anonymous> (../../lib/uiautomator.js:47:14)
    at emitTwo (events.js:125:13)
    at SubProcess.emit (events.js:213:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:233:14)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by dpgraham** [comment]
Try again with latest version
