### ISSUE TITLE
[AndroidDriver] Error: Could not find package app-debug.apk on the device     at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)

### ISSUE THREAD

**Issue by iamabhiram** [appium/appium-desktop#359]
Appium Desktop

[info] [Appium] Welcome to Appium v1.7.1
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium]   port: 4725
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4725[info] [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"capabilities":{"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},null,{"desiredCapabilities":{"app":"app-debug.apk","appActivity":"com.xfactory.in.activity.SplashActivity","appPackage":"com.xfactory.in","deviceName":"Android Emulator","platformName":"Android"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1512471463420 (16:27:43 GMT+0530 (India Standard Time))
[info] [Appium] Creating new AndroidDriver (v1.28.1) session
[info] [Appium] Capabilities:
[info] [Appium]   app: 'app-debug.apk'
[info] [Appium]   appActivity: 'com.xfactory.in.activity.SplashActivity'
[info] [Appium]   appPackage: 'com.xfactory.in'
[info] [Appium]   deviceName: 'Android Emulator'
[info] [Appium]   platformName: 'Android'
[info] [BaseDriver] Session created with session id: 82d38339-f68a-4d30-9cc6-2f543e2b70f0
[debug] [AndroidDriver] Getting Java version[info] [AndroidDriver] Java version is: 1.8.0_144
[info] [ADB] Checking whether adb is present[debug] [ADB] 1 device(s) connected
[info] [AndroidDriver] Using device: emulator-5554
[info] [ADB] Checking whether adb is present
[info] [ADB] Using adb.exe from C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[info] [AndroidDriver] App file was not listed, instead we're going to run app-debug.apk directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","app-debug.apk"]
[error] [AndroidDriver] Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[debug] [ADB] Getting connected devices...[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\XXXXXX\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"][debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[error] [MJSONWP] Encountered internal error running command: Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)
    at AndroidDriver.checkPackagePresent$ (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:392:11)
    at tryCatch (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\XXXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[info] [HTTP] <-- POST /wd/hub/session 500 1203 ms - 187 

## The problem

[AndroidDriver] Error: Could not find package app-debug.apk on the device
    at Object.wrappedLogger.errorAndThrow (C:\Users\XXXXX\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:63:13)

[MJSONWP] Encountered internal error running command: Error: Could not find package app-debug.apk on the device

## Environment

- I am running Appium Desktop version _<1.7.1>_.
- I am on (pick one):
 
    - [ ] Windows

**Comment by anandsumit** [comment]
Facing same issue.
