### ISSUE TITLE
  Getting error for Xcode version

### ISSUE THREAD

**Issue by Arthikuppusamy** [appium/appium-desktop#370]
Getting error for Xcode version while running Appium desktop server.

**Appium desktop version: 1.2.7
Xcode: 8.3.3**

After starting Appium desktop server, running code from eclipse gives error as below
```
[Appium] Welcome to Appium v1.7.1 
[Appium] Appium REST http interface listener started on 0.0.0.0:4723 [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/cyranosystems/Desktop","automationName":"XCuiTest","deviceName":"iPhone 6","platformName":"iOS"},"capabilities":{"desiredCapabilities":{"app":"/Users/cyranosystems/Desktop","automationName":"XCuiTest","deviceName":"iPhone 6","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}} 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/cyranosystems/Desktop","automationName":"XCuiTest","deviceName":"iPhone 6","platformName":"iOS"},null,{"desiredCapabilities":{"app":"/Users/cyranosystems/Desktop","automationName":"XCuiTest","deviceName":"iPhone 6","platformName":"iOS"},"firstMatch":[{"platformName":"ios"}]}] 
[BaseDriver] Event 'newSessionRequested' logged at 1513761563065 (14:49:23 GMT+0530 (IST)) 
[Appium] Creating new XCUITestDriver (v2.51.1) session 
[Appium] Capabilities: 
[Appium] app: '/Users/cyranosystems/Desktop' 
[Appium] automationName: 'XCuiTest' 
[Appium] deviceName: 'iPhone 6' 
[Appium] platformName: 'iOS' 
[BaseDriver] Session created with session id: 42f492ef-0c1a-4baf-a048-71f36b1d5c31 
[XCUITest] Error: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at getVersionWithoutRetry$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcode/lib/xcode.js:116:11) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) Error: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at getVersionWithoutRetry$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcode/lib/xcode.js:116:11) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) [XCUITest] Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at Object.wrappedLogger.errorAndThrow (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13) at getAndCheckXcodeVersion$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:51:9) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at Object.wrappedLogger.errorAndThrow (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13) at getAndCheckXcodeVersion$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:51:9) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) [XCUITest] Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at Object.wrappedLogger.errorAndThrow (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13) at getAndCheckXcodeVersion$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:51:9) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at Object.wrappedLogger.errorAndThrow (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13) at getAndCheckXcodeVersion$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:51:9) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on. [MJSONWP] Encountered internal error running command: Error: Could not determine Xcode version: Could not get Xcode version. /Library/Developer/Info.plist does not exist on disk. at Object.wrappedLogger.errorAndThrow (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:63:13) at getAndCheckXcodeVersion$ (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:51:9) at tryCatch (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Users/cyranosystems/Desktop/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) 
[HTTP] <-- POST /wd/hub/session 500 38 ms - 254 
 [HTTP] --> GET /wd/hub/sessions {} 
[MJSONWP] Calling AppiumDriver.getSessions() with args: [] 
[MJSONWP] Responding to client with driver.getSessions() result: [] 
[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40
```

**Comment by dpgraham** [comment]
This StackOverflow page may be of assistance to you: https://stackoverflow.com/questions/32724616/appium-error-could-not-get-xcode-version
