### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Command 'java' not found. Is it installed?

### ISSUE THREAD

**Issue by 1228337123** [appium/appium-desktop#386]
## The problem
After I installed Appium Desktop, it runs OK. But after I closed it and reopened, it reports ERROR when I start session:

[MJSONWP] Encountered internal error running command: Error: Command 'java' not found. Is it installed?

## Environment
Win7 X64; java version "1.8.0_144"; Appium Desktop1.3.1

---------------------------------
[BaseDriver] Session created with session id: 8cec1c36-406b-430f-a706-c1e0d92da801
[AndroidDriver] Getting Java version
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: Command 'java' not found. Is it installed?
    at ChildProcess. (C:\Users\Administrator\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\teen_process\lib\teen_process.js:42:14)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by superMaster007** [comment]
how are you fixed it ? I get this error also

**Comment by superMaster007** [comment]
@1228337123

**Comment by Sudhakar-Gandikota** [comment]
Hello, have you find the solution for above issue?
