### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Invalid Version: android-8.1.0

### ISSUE THREAD

**Issue by rrandoom** [appium/appium-desktop#451]
```
 [Appium] Creating new AndroidDriver (v1.37.0) session
[Appium] Capabilities:
[Appium]   appActivity: .Calculator
[Appium]   appPackage: com.meizu.flyme.calculator
[Appium]   automationName: appium
[Appium]   deviceName: note2
[Appium]   platformName: Android
[Appium]   platformVersion: 5.1
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: b0b2ecc1-e624-4701-b445-4d410df8b32e
[AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_144
[ADB] Checking whether adb is present
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: TypeError: Invalid Version: android-8.1.0
    at new SemVer (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:293:11)
    at compare (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:566:10)
    at rcompare (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\semver\semver.js:576:10)
    at Array.sort (native)
    at Array.sort (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\webpack:\~\core-js\modules\es6.array.sort.js:21:1)
    at ADB.callee$0$0$ (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:89:17)
    at tryCatch (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\xl\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at 
## Environment
```

- I am running Appium Desktop version 1.4
- I am on (pick one):
    - [ ] Mac
    - [1] Windows

**Comment by dpgraham** [comment]
It's not supported on that automation. Try setting `automationName=UiAutomator2`.

**Comment by rrandoom** [comment]
i resolved the problem , in that folder  %ANDROID_HOME% /build-tools  ,rename a folder :    android-8.1.1   >>> 28.0.1
