### ISSUE TITLE
\AppData\Local\SquirrelTemp\RELEASES does not exist, something is probably broken with your application

### ISSUE THREAD

**Issue by nnTasha** [appium/appium-desktop#519]
Appium Desktop

Unablle to install Appium Desktop version 1.5.0
appium-desktop-Setup-1.5.0-ia32.exe and run the follow error is displayed 

...\AppData\Local\SquirrelTemp\RELEASES does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()

- I am running Appium Desktop version 1.5.0
- I am on (pick one):

    - [ ] Windows

**Comment by dpgraham** [comment]
Which version of Windows is it and is it 32 bit or 64 bit Windows?

**Comment by dpgraham** [comment]
Also, are you running McAfee anti-virus? That's known to cause some installation issues for Electron apps.

**Comment by dpgraham** [comment]
@nnTasha I just created a new bundle https://github.com/appium/appium-desktop/releases/tag/v1.5.0

It's called Appium.Web.Setup.1.6.0.exe

I think this should resolve the problems.

**Comment by nnTasha** [comment]
Hi Dan,
Thank you for the response.
I'm on 64 bit Windows without McAfee
I'll check this new bundle and get back to you soon with any update

**Comment by dpgraham** [comment]
Try this one instead, it's more up-to-date: https://github.com/appium/appium-desktop/releases/download/v1.6.1/appium-desktop-setup-1.6.1.exe

**Comment by nnTasha** [comment]
It works ! :)

thanks a lot Dan
