### ISSUE TITLE
Appium-uiautomator2-server-v1.9.1.apk file doesn't exist

### ISSUE THREAD

**Issue by hardworking4u** [appium/appium-desktop#559]
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I run test in my computer that installed appium-desktop-1.6.1-x86_64.AppImage，and found it suggests appium-uiautomator2-server-v1.9.1.apk file doesn't exist .The crash information in console as shown below：

![2018-06-05 15-36-52](https://user-images.githubusercontent.com/19179585/40962119-35d30fb8-68d7-11e8-8864-a3ce3231c89b.png)
     So I check the file in appium-desktop workspace,found the target application does not exist
,and the directory has only read-only permissions,I can not do anything to fix the problem.

![2018-06-05 16-00-40](https://user-images.githubusercontent.com/19179585/40963037-ecb28342-68d9-11e8-9e5c-15629b6d3a46.png)

   I spent a lot of time and can not solve this problem, have to submit issues hope to get your help,thank you!

## Environment

- I am running Appium Desktop-1.6.1-x86_64.AppImage.
- I am on (pick one):
    - [x] Linux

**Comment by dpgraham** [comment]
Alright, I finally published a new version. Sorry for the delay.

Can you try the latest: https://github.com/appium/appium-desktop/releases/latest

**Comment by rivaldi8** [comment]
It seems the Linux Appimage file is missing or at least I can't see it.

**Comment by dpgraham** [comment]
Alright @rivaldi8 I republished it. Let me know if that error still happens.

**Comment by rivaldi8** [comment]
Thanks @dpgraham, this issue seems to be fixed now. However, there's another problem now. It fails with this error:
```
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar.
Original error: Command '/home/alex/local-apps/android-sdk/build-tools/27.0.3/apksigner sign --key /tmp/.mount_appium6rOPCU/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.pk8 --cert /tmp/.mount_appium6rOPCU/app/resources/app/node_modules/appium/node_modules/appium-adb/keys/testkey.x509.pem /tmp/.mount_appium6rOPCU/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileSystemException: /tmp/.mount_appium6rOPCU/app/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.12.0.apk: Read-only file system
```
Although it looks similar to #327, this issue seems more related to the fact that the Appimage runs in read-only file system. Should I open a new issue?

**Comment by dpgraham** [comment]
@rivaldi8 Can you try running Appium from the terminal

```
npm install -g appium
appium
```

And then pointing a session to it by navigating to `Custom` and then inputting `localhost` as the host and `4723` as the port?

If it still happens when you do that, then we can rule it out as an Appium Desktop error and it's probably either an Appium issue or an environment issue.

**Comment by hardworking4u** [comment]
I've tried and it works properly

**Comment by atiyasuhail** [comment]
I installed Appium using the following exe file
 appium-desktop-setup-1.6.2.exe
I get the error appium-ui-automator2-server-v.12.0.apk file does not exist.
I drilled down to the folder and found the file is not there.
Please help

**Comment by dpgraham** [comment]
@hardworking4u @atiyasuhail I'm going to dig into this today. In the meantime, a good workaround is to just install and run Appium from command line:

```
npm install -g appium
appium .
```

And then run sessions by opening the inspector window (Ctrl/Cmd + N) and using `Custom Server`.

**Comment by dpgraham** [comment]
@atiyasuhail I just tried re-building it and the apk is there now.

Can you try the appImage again? https://github.com/appium/appium-desktop/releases/download/v1.6.2/appium-desktop-1.6.2-x86_64.AppImage

**Comment by sevetseh28** [comment]
The same is happening to me on Linux Mint 19 and running appium from command line.

**Comment by nikuldoutest** [comment]
I am getting below error for some reason. It was working fine til a day before. Suddenly, started showing an error.

I got this error on Appium Desktop Application 1.6.2 while running inspector. Not able to start Appium inspector.

Any solution for below error??

"Error

> An unknown server-side error occurred while processing the command. Original error: C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk file doesn't exist.


[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[ADB] Running 'C:\Users\OHM\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.propdispatch.pdnextgen'
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\OHM\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[ADB] Running 'C:\Users\OHM\AppData\Local\Android\sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\OHM\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[BaseDriver] Event 'newSessionStarted' logged at 1534008104625 (11:21:44 GMT-0600 (Mountain Daylight Time))
[MJSONWP] Encountered internal error running command: Error: C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.12.0.apk file doesn't exist.
[MJSONWP]     at ADB.callee$0$0$ (C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:61:11)
[MJSONWP]     at tryCatch (C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (C:\Users\OHM\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 2474 ms - 339
[HTTP]

**Comment by dpgraham** [comment]
Is this happening for anyone on 1.6.3? (https://github.com/appium/appium-desktop/releases/tag/v1.6.3)

**Comment by CalvinRodo** [comment]
This error is occurring for 1.15.1

**Comment by CalvinRodo** [comment]
Sorry it was version 1.7.1, my dev reinstalled using Windows installer and it fixed the issue.

I guess she ran appium desktop as admin in an effort to fix an issue with an unsigned apk and it deleted the apk.

**Comment by Peridactite** [comment]
I am experiencing this on 1.6.1 Appium Desktop with Windows 7. 
Unrelated:
The only reason I'm not using the console is because I cannot seem to past sqlite3 bug. Even installed sqlite3 separately (and successfully) but Appium still fails with sqlite3 errors.
