### ISSUE TITLE
 handset server: server is busy processing another request [/appiumModeStop]

### ISSUE THREAD

**Issue by c5253606** [appium/appium-desktop#592]
When we are trying to run the different scenarios in different devices at the same time we are getting this issues. if in one device the execution completes, then in other device the execution in other device is  aborting, 
We attached the log files as well, 

Aug 07, 2018 1:32:48 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.xpath: //*[@id='mainShell-header-hdr-begin']//*[@class='sapUiUfdShellHeadContainer']//span)
org.openqa.selenium.WebDriverException: Failed to execute command webpage.element find: findElements command failed. Reason: handset server: server is busy processing another request [/appiumModeStop]
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'INLN50940147A', ip: '10.52.99.0', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver
Capabilities [{reportPdfUrl=https://sap.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=khyathi.konala@sap.com_RemoteWebDriver_18-08-07_07_58_06_557&_timestamp[0]=1533628686792, eclipseExecutionId=khyathi.konala@sap.com_Eclipse_18-08-07_06_16_00_511, simpleIsVisibleCheck=true, deviceName=8753C71DE4EF26B55B14A739F678F7F8FB4F0BF6, platform=IOS, password=, deviceSessionId=55C47182A39902C219670DCD4F5354F5, driverClass=io.appium.java_client.ios.IOSDriver, automationName=Appium, host=sap.perfectomobile.com, singleTestReportUrl=https://sap.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/180807/RemoteWebDriver_18-08-07_07_58_06_557.xml&ownerId=khyathi.konala@sap.com&sharingCode=32730250-e8b0-406e-a3e5-002b2505bfee, takesScreenshot=true, javascriptEnabled=true, model=iPad Air, platformName=IOS, rotatable=true, testGridReportUrl=https://sap.reporting.perfectomobile.com/library?externalId[0]=khyathi.konala@sap.com_RemoteWebDriver_18-08-07_07_58_06_557&_timestamp[0]=1533628686792, entityType=remote_web_driver, xcuitestFindOptimizations=true, bundleId=com.apple.mobilesafari, serverConnector=, serverHost=10.51.19.23:11603, securityToken=, executionId=khyathi.konala@sap.com_RemoteWebDriver_18-08-07_07_58_06_557, objectsOptimization=true, webdriver.remote.sessionid=09758e51-be65-4e01-9396-db0e5d91114f, locationContextEnabled=true, scriptName=RemoteWebDriver, reportKey=PRIVATE:RemoteWebDriver/180807/RemoteWebDriver_18-08-07_07_58_06_557.xml, windTunnelReportUrl=https://sap.perfectomobile.com/nexperience/singletest/report/?reportRepositoryKey=PRIVATE:RemoteWebDriver/180807/RemoteWebDriver_18-08-07_07_58_06_557.xml&ownerId=khyathi.konala@sap.com&sharingCode=32730250-e8b0-406e-a3e5-002b2505bfee, user=, cssSelectorsEnabled=true}]
Session ID: 09758e51-be65-4e01-9396-db0e5d91114f
*** Element info: {Using=xpath, value=//*[@id='mainShell-header-hdr-begin']//*[@class='sapUiUfdShellHeadContainer']//span}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:356)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:458)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByXPath(QAFExtendedWebDriver.java:400)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElementByXPath(QAFExtendedWebDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:348)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:171)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.findElement(QAFExtendedWebDriver.java:1)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:41)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:181)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:178)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.load(QAFExtendedWebDriver.java:216)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.load(QAFExtendedWebElement.java:299)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.execute(QAFExtendedWebElement.java:250)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at com.qmetry.qaf.automation.step.CommonStep.click_aroundBody50(CommonStep.java:642)
	at com.qmetry.qaf.automation.step.CommonStep$AjcClosure51.run(CommonStep.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.qmetry.qaf.automation.step.JavaStepReporter.javaTestStep(JavaStepReporter.java:101)
	at com.qmetry.qaf.automation.step.CommonStep.click(CommonStep.java:641)
	at com.sap.utilities.CommonFunctionsUtility.selectMenu(CommonFunctionsUtility.java:405)
	at com.quantum.steps.CommonStepsDefs.iSelectFromMenu(CommonStepsDefs.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:159)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:173)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:781)
	at org.testng.TestRunner.run(TestRunner.java:635)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to execute command webpage.element find: findElements command failed. Reason: handset server: server is busy processing another request [/appiumModeStop]
	at com.perfectomobile.selenium.MobileEntity.processCommonResponse(MobileEntity.java:102)
	at com.perfectomobile.selenium.MobileDevice.processResponse(MobileDevice.java:530)
	at com.perfectomobile.selenium.MobileApplication.processResponse(MobileApplication.java:46)
	at com.perfectomobile.selenium.dom.MobileDOMApplication.processResponse(MobileDOMApplication.java:389)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:57)
	at com.perfectomobile.selenium.MobileEntity.executeCommand(MobileEntity.java:50)
	at com.perfectomobile.selenium.MobileApplication.findElementsImpl(MobileApplication.java:262)
	at com.perfectomobile.selenium.dom.MobileDOMApplication.findElementsImpl(MobileDOMApplication.java:399)
	at com.perfectomobile.selenium.MobileApplication.findElementsImpl(MobileApplication.java:243)
	at com.perfectomobile.selenium.MobileApplication.findElementsByXPath(MobileApplication.java:199)
	at com.perfectomobile.selenium.MobileApplication.findElementByXPath(MobileApplication.java:192)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at com.perfectomobile.selenium.MobileApplication.findElement(MobileApplication.java:132)
	at com.perfectomobile.selenium.server.PerfectoMobileDriver.findElement(PerfectoMobileDriver.java:892)
	at sun.reflect.GeneratedMethodAccessor1720.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:109)
	at com.sun.proxy.$Proxy281.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:193)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:33)
	at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:192)
	at org.openqa.selenium.remote.server.MobileDriverServlet.lambda$handleRequest$0(MobileDriverServlet.java:465)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dpgraham** [comment]
Try again with latest appium. We've done work on parallelism.
