### ISSUE TITLE
I try toconnect or Start seccion with an an application in apium and I see somehow same issue:

### ISSUE THREAD

**Issue by mahsanasseri** [appium/appium-desktop#605]
Try to connect with appium server, I set al the Capabilities : 
{
  "deviceName": "Xiaomi Mi A1",
  "udid": "0eebac319805",
  "platformName": "Android",
  "platformVersion": "8.1.0",
  "appPackage": "com.isinolsun.app",
  "appActivity": "com.isinolsun.app.activities.OnBoarderActivity"
}
with an application and see this Error: 

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.isinolsun.app' application. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\naser\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 0eebac319805 shell am start -W -n com.isinolsun.app/com.isinolsun.app.activities.OnBoarderActivity -S' exited with code 4294967295'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.isinolsun.app/.activities.OnBoarderActivity } from null (pid=11484, uid=2000) not exported from uid 10084
 
 java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.isinolsun.app/.activities.OnBoarderActivity } from null (pid=11484, uid=2000) not exported from uid 10084
 at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1641)
 at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:443)
 at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:283)
 at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:822)
 at com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:4744)
 at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:412)
 at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
 at android.os.ShellCommand.exec(ShellCommand.java:96)
 at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15186)
 at android.os.Binder.shellCommand(Binder.java:594)
 at android.os.Binder.onTransact(Binder.java:492)
 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4243)
 at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2971)
 at android.os.Binder.execTransact(Binder.java:697)'; Code: '4294967295'

I did uninstall Appium and reinstall the desktop version:" appium-desktop-setup-1.6.3" and it didn't work!
Can anyone help me with that?

**Comment by dpgraham** [comment]
I would try asking at discuss.appium.io

The GitHub issues pages is for reporting bugs and feature requests.
