### ISSUE TITLE
Cannot start session (An unknown server-side error occurred while processing the command)

### ISSUE THREAD

**Issue by kahill14793** [appium/appium-desktop#615]
## Appium or Appium Desktop?

Both of Appium and Appium Desktop have the same issue

## The problem

An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.isinolsun.app' application. Original error: Error executing adbExec. Original error: 'Command '/Users/mac/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n com.isinolsun.app/com.isinolsun.app.activities.UserTypeChooserActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.isinolsun.app/.activities.UserTypeChooserActivity } from null (pid=3998, uid=2000) not exported from uid 10076 at android.os.Parcel.readException(Parcel.java:1684) at android.os.Parcel.readException(Parcel.java:1637) at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3208) at com.android.commands.am.Am.runStart(Am.java:630) at com.android.commands.am.Am.onRun(Am.java:388) at com.android.internal.os.BaseCommand.run(BaseCommand.java:51) at com.android.commands.am.Am.main(Am.java:121) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)'; Code: '1'

## Environment

- I am running Appium Desktop version v1.8.1
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by kahill14793** [comment]
this issue has resolved by add android:exported="true" to manifest file
