### ISSUE TITLE
Appium desktop crashes after attached to the session

### ISSUE THREAD

**Issue by MoOoG** [appium/appium-desktop#637]
## Appium Desktop

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After attaching to the session and selecting anything on UI, Appium desktop crashes.

## Environment

- I am running Appium Desktop version 1.7.0.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

`2018-09-26 06:38:31:464 - info: [Appium] Welcome to Appium v1.9.0
2018-09-26 06:38:31:465 - info: [Appium] Non-default server args:
2018-09-26 06:38:31:465 - info: [Appium]   log: /Users/zigas/Desktop/appium.log
2018-09-26 06:38:31:481 - info: [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2018-09-26 06:38:45:431 - info: [HTTP] --> GET /wd/hub/sessions
2018-09-26 06:38:45:431 - info: [HTTP] {}
2018-09-26 06:38:45:436 - info: [debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
2018-09-26 06:38:45:440 - info: [debug] [MJSONWP] Responding to client with driver.getSessions() result: []
2018-09-26 06:38:45:446 - info: [HTTP] <-- GET /wd/hub/sessions 200 13 ms - 40
2018-09-26 06:38:45:447 - info: [HTTP] 
2018-09-26 06:40:21:648 - info: [HTTP] --> GET /wd/hub/session/3944228c-a75c-4a02-8c50-b7d9bb8fd668
2018-09-26 06:40:21:649 - info: [HTTP] {}
2018-09-26 06:40:21:703 - error: [MJSONWP] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2018-09-26 06:40:21:703 - error: [MJSONWP]     at asyncHandler$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:223:15)
2018-09-26 06:40:21:703 - error: [MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2018-09-26 06:40:21:703 - error: [MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at new Promise (<anonymous>)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
2018-09-26 06:40:21:704 - error: [MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js:335:32)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:417:15
2018-09-26 06:40:21:706 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2018-09-26 06:40:21:706 - error: [MJSONWP]     at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2018-09-26 06:40:21:707 - error: [MJSONWP]     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at param (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:707 - error: [MJSONWP]     at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:708 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at jsonParser (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:708 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:709 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:709 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:709 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:709 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2018-09-26 06:40:21:709 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:709 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:709 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:710 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:710 - error: [MJSONWP]     at methodOverride (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/method-override/index.js:65:14)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:711 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at urlencodedParser (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/types/urlencoded.js:91:7)
2018-09-26 06:40:21:711 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:712 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:712 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:713 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:713 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:713 - error: [MJSONWP]     at defaultToJSONContentType (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/express/middleware.js:37:3)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:714 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at fixPythonContentType (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/express/middleware.js:30:3)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:714 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:715 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at allowCrossDomain (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/express/middleware.js:15:7)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2018-09-26 06:40:21:715 - error: [MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2018-09-26 06:40:21:715 - error: [MJSONWP]     at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at SendStream.error (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/serve-static/index.js:121:7)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at emitOne (events.js:116:13)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at SendStream.emit (events.js:211:7)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at SendStream.error (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/send/index.js:270:17)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at SendStream.onStatError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/send/index.js:421:12)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/send/index.js:736:16)
2018-09-26 06:40:21:716 - error: [MJSONWP]     at onstat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/send/index.js:725:14)
2018-09-26 06:40:21:717 - error: [MJSONWP]     at FSReqWrap.oncomplete (fs.js:152:21)
2018-09-26 06:40:21:719 - info: [HTTP] <-- GET /wd/hub/session/3944228c-a75c-4a02-8c50-b7d9bb8fd668 404 70 ms - 11525
2018-09-26 06:40:21:719 - info: [HTTP] 
2018-09-26 06:40:39:171 - error: uncaughtException: no value passed to Element constructor date=Wed Sep 26 2018 08:40:39 GMT+0200 (CEST), pid=1542, uid=1192947920, gid=2007269532, cwd=/, execPath=/Applications/Appium.app/Contents/MacOS/Appium, version=v8.9.3, argv=[/Applications/Appium.app/Contents/MacOS/Appium], rss=258920448, heapTotal=417566720, heapUsed=402970176, external=177780, loadavg=[7.1318359375, 4.96240234375, 5.72412109375], uptime=1526, trace=[column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/element.js, function=PromiseElement.Element, line=15, method=Element, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js, function=new PromiseElement, line=73, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js, function=PromiseWebdriver.newElement, line=103, method=newElement, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js, function=null, line=137, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js, function=null, line=82, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/webdriver.js, function=null, line=179, method=null, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/http-utils.js, function=Request._callback, line=89, method=_callback, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=Request.self.callback, line=186, method=callback, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Request.emit, line=214, method=emit, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=null, line=1163, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Request.emit, line=211, method=emit, native=false, column=1, file=/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js, function=null, line=1085, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=313, method=onceWrapper, native=false, column=20, file=events.js, function=emitNone, line=111, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=208, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1056, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[Error: no value passed to Element constructor,     at PromiseElement.Element (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/element.js:15:1),     at new PromiseElement (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js:73:1),     at PromiseWebdriver.newElement (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/promise-webdriver.js:103:1),     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js:137:1,     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/callbacks.js:82:1,     at /Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/webdriver.js:179:1,     at Request._callback (/Applications/Appium.app/Contents/Resources/app/webpack:/~/wd/lib/http-utils.js:89:1),     at Request.self.callback (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:186:1),     at emitTwo (events.js:126:13),     at Request.emit (events.js:214:7),     at Request.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:1163:1),     at emitOne (events.js:116:13),     at Request.emit (events.js:211:7),     at IncomingMessage.<anonymous> (/Applications/Appium.app/Contents/Resources/app/webpack:/~/request/request.js:1085:1),     at Object.onceWrapper (events.js:313:30),     at emitNone (events.js:111:20),     at IncomingMessage.emit (events.js:208:7),     at endReadableNT (_stream_readable.js:1056:12),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
`

**Comment by a-en** [comment]
@dpgraham , is there any workaround for this issue? In my case everything works fine for Android, but the defect completely blocks us from working with iOS devices

**Comment by viswatej29** [comment]
I get the below error while running the tests in "Jenkins" environment on Appium 1.9.1
on Android device
13:19:11     [Appium] Welcome to Appium v1.9.1
13:19:11     [Appium] Appium REST http interface listener started on 0.0.0.0:4723
13:19:11     [HTTP] --> GET /wd/hub/status
13:19:11     [HTTP] {}
13:19:11     [debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
13:19:11     [debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1"}}
13:19:11     [HTTP] <-- GET /wd/hub/status 200 15 ms - 67
13:19:11     [HTTP] 
13:19:11     [HTTP] --> POST /wd/hub/session/990b2475-b68d-44da-a40e-265cc2837448/appium/app/close
13:19:11     [HTTP] {}
13:19:11     [debug] [GENERIC] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
13:19:11     [debug] [GENERIC]     at asyncHandler$ (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:260:15)
13:19:11     [debug] [GENERIC]     at tryCatch (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
13:19:11     [debug] [GENERIC]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
13:19:11     [debug] [GENERIC]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
13:19:11     [debug] [GENERIC]     at invoke (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
13:19:11     [debug] [GENERIC]     at enqueueResult (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
13:19:11     [debug] [GENERIC]     at new Promise (<anonymous>)
13:19:11     [debug] [GENERIC]     at new F (/usr/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
13:19:11     [debug] [GENERIC]     at AsyncIterator.enqueue (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
13:19:11     [debug] [GENERIC]     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
13:19:11     [debug] [GENERIC]     at Object.runtime.async (/usr/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
13:19:11     [debug] [GENERIC]     at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js:380:32)
13:19:11     [debug] [GENERIC]     at /usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:446:15
13:19:11     [debug] [GENERIC]     at Layer.handle [as handle_request] (/usr/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
13:19:11     [debug] [GENERIC]     at next (/usr/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
13:19:11     [debug] [GENERIC]     at Route.dispatch (/usr/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
13:19:11     [debug] [GENERIC]     at Layer.handle [as handle_request] (/usr/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
13:19:11     [debug] [GENERIC]     at /usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
13:19:11     [debug] [GENERIC]     at param (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
13:19:11     [debug] [GENERIC]     at param (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
13:19:11     [debug] [GENERIC]     at Function.process_params (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
13:19:11     [debug] [GENERIC]     at next (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
13:19:11     [debug] [GENERIC]     at logger (/usr/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
13:19:11     [debug] [GENERIC]     at Layer.handle [as handle_request] (/usr/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
13:19:11     [debug] [GENERIC]     at trim_prefix (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
13:19:11     [debug] [GENERIC]     at /usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
13:19:11     [debug] [GENERIC]     at Function.process_params (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
13:19:11     [debug] [GENERIC]     at next (/usr/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
13:19:11     [debug] [GENERIC]     at /usr/lib/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
13:19:11     [debug] [GENERIC]     at invokeCallback (/usr/lib/node_modules/appium/node_modules/raw-body/index.js:224:16)
13:19:11     [debug] [GENERIC]     at done (/usr/lib/node_modules/appium/node_modules/raw-body/index.js:213:7)
13:19:11     [debug] [GENERIC]     at IncomingMessage.onEnd (/usr/lib/node_modules/appium/node_modules/raw-body/index.js:273:7)
13:19:11     [debug] [GENERIC]     at emitNone (events.js:106:13)
13:19:11     [debug] [GENERIC]     at IncomingMessage.emit (events.js:208:7)
13:19:11     [debug] [GENERIC]     at endReadableNT (_stream_readable.js:1064:12)
13:19:11     [debug] [GENERIC]     at _combinedTickCallback (internal/process/next_tick.js:139:11)
13:19:11     [debug] [GENERIC]     at process._tickCallback (internal/process/next_tick.js:181:9)
13:19:11     [HTTP] <-- POST /wd/hub/session/990b2475-b68d-44da-a40e-265cc2837448/appium/app/close 404 20 ms - 3834
