### ISSUE TITLE
Appium desktop inspector session crashes after refresh 

### ISSUE THREAD

**Issue by krirohini** [appium/appium-desktop#682]
## Appium or Appium Desktop?
appium desktop
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment
Mac OS High Sierra
Appium 1.9.1
Appium Server 1.8.0

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

logs
=================

￼
The server is running

```
[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 6 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appActivity":".MainActivity","appPackage”:”com.samsung.xxx”,”automationName":"Appium","deviceName":"Note_8_","forceMjsonwp":"true","fullReset":"false","newCommandTimeout":"90","noReset":"true","platformName":"Android","platformVersion":"7.1.1","useJSONSource":"true","connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":".MainActivity","appPackage":"com.samsung.xxx”,”automationName":"Appium","deviceName":"Note_8_wise","forceMjsonwp":"true","fullReset":"false","newCommandTimeout":"90","noReset":"true","platformName":"Android","platformVersion":"7.1.1","useJSONSource":"true","connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1540361979701 (23:19:39 GMT-0700 (PDT))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.1.1) session
[Appium] Capabilities:
[Appium]   appActivity: .MainActivity
[Appium]   appPackage: com.samsung.xxx
[Appium]   automationName: Appium
[Appium]   deviceName: Note_8_wise
[Appium]   forceMjsonwp: true
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 90
[Appium]   noReset: true
[Appium]   platformName: Android
[Appium]   platformVersion: 7.1.1
[Appium]   useJSONSource: true
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"appActivity":".MainActivi...
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'fullReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('90') to integer (90). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: forceMjsonwp, useJSONSource, connectHardwareKeyboard.
[BaseDriver] Session created with session id: ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc
[AndroidDriver] Java version is: 1.8.0_152-release
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under '/Users/kumari/Library/Android/sdk' (newest first):
[ADB]     /Users/kumari/Library/Android/sdk/build-tools/27.0.3
[ADB]     /Users/kumari/Library/Android/sdk/build-tools/26.0.2
[ADB] Using adb from /Users/kumari/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android '7.1.1'
[ADB] Setting device id to 988914424e3356484b30
[ADB] Getting device platform version
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.1.1
[AndroidDriver] Using device: 988914424e3356484b30
[ADB] Setting device id to 988914424e3356484b30
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 25
[ADB] Device API level: 25
[AndroidDriver] Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[AndroidDriver] App file was not listed, instead we're going to run com.samsung.xxxdirectly on the device
[AndroidDriver] Checking whether package is present on the device
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell pm list packages com.samsung.xxx’
[AndroidDriver] Starting Android session
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 wait-for-device'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell pm list packages io.appium.settings'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell dumpsys package io.appium.settings'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/kumari/Library/Android/sdk/build-tools/27.0.3/aapt
[ADB] The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell ps'
[ADB] Device API level: 25
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell am start -W -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 25
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell appops set io.appium.settings android\:mock_location allow'
[AndroidDriver] setDeviceLanguageCountry requires language or country.
[AndroidDriver] Got language: 'undefined' and country: 'undefined'
[Logcat] Starting logcat capture
[AndroidDriver] Pushing unlock helper app to device...
[ADB] Getting install status for io.appium.unlock
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell pm list packages io.appium.unlock'
[ADB] App is installed
[ADB] Getting package info for 'io.appium.unlock'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell dumpsys package io.appium.unlock'
[ADB] The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[ADB] Getting device platform version
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 7.1.1
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell wm size'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell getprop ro.product.model'
[ADB] Current device property 'ro.product.model': SM-N950U
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell getprop ro.product.manufacturer'
[ADB] Current device property 'ro.product.manufacturer': samsung
[AndroidDriver] No app sent in, not parsing package/activity
[AndroidDriver] No app capability. Assuming it is already on the device
[AndroidBootstrap] Watching for bootstrap disconnect
[ADB] Forwarding system: 4724 to device: 4724
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 forward tcp\:4724 tcp\:4724'
[UiAutomator] Starting UiAutomator
[UiAutomator] Moving to state 'starting'
[UiAutomator] Parsing uiautomator jar
[UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 push /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[ADB] Attempting to kill all uiautomator processes
[ADB] Getting all processes with uiautomator
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[UiAutomator] Starting UIAutomator
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","988914424e3356484b30","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.samsung.xxx”,”-e”,”disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell dumpsys window'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen is locked, trying to unlock
[AndroidDriver] Using app unlock, this is going to be deprecated!
[AndroidDriver] Unlocking screen
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell am force-stop io.appium.unlock'
[AndroidBootstrap] Emitting alert message...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Emitting system alert message
[AndroidDriver] Launching io.appium.unlock
[ADB] Device API level: 25
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell am start -W -n io.appium.unlock/.Unlock -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[ADB] Device API level: 25
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell am start -W -n com.samsung.xxx/.MainActivity -S'
[Appium] New AndroidDriver session created successfully, session ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1540362010190 (23:20:10 GMT-0700 (PDT))
[MJSONWP] Cached the protocol value 'MJSONWP' for the new session ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appActivity":".MainActivity","appPackage":"com.samsung.xxx”,”automationName":"Appium","deviceName":"Note_8_wise","forceMjsonwp":"true","fullReset":false,"newCommandTimeout":90,"noReset":true,"platformName":"Android","platformVersion":"7.1.1","useJSONSource":"true","connectHardwareKeyboard":true},"appActivity":".MainActivity","appPackage":"com.samsung.xxx,”automationName":"Appium","deviceName":"988914424e3356484b30","forceMjsonwp":"true","fullReset":false,"newCommandTimeout":90,"noReset":true,"platformName":"Android","platformVersion":"7.1.1","useJSONSource":"true","connectHardwareKeyboard":true,"deviceUDID":"988914424e3356484b30","deviceScreenSize":"1440x2960","deviceModel":"SM-N950U","deviceManufacturer":"samsung"}
[HTTP] <-- POST /wd/hub/session 200 30494 ms - 1028
[HTTP] 
[HTTP] --> POST /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/context
[HTTP] {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[AndroidDriver] Getting a list of available webviews
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell cat /proc/net/unix'
[AndroidDriver] WEBVIEW_21791 mapped to pid 21791
[AndroidDriver] Getting process name for webview
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell ps'
[AndroidDriver] WEBVIEW_16046 mapped to pid 16046
[AndroidDriver] Getting process name for webview
[ADB] Running '/Users/kumari/Library/Android/sdk/platform-tools/adb -P 5037 -s 988914424e3356484b30 shell ps'
[AndroidDriver] Parsed pid: '16046' pkg: 'com.att.callprotect' from
[AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[AndroidDriver]     u0_a113   16046 1809  1960120 154036 SyS_epoll_ 7fb15858c0 S com.att.callprotect
[AndroidDriver] Returning process name: 'com.att.callprotect'
[AndroidDriver] Parsed pid: '21791' pkg: 'com.directv.dvrscheduler' from
[AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
[AndroidDriver]     u0_a221   21791 1926  1908288 153336 SyS_epoll_ 00f0118c00 S com.directv.dvrscheduler
[AndroidDriver] Returning process name: 'com.directv.dvrscheduler'
[AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.directv.dvrscheduler","WEBVIEW_com.att.callprotect"]
[AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.directv.dvrscheduler","WEBVIEW_com.att.callprotect"]
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/context 200 228 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"<\/android.widget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/hierarchy>"}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getPageSource() result: "
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/source 200 55 ms - 2690
[HTTP] 
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[ADB] Device API level: 25
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAisCAYAAACtR1KuAABlAklEQVR4AezBeXBUeYLg9+/vvZf5MiVl6sgUpBDoghQpcUlcBXWoqII+oLq6Wz0zPd0T6w0P440NR4wjHOtxTIztscPRf4wddswf69kJh8Nb69hdT/f2zqDePuhjBFQJiqsoiTsBgS6QUiAJHSmlMl/mez/363J2q9UcAiQQ1O/zEV/7r/47iaIoiqIoiqIoiqIoyktMQ1EURVEURVEURVEU5SWnoSiKoiiKoiiKoiiK8pLTUBRFURRFURRFURRFeclpKIqiKIqiKIqiKIqivOQ0FEVRFEVRFEVRFEVRXnIaiqIoiqIoiqIoiqIoLzkNRVEURVEURVEURVGUl5yGoiiKoiiKoiiKoijKS05DURRFURRFURRFURTlJaehKIqiKIqiKIqiKIryktNQFEVRFEVRFEVRFEV5yWkoivJYmqaxMlRKTWUFhq6jKIqiKIqiKIqiLC8GykvB0HXKSwL4vR68HgPpOAghsLI5ZrM2o5NTZHM2yuISQuDzetm2oZ53d27FMHROX7jKqQtXmEhOI6VEURRFURRFURRFefEMlGVL1zRqImHWV5ZTW7ECTQgeRkpJYjzJhZ7b9A2PkLMdlGcTKg6yef1aNtXXURYMomkarl1bGtmwroabt4e40t1L31ACK5tDURRFUebymV4i4RC1lRGeVDpj0XWtm3TGYr7dTRvweb3M1Ts4zPDoGOmMxcuiNBhgfCrJi1AaDFAcKOJB+gYTvOp0TcN2HJSlVVEewvR6eZiMZZEYGUNRlMVjoCxLtStDvLVhLR5dIxgMYpomkUiEYDCI3+8nz7IspqamGB4eRtd1IiVFODTS3nWV7jt3URauwGcSKimmojxE3epVrImUU+j3o2kav00QKCykObaODXXVjCenuT18j6GRMSamkkxNp0il02SsLNlcDkVRFOXzp6I8xLf376UkGGCu89e6aYpFWYh3djZz7GwXpy5cYb53dm5l...
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/screenshot 200 1601 ms - 41866
[HTTP] 
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/window/current/size
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"getDeviceSize","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getDeviceSize
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getWindowSize() result: {"height":2094,"width":1080}
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/window/current/size 200 25 ms - 100
[HTTP] 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"height":2094,"width":1080}}
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/source
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Command returned error:org.w3c.dom.DOMException:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":""}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[MJSONWP] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command.
[MJSONWP]     at errorFromMJSONWPStatusCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:789:10)
[MJSONWP]     at Socket. (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-android-driver/lib/bootstrap.js:139:18)
[MJSONWP]     at Socket.emit (events.js:182:13)
[MJSONWP]     at addChunk (_stream_readable.js:279:12)
[MJSONWP]     at readableAddChunk (_stream_readable.js:260:13)
[MJSONWP]     at Socket.Readable.push (_stream_readable.js:219:10)
[MJSONWP]     at TCP.onread (net.js:636:20)
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/source 500 131 ms - 154
[HTTP] 
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/screenshot
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[ADB] Device API level: 25
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAisCAYAAACtR1KuAACAAElEQVR4AezBeXBUeYLg9+/vvZf5MiWlrkxBCoEuSJESl8RVUEWpqBJ9QHV1t3q6e7o71hse2hsbjhhH2Ou1J8b22H/UH2OH7fljd7bD4fDW2rvr7p7eGVTbB9WHgCpBcRUlcYkEBLpASoEkdKSOzJf53s/zupzdGjWHAAkE9ft8xNf+i/9OoiiKoiiKoiiKoiiK8gLTUBRFURRFURRFURRFecFpKIqiKIqiKIqiKIqivOA0FEVRFEVRFEVRFEVRXnAaiqIoiqIoiqIoiqIoLzgNRVEURVEURVEURVGUF5yGoiiKoiiKoiiKoijKC05DURRFURRFURRFURTlBaehKIqiKIqiKIqiKIrygtNQFEVRFEVRFEVRFEV5wWkoiqIoiqIoiqIoiqK84DQURVEURVEURVEURVFecBqKojySpmmsDBZRWVaKoesoiqIoiqIoiqIoy4uB8kIwdJ2SwgB+rwevx0A6DkIIrHSG2bTNyMQk6YyNsriEEPi8XrZtqOGtnVsxDJ3TF65w6kIn44kppJQoiqIoiqIoiqIoz5+BsmzpmkZlOMT6shKqSlegCcGDSCmJjyW40H2L3qFhMraD8nSCBflsXr+WTTXVFOfno2karl1b6tiwrpIbtwbp7OqhdzCOlc6gKIqiKHP5TC/hUJCqsjCPK5my6LjaRTJlMd/u+g34vF7m6hkYYmhklGTK4kVRlB9gbDLB81CUH6AgkMf99A7EednpmobtOChLq7QkiOn18iApyyI+PIqiKIvHQFmWqlYGeX3DWjy6Rn5+PqZpEg6Hyc/Px+/3k2VZFpOTkwwNDaHrOuHCPBzqaO24QtftOygLl+MzCRYWUFoSpHr1KtaES8j1+9E0jX9IEMjNpSG6jg3VFYwlprg1dJfB4VHGJxNMTs0wk0ySstKkMxkURVGUz5/SkiDf3d9EYX6Auc5f7aI+GmEh3tzZwLGzHZy60Ml8b+7c...
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/screenshot 200 1740 ms - 314082
[HTTP] 
[HTTP] --> GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/window/current/size
[HTTP] {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc"]
[AndroidBootstrap] Sending command to android: {"cmd":"action","action":"getDeviceSize","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getDeviceSize
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"height":2094,"width":1080}}
[AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getWindowSize() result: {"height":2094,"width":1080}
[HTTP] <-- GET /wd/hub/session/ad2a36c3-ec34-4eb0-bd20-cd5ced4765bc/window/current/size 200 18 ms - 100
[HTTP] 
```

**Comment by dpgraham** [comment]
Can you try running Appium from the command line:

```
npm install -g appium
appium .
```

And see if the issue still happens?

**Comment by krirohini** [comment]
still getting the same issue.

[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":""}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [MJSONWP] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command.

**Comment by krirohini** [comment]
The session created by Appium while launching the App is terminating. 

private DesiredCapabilities settingDeviceCapabilities(String androidVersion, String deviceName) {
                 capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability(CapabilityType.VERSION, androidVersion);
		capabilities.setCapability("deviceName", deviceName);
		
		capabilities.setCapability("appPackage", "com.samsung.xxxx");
		capabilities.setCapability("appActivity", ".MainActivity");
		
		capabilities.setCapability("autoGrantPermissions", "true");
                 capabilities.setCapability("autoAcceptAlerts", "true");
                 capabilities.setCapability("noReset", "true");
                 capabilities.setCapability("fullReset", "false");
}

**Comment by dpgraham** [comment]
Try setting `automationName=UIAutomator2`.... this automation is no longer supported.

**Comment by dpgraham** [comment]
Can you try running logcat and then getting the logs for when that error happens.

**Comment by iwnfubb** [comment]
Hi I have same problem with iphone simulator also, please help !
