### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function

### ISSUE THREAD

**Issue by arkadiyala** [appium/appium-desktop#749]
## Appium or Appium Desktop?
Appium Desktop 

## The problem

I’m trying to retrieve attribute value by using getAttribute.
String ActualValue = driver.findElement(By.xpath("//div[@data-componentname=‘globalHeader’]")).getAttribute(“data-componentname”);
Assert.assertEquals(“data-componentname”,ActualValue,“Message”);

When i run script on laptop - Running fine
When i run same script on google pixel phone(Android) - Getting below error.

Exception in thread “main” org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
(Session info: chrome=70.0.3538.110)

Could anybody please help me.

## Environment

- I am running Appium Desktop version _1.7.0 & above versions_.
- I am on (pick one):
    - [ ] Windows

**Comment by arkadiyala** [comment]
Hi @dpgraham , @jlipps .@Walther 

Please see my POM.xml - https://gist.github.com/arkadiyala/7ce3a877ae9b10c2f5e7dccc8b36eb9b
Please see appium log(When I use Appium Desktop 7.0) - https://gist.github.com/arkadiyala/7288f79149e78b670791261fe60f6489
(Similar log has been generated for Appium 1.8.2 as well)
![image](https://user-images.githubusercontent.com/21693119/49389863-f355c780-f6ec-11e8-859c-b5fbd4ee7083.png)

Please help me.

**Comment by dpgraham** [comment]
Can you provide the Appium logs as text.

**Comment by arkadiyala** [comment]
Hi @dpgraham - 
Please see log file- 
[info] [35m[Appium][39m Welcome to Appium v1.9.1
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"browserName":"chrome","deviceName":"GooglePhone","platform":"ANY","platformName":"android","version":""},"capabilities":{"desiredCapabilities":{"browserName":"chrome","deviceName":"GooglePhone","platform":"ANY","platformName":"android","version":""},"firstMatch":[{"browserName":"chrome","platformName":"android"}]}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"browserName":"chrome","deviceName":"GooglePhone","platform":"ANY","platformName":"android","version":""},null,{"desiredCapabilities":{"browserName":"chrome","deviceName":"GooglePhone","platform":"ANY","platformName":"android","version":""},"firstMatch":[{"browserName":"chrome","platformName":"android"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1543861222404 (12:20:22 GMT-0600 (Central Standard Time))
[info] [35m[Appium][39m Could not parse W3C capabilities: 'deviceName' can't be blank
[info] [35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[warn] [35m[BaseDriver][39m The capabilities ["deviceName","platform","version"] are not standard capabilities and should have an extension prefix
[info] [35m[Appium][39m Creating new AndroidDriver (v4.1.1) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   deviceName: GooglePhone
[info] [35m[Appium][39m   platform: ANY
[info] [35m[Appium][39m   version: 
[info] [35m[Appium][39m   browserName: chrome
[info] [35m[Appium][39m   platformName: android
[debug] [35m[BaseDriver][39m W3C capabilities {"alwaysMatch":{"appium:dev... and MJSONWP desired capabilities {"browserName":"chrome","de... were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {"alwaysMatch":{"appium:dev...
[warn] [35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: platform, version.
[info] [35m[BaseDriver][39m Session created with session id: d97aa8e2-3bfb-421b-8cb1-33bd01f107cd[info] [35m[AndroidDriver][39m Java version is: 1.8.0_161
[info] [35m[AndroidDriver][39m We're going to run a Chrome-based session
[info] [35m[AndroidDriver][39m Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices...
[debug] [35m[ADB][39m 1 device(s) connected
[info] [35m[AndroidDriver][39m Using device: FA71A0302632
[debug] [35m[ADB][39m Setting device id to FA71A0302632
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 27
[debug] [35m[ADB][39m Device API level: 27
[warn] [35m[AndroidDriver][39m Consider setting 'automationName' capability to 'uiautomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[info] [35m[AndroidDriver][39m App file was not listed, instead we're going to run com.android.chrome directly on the device
[debug] [35m[AndroidDriver][39m Checking whether package is present on the device
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell pm list packages com.android.chrome'[info] [35m[AndroidDriver][39m Starting Android session
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 wait-for-device'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell echo ping'[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell pm list packages io.appium.settings'[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m The installed 'io.appium.settings' package does not require upgrade ('2.3.0' >= '2.3.0')
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell ps'[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[ADB][39m Device API level: 27
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell appops set io.appium.settings android\:mock_location allow'[warn] [35m[AndroidDriver][39m setDeviceLanguageCountry requires language or country.
[warn] [35m[AndroidDriver][39m Got language: 'undefined' and country: 'undefined'
[debug] [35m[Logcat][39m Starting logcat capture[debug] [35m[AndroidDriver][39m Pushing unlock helper app to device...
[debug] [35m[ADB][39m Getting install status for io.appium.unlock
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell pm list packages io.appium.unlock'[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.unlock'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell dumpsys package io.appium.unlock'[debug] [35m[ADB][39m The installed 'io.appium.unlock' package does not require upgrade ('2.0.0' >= '2.0.0')
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell getprop ro.build.version.release'[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 8.1.0
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell wm size'[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell getprop ro.product.model'[debug] [35m[ADB][39m Current device property 'ro.product.model': Pixel
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell getprop ro.product.manufacturer'[debug] [35m[ADB][39m Current device property 'ro.product.manufacturer': Google
[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[AndroidDriver][39m No app capability. Assuming it is already on the device
[debug] [35m[ADB][39m Getting install status for com.android.chrome
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell pm list packages com.android.chrome'[debug] [35m[ADB][39m App is installed
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell am force-stop com.android.chrome'[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell pm clear com.android.chrome'[debug] [35m[AndroidDriver][39m Performed fast reset on the installed 'com.android.chrome' application (stop and clear)
[debug] [35m[AndroidBootstrap][39m Watching for bootstrap disconnect
[debug] [35m[ADB][39m Forwarding system: 4724 to device: 4724
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 forward tcp\:4724 tcp\:4724'[debug] [35m[UiAutomator][39m Starting UiAutomator
[debug] [35m[UiAutomator][39m Moving to state 'starting'
[debug] [35m[UiAutomator][39m Parsing uiautomator jar
[debug] [35m[UiAutomator][39m Found jar name: 'AppiumBootstrap.jar'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 push C\:\\Users\\sl4843\\AppData\\Local\\appium-desktop\\app-1.8.2\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\bootstrap\\bin\\AppiumBootstrap.jar /data/local/tmp/'
[debug] [35m[ADB][39m Attempting to kill all uiautomator processes
[debug] [35m[ADB][39m Getting all processes with uiautomator
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell ps'[debug] [35m[ADB][39m Attempting to kill process 14673
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell kill -0 14673'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell kill 14673'[error] [35m[UiAutomator][39m UiAutomator exited unexpectedly with code 4294967183, signal null
[debug] [35m[UiAutomator][39m Moving to state 'stopped'
[debug] [35m[AndroidDriver][39m Shutting down Android driver
[debug] [35m[AndroidDriver][39m Stopping chromedriver for context CHROMIUM
[debug] [35m[Chromedriver][39m Changed state to 'stopping'
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /] to [DELETE http://127.0.0.1:8001/wd/hub/session/a291b79f8cadebb8b158ff08868d84e4] with no body
[warn] [35m[Appium][39m Closing session, cause was 'UiAUtomator shut down unexpectedly'
[info] [35m[Appium][39m Removing session 619a67b9-7a49-40a5-b44b-b7ffed07a235 from our master session list[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"a291b79f8cadebb8b158ff08868d84e4\",\"status\":0,\"value\":null}"
[debug] [35m[Chromedriver][39m Changed state to 'stopped'
[debug] [35m[ADB][39m Pressing the HOME button
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell input keyevent 3'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell kill 14673'[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell kill 14673'[debug] [35m[UiAutomator][39m Starting UIAutomator
[debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","FA71A0302632","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false][warn] [35m[AndroidBootstrap][39m Cannot shut down Android bootstrap; it has already shut down
[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell am force-stop io.appium.unlock'[debug] [35m[AndroidDriver][39m Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[debug] [35m[UiAutomator][39m Moving to state 'online'
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Registered crash watchers.
[info] [35m[AndroidBootstrap][39m Android bootstrap socket is now connected
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell dumpsys window'
[debug] [35m[AndroidBootstrap][39m [BOOTSTRAP LOG] [debug] Client connected[info] [35m[AndroidDriver][39m Screen already unlocked, doing nothing
[info] [35m[AndroidDriver][39m Starting a chrome-based browser session
[debug] [35m[AndroidDriver][39m A port was not given, using random port: 8001
[debug] [35m[Chromedriver][39m Changed state to 'starting'
[debug] [35m[Chromedriver][39m Found 1 executable in 'C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win'[debug] [35m[Chromedriver][39m The following Chromedriver executables were found:
[debug] [35m[Chromedriver][39m     C:/Users/sl4843/AppData/Local/appium-desktop/app-1.8.2/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe (minimum Chrome version '68.0.3440')
[debug] [35m[ADB][39m Device API level: 27
[debug] [35m[ADB][39m Getting package info for 'com.android.chrome'
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 shell dumpsys package com.android.chrome'
[debug] [35m[Chromedriver][39m Found Chrome bundle 'com.android.chrome' version '70.0.3538'
[debug] [35m[Chromedriver][39m Found 1 Chromedriver executable capable of automating Chrome '70.0.3538'.
[debug] [35m[Chromedriver][39m Choosing the most recent, 'C:/Users/sl4843/AppData/Local/appium-desktop/app-1.8.2/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe'.
[debug] [35m[Chromedriver][39m If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[info] [35m[Chromedriver][39m Set chromedriver binary as: C:/Users/sl4843/AppData/Local/appium-desktop/app-1.8.2/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe
[debug] [35m[Chromedriver][39m Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8001 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))[warn] [35m[Chromedriver][39m No old chromedrivers seemed to exist
[debug] [35m[Chromedriver][39m Cleaning any old adb forwarded port socket connections
[debug] [35m[ADB][39m List forwarding ports
[debug] [35m[ADB][39m Running 'C:\Users\sl4843\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s FA71A0302632 forward --list'[info] [35m[Chromedriver][39m Spawning chromedriver with: C:/Users/sl4843/AppData/Local/appium-desktop/app-1.8.2/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe --url-base=wd/hub --port=8001 --adb-port=5037 --verbose
[debug] [35m[Chromedriver][39m Chromedriver version: '2.42.591088'
[debug] [35m[JSONWP Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[JSONWP Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8001/wd/hub/status] with no body[debug] [35m[JSONWP Proxy][39m Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[debug] [35m[JSONWP Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8001/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"FA71A0302632"}}}[debug] [35m[Chromedriver][39m Webview version: 'Chrome/70.0.3538.110'[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"d3dbf2e276dac044c314e46099c7fd79","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"goog:chromeOptions":{"debuggerAddress":"localhost:5731"},"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"setWindowRect":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"70.0.3538.110","webStorageEnabled":true}}
[debug] [35m[Chromedriver][39m Changed state to 'online'
[info] [35m[Appium][39m New AndroidDriver session created successfully, session d97aa8e2-3bfb-421b-8cb1-33bd01f107cd added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1543861237430 (12:20:37 GMT-0600 (Central Standard Time))
[debug] [35m[W3C][39m Cached the protocol value 'W3C' for the new session d97aa8e2-3bfb-421b-8cb1-33bd01f107cd
[debug] [35m[W3C][39m Responding to client with driver.createSession() result: {"capabilities":{"platform":"ANY","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"browserName":"chrome","platformName":"android","deviceName":"GooglePhone","platform":"ANY","version":""},"browserName":"chrome","platformName":"android","deviceName":"FA71A0302632","version":"","deviceUDID":"FA71A0302632","platformVersion":"8.1.0","deviceScreenSize":"1080x1920","deviceModel":"Pixel","deviceManufacturer":"Google"}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m15027 ms - 614[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/cookie[39m
[info] [35m[HTTP][39m [90m{}[39m
[info] [35m[W3C][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/cookie' to command name 'deleteCookies'
[debug] [35m[JSONWP Proxy][39m Proxying [DELETE /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/cookie] to [DELETE http://127.0.0.1:8001/wd/hub/session/d3dbf2e276dac044c314e46099c7fd79/cookie] with body: {}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"d3dbf2e276dac044c314e46099c7fd79","status":0,"value":null}
[info] [35m[JSONWP Proxy][39m Replacing sessionId d3dbf2e276dac044c314e46099c7fd79 with d97aa8e2-3bfb-421b-8cb1-33bd01f107cd
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/cookie [39m[32m200[39m [90m140 ms - 76[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/url[39m
[info] [35m[HTTP][39m [90m{"url":"https://www.corteva.ca/"}[39m
[info] [35m[W3C][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/url' to command name 'setUrl'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/url] to [POST http://127.0.0.1:8001/wd/hub/session/d3dbf2e276dac044c314e46099c7fd79/url] with body: {"url":"https://www.corteva.ca/"}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"d3dbf2e276dac044c314e46099c7fd79","status":0,"value":null}
[info] [35m[JSONWP Proxy][39m Replacing sessionId d3dbf2e276dac044c314e46099c7fd79 with d97aa8e2-3bfb-421b-8cb1-33bd01f107cd
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/url [39m[32m200[39m [90m5152 ms - 76[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/element[39m
[info] [35m[HTTP][39m [90m{"value":"//div[@data-componentname='globalHeader']","using":"xpath"}[39m
[info] [35m[W3C][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/element' to command name 'findElement'
[debug] [35m[JSONWP Proxy][39m Proxying [POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/element] to [POST http://127.0.0.1:8001/wd/hub/session/d3dbf2e276dac044c314e46099c7fd79/element] with body: {"value":"//div[@data-componentname='globalHeader']","using":"xpath"}[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"d3dbf2e276dac044c314e46099c7fd79","status":0,"value":{"ELEMENT":"0.4317755771183933-1"}}
[info] [35m[JSONWP Proxy][39m Replacing sessionId d3dbf2e276dac044c314e46099c7fd79 with d97aa8e2-3bfb-421b-8cb1-33bd01f107cd
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/element [39m[32m200[39m [90m113 ms - 106[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute/sync[39m
[info] [35m[HTTP][39m [90m{"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsuppo[39m
[info] [35m[W3C][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[JSONWP Proxy][39m Matched '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute/sync' to command name 'execute'
[info] [35m[Protocol Converter][39m Rewrote the original URL '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute/sync' to '/wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute' for MJSONWP protocol
[debug] [35m[JSONWP Proxy][39m Proxying [POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute] to [POST http://127.0.0.1:8001/wd/hub/session/d3dbf2e276dac044c314e46099c7fd79/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k<arguments.length;k++)e[k-2]=arguments[k];return a.prototype[c].apply(b,e)}})();var m=\"unknown error\",l={15:\"element not selectable\",11:\"element not visible\"};l[31]=m;l[30]=m;l[24]=\"invalid cookie domain\";l[29]=\"invalid element coordinates\";l[12]=\"invalid element state\";l[32]=\"invalid selector\";l[51]=\"invalid selector\";\nl[52]=\"invalid selector\";l[17]=\"javascript error\";l[405]=\"unsupported operation\";l[34...
[debug] [35m[JSONWP Proxy][39m Got response with status 200: {"sessionId":"d3dbf2e276dac044c314e46099c7fd79","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n  (Session info: chrome=70.0.3538.110)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[debug] [35m[W3C][39m Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute has failed
[debug] [35m[W3C][39m     at JWProxy.proxy$ (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[debug] [35m[W3C][39m     at tryCatch (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[debug] [35m[W3C][39m     at GeneratorFunctionPrototype.invoke (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[debug] [35m[W3C][39m     at run (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:75:1)
[debug] [35m[W3C][39m     at C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\es6.promise.js:92:1
[debug] [35m[W3C][39m     at flush (C:\Users\sl4843\AppData\Local\appium-desktop\app-1.8.2\resources\app\webpack:\~\babel-polyfill\~\core-js\modules\_microtask.js:18:1)
[debug] [35m[W3C][39m     at process._tickCallback (internal/process/next_tick.js:61:11)
[debug] [35m[MJSONWP][39m Matched JSONWP error code 13 to UnknownError
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/d97aa8e2-3bfb-421b-8cb1-33bd01f107cd/execute/sync [39m[31m500[39m [90m63 ms - 2671[39m
[info] [35m[HTTP][39m [90m[39m

**Comment by dpgraham** [comment]
Related to this: https://github.com/appium/appium/issues/11510

**Comment by dpgraham** [comment]
Try setting `automationName=UiAutomator2`

**Comment by Tanatik** [comment]
I has same trouble with Appium v1.14.0 in version 1.15.1  part of the trouble  is gone. 
code works correctly on Java, but is not correctly on Kotlin
