### ISSUE TITLE
Issues with xcodebuild failure - unable to launch app using the new Desktop version 1.0.0-beta3

### ISSUE THREAD

**Issue by w2aRahul** [appium/appium-desktop#87]
Hi Team,

I am facing Issues with xcodebuild failure - unable to launch app using the new Desktop version 1.0.0-beta3

Any configuration I may be missing?

Everything works fine for Android

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: EROFS: read-only file system, mkdir '/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:337:15)
    at tryCatch (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
<img width="886" alt="screen shot 2017-03-15 at 1 52 50 am" src="https://cloud.githubusercontent.com/assets/4704874/23920775/fbcbd234-0921-11e7-91a3-02c99c4f226d.png">

**Comment by dpgraham** [comment]
This is a permissions error. Please refer to https://github.com/appium/appium/issues/8033 for a fix

**Comment by jlipps** [comment]
@w2aRahul are you trying to run the app from a DMG? you cannot, you need to copy it to your filesystem first.

**Comment by jlipps** [comment]
(I just added a note to the README explaining that running from the DMG doesn't work)

**Comment by w2aRahul** [comment]
Thanks for the quick response Jonathan, I tried building the app and WebDriverAgent from xcode and then while running the code it shows the same permission error:

I just started the server from the new GUI

any clue on how to resolve the permission issue as the folder shows read permissions only

[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: EROFS: read-only file system, mkdir '/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'
    at XCUITestDriver.quitAndUninstall$ (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:337:15)
    at tryCatch (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 22793 ms - 445

**Comment by jlipps** [comment]
@w2aRahul how are you running Appium Desktop?

**Comment by jlipps** [comment]
it looks like you are running it from `/private/var/folders/gq/djnryhnn4zjcgj9jxg1pp8cc0000gn/T/AppTranslocation/8288C9BA-6E5D-4141-BB42-0611B68CE113/d/Appium.app` which is a very odd place to run an app from

**Comment by w2aRahul** [comment]
Thanks I just changed the location to the Application folder as suggested by you in README and now getting below error:  Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

[Xcode] 2017-03-15 02:40:00.348 xcodebuild[4483:127075] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/rahularora/Library/Developer/Xcode/DerivedData/WebDriverAgent-cvqckynzuuktkogfpkkkgyompmoj/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fdc1afc79b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-03-15 02:40:00.348 xcodebuild[4483:127075] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 4482)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:337:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:337:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:337:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 36029 ms - 230

**Comment by jlipps** [comment]
@w2aRahul can you delete Appium Desktop from your machine, then copy it from the DMG to /Applications, then try again by running from /Applications.

**Comment by w2aRahul** [comment]
Awesome, finally it did work 👍 

Thanks for all your support on this Jonathan !!!

**Comment by jlipps** [comment]
You're welcome, have fun!

**Comment by cpt-buzz** [comment]
Hi there, sorry for my bad english first. I get this error if i launch my app and using the new Desktop version 1.0.0-beta3 

Error
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

I think its not the signature error, because i checked the https://github.com/appium/appium-xcuitest-driver/pull/217/commits/77e7749d2d9bbb24cbf7282f8e5446c4d10e30bf its the same code like there. 

Do you have a solution for me? I don't wanna run the app on real devices! I wanna use the simulator only.

Thx,
Saintz

**Comment by imurchie** [comment]
@cpt-buzz Please add the `showXcodeLog` capability (set to `true`) and post a link to a [gist](https://gist.github.com) with the _full_ Appium server logs.

**Comment by cpt-buzz** [comment]
@imurchie Hope i did correctly :) 
https://gist.github.com/cpt-buzz/ce7cae1fbd1298dca3b7c446acaa227f

**Comment by imurchie** [comment]
You need to upgrade the Appium server. This version you are using does not support Xcode 8.3.

**Comment by cpt-buzz** [comment]
@imurchie Thx for your fast answer. I have uninstalled the appium 1.6.4 beta and installed the appium 1.6.4-beta.2, but in the appium desktop i see again the "Welcome to Appium v1.6.4-beta" Version. How to get the correct version in the appium desktop gui?

**Comment by dpgraham** [comment]
Appium Desktop has a fixed version that's bundled with the application. It doesn't use the version that you have globally installed.

See this issue https://github.com/appium/appium-desktop/issues/116. It explains how to use Appium Desktop with a separate Appium server.

p.s.: Once we get 1.6.4 released we'll be releasing v1.0.0 of Appium Desktop with 1.6.4 bundled

**Comment by GeeSlimmy** [comment]
so happy i found this post I was also facing the same issues as w2aRahul!! Thanks guys!

**Comment by sjdptn** [comment]
An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "EROFS: read-only file system, mkdir '/private/var/folders/5d/m1b_30697m3dz3d4__4q_50c0000gn/T/AppTranslocation/32437266-384A-439E-852F-D74CADD41000/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'".

I'm getting this error and not able to locate the folder to change the permission?
